import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import path from "path";
import { execSync } from "child_process";
import runtimeErrorOverlay from "@replit/vite-plugin-runtime-error-modal";

/**
 * Vite configuration supporting three build modes:
 *
 *   pnpm run dev          → dev server (command = "serve")
 *   pnpm run build:client → client bundle → dist/public/
 *   pnpm run build:ssr    → SSR Node bundle → dist/server/  (VITE_SSR=true)
 *
 * PORT is only required for the dev/preview server; build modes skip the check.
 */

// PORT is needed for `vite dev` and `vite preview` but not for `vite build`.
// During builds in the Replit deployment pipeline, PORT is always present via
// [services.env] in artifact.toml, so this guard only helps local invocations.
const isBuildStep = process.argv.some((a) => a === "build");
const rawPort = process.env.PORT;

if (!rawPort && !isBuildStep) {
  throw new Error(
    "PORT environment variable is required but was not provided.",
  );
}

const port = rawPort ? Number(rawPort) : 0;

if (port !== 0 && (Number.isNaN(port) || port <= 0)) {
  throw new Error(`Invalid PORT value: "${rawPort}"`);
}

const basePath = process.env.BASE_PATH ?? "/";

// Whether this is the SSR bundle build (VITE_SSR=true vite build)
const isSSR = process.env.VITE_SSR === "true";

/**
 * Vite plugin: generate the XML sitemap once during the client build.
 * Skipped for the SSR bundle build to avoid running it twice.
 */
function sitemapPlugin() {
  return {
    name: "generate-sitemap",
    buildStart() {
      if (isSSR) return; // SSR build — sitemap already generated by client build
      execSync("pnpm run generate-sitemap", {
        cwd: import.meta.dirname,
        stdio: "inherit",
      });
    },
  };
}

export default defineConfig({
  base: basePath,
  plugins: [
    sitemapPlugin(),
    react(),
    tailwindcss(),
    ...(process.env.NODE_ENV !== "production"
      ? [runtimeErrorOverlay()]
      : []),
    ...(process.env.NODE_ENV !== "production" &&
    process.env.REPL_ID !== undefined
      ? [
          await import("@replit/vite-plugin-cartographer").then((m) =>
            m.cartographer({
              root: path.resolve(import.meta.dirname, ".."),
            }),
          ),
          await import("@replit/vite-plugin-dev-banner").then((m) =>
            m.devBanner(),
          ),
        ]
      : []),
  ],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "src"),
      "@assets": path.resolve(import.meta.dirname, "..", "..", "attached_assets"),
    },
    dedupe: ["react", "react-dom"],
  },
  root: path.resolve(import.meta.dirname),
  build: {
    // Client build → dist/public/  (served as static files by artifact.toml)
    // SSR build    → dist/server/  (Node bundle consumed by prerender.ts)
    outDir: isSSR
      ? path.resolve(import.meta.dirname, "dist/server")
      : path.resolve(import.meta.dirname, "dist/public"),
    emptyOutDir: true,
    // Target modern browsers — smaller output, fewer polyfills, better tree-shaking
    target: "es2020",
    // Skip gzip size reporting in CI — no user benefit, slows the build
    reportCompressedSize: false,
    // SSR entry — builds src/entry-server.tsx as a Node-compatible ESM bundle.
    // Falsy value (undefined) uses the normal client build entry (index.html).
    ssr: isSSR ? "src/entry-server.tsx" : undefined,
    rollupOptions: isSSR ? {} : {
      output: {
        manualChunks: {
          "vendor-react": ["react", "react-dom", "react-dom/client", "react-helmet-async"],
          "vendor-motion": ["framer-motion"],
          "vendor-query": ["@tanstack/react-query"],
          "vendor-radix": [
            "@radix-ui/react-accordion",
            "@radix-ui/react-dialog",
            "@radix-ui/react-dropdown-menu",
            "@radix-ui/react-select",
            "@radix-ui/react-toast",
            "@radix-ui/react-tooltip",
          ],
        },
      },
    },
  },
  esbuild: {
    // Strip debugger statements from production bundles
    drop: process.env.NODE_ENV === "production" ? ["debugger"] : [],
  },
  server: {
    port: port || undefined,
    strictPort: true,
    host: "0.0.0.0",
    allowedHosts: true,
    fs: {
      strict: true,
    },
  },
  preview: {
    port: port || undefined,
    host: "0.0.0.0",
    allowedHosts: true,
  },
  // SSR build: do NOT add noExternal for react-helmet-async.
  // Its canUseDOM static field reads `typeof window !== "undefined"` at module
  // load time. If Vite bundles it (noExternal), its browser-target transform
  // replaces typeof-window with `true`, making canUseDOM=true → Helmet skips
  // SSR context population entirely. Leaving it external lets Node.js require()
  // it at runtime where window is genuinely undefined → canUseDOM=false → SSR
  // context is populated correctly after renderToString.
});
