import type { Region } from "./region-services";

export type ArticleContext = {
  region: Region | null;
  serviceSlug: string;
  relatedWorkSlugs: string[];
  relatedBlogSlugs?: string[];
  categoryEn?: string;
  categoryAr?: string;
  editorialUpdatedAt?: string;
};

/** A dated correction must never backdate a later CMS edit. */
export function articleModifiedAt(...values: Array<string | Date | null | undefined>): string | undefined {
  return values.filter((value): value is string | Date => value != null)
    .map(value => ({ value: value instanceof Date ? value.toISOString() : value, time: new Date(value).getTime() }))
    .filter(value => Number.isFinite(value.time))
    .sort((a, b) => b.time - a.time)[0]?.value;
}

/** Explicit editorial routing; null means the article does not establish one country. */
export const ARTICLE_CONTEXT: Readonly<Record<string, ArticleContext>> = {
  "mta-ykwn-alslh-afdl-mn-alastmrar-fy-alkhswmh": { editorialUpdatedAt: "2026-09-07", region: null, serviceSlug: "business-law", relatedWorkSlugs: ["kyf-saadt-kawnslw-fy-astrdad-300000-ryal-abr-slh-qdayy-fy-nzaa-tjary"], relatedBlogSlugs: ["bna-astratyjyh-aldfaa-qbl-bd-alkhswmh", "hmayh-alamyl-mn-mswdh-alaqd-ala-altwqya"] },
  "mta-ysthq-alwsyt-altjary-kaml-amwlth": { editorialUpdatedAt: "2026-09-07", region: "sa", serviceSlug: "business-law", relatedWorkSlugs: ["kawnslw-w-tkhfyd-mtalbh-amwlh-tjaryh-mn-348-mlywn-ryal-ila-584-alf-ryal"], relatedBlogSlugs: ["lys-kl-mblgh-ytalb-bh-yhkm-bh-kyf-tfkk-almtalbat-altjaryh-qbl-bna-aldfaa", "athbat-alaqwd-amam-alqda-alsawdy", "hmayh-alamyl-mn-mswdh-alaqd-ala-altwqya"] },
  "hyn-ykwn-alaqrar-aqwa-mn-alankar": { editorialUpdatedAt: "2026-09-06", region: "sa", serviceSlug: "real-estate", relatedWorkSlugs: [], categoryEn: "Real Estate", categoryAr: "العقارات", relatedBlogSlugs: ["mta-ythwl-twqya-alaaml-ala-mhdr-almrajah-ala-aqrar-balmswwlyh", "athbat-alaqwd-amam-alqda-alsawdy", "alaywb-alkhfyh-fy-alaqwd-wathrha-alqanwny"] },
  "lys-kl-mblgh-ytalb-bh-yhkm-bh-kyf-tfkk-almtalbat-altjaryh-qbl-bna-aldfaa": { editorialUpdatedAt: "2026-09-07", region: "sa", serviceSlug: "business-law", relatedWorkSlugs: ["kyf-sahmt-kawnslw-fy-tkhfyd-mtalbh-mn-500-alf-ryal-ila-227"], relatedBlogSlugs: ["almswwlyh-alaqdyh-fy-almaamlat-altjaryh", "athbat-alaqwd-amam-alqda-alsawdy", "bna-astratyjyh-aldfaa-qbl-bd-alkhswmh"] },
  "mta-ysbh-astamal-alhq-tasfa-fy-alnzam-alsawdy": { editorialUpdatedAt: "2026-09-06", region: "sa", serviceSlug: "contracts", relatedWorkSlugs: [], relatedBlogSlugs: ["alfrq-byn-alfskh-waltawyd-fy-alaqwd-altjaryh", "altwsyat-alamlyh-lsyaghh-aqd-qwy", "Penalty-clause-in-saudi"] },
  "mta-yqbl-altmas-aaadh-alnzr-atjahat-qdayyh-mhmh": { region: "sa", serviceSlug: "enforcement", relatedWorkSlugs: ["tfkyk-mstndat-altmas-aaadh-alnzr-bnjah"], editorialUpdatedAt: "2026-09-07", relatedBlogSlugs: ["athbat-alaqwd-amam-alqda-alsawdy", "mta-ythwl-twqya-alaaml-ala-mhdr-almrajah-ala-aqrar-balmswwlyh", "bna-astratyjyh-aldfaa-qbl-bd-alkhswmh"] },
  "alsnd-lamr-kadah-dman-mta-ythwl-ala-khtr-tnfydhy": { region: "sa", serviceSlug: "enforcement", relatedWorkSlugs: ["astratyjyh-kawnslw-lastrdad-sndat-lamr-bqymh-17-mlywn-ryal", "hdwd-mswwlyh-alkfyl-fy-alsnd-lamr"], editorialUpdatedAt: "2026-09-06", relatedBlogSlugs: ["almswwlyh-alaqdyh-fy-almaamlat-altjaryh", "alfrq-byn-alfskh-waltawyd-fy-alaqwd-altjaryh", "Penalty-clause-in-saudi"] },
  "alaywb-alkhfyh-fy-alaqwd-wathrha-alqanwny": { editorialUpdatedAt: "2026-09-07", region: "sa", serviceSlug: "contracts", relatedWorkSlugs: [], relatedBlogSlugs: ["commercial-supply-contracts-in-saudi", "aqwd-almqawlat-fy-alnzam-alsawdy", "alfrq-byn-alfskh-waltawyd-fy-alaqwd-altjaryh"] },
  "hmayh-alamyl-mn-mswdh-alaqd-ala-altwqya": { editorialUpdatedAt: "2026-09-07", region: null, serviceSlug: "contracts", relatedWorkSlugs: ["mnhj-kawnslw-fy-mrajah-alaqwd-altjaryh", "altfawd-alqanwny-aldhky"], relatedBlogSlugs: ["syghh-mdhkrh-tfahm-qablh-lltadyl", "mnhjyh-5why-fy-alaml-alqanwny", "bna-astratyjyh-aldfaa-qbl-bd-alkhswmh"] },
  "mta-ythwl-twqya-alaaml-ala-mhdr-almrajah-ala-aqrar-balmswwlyh": { editorialUpdatedAt: "2026-09-07", region: "sa", serviceSlug: "employment-law", relatedWorkSlugs: ["kyf-adart-kawnslw-mrajah-mhasbyh-hsash"], relatedBlogSlugs: ["anha-aqd-alaml-bdwn-sbb-mshrwa", "altakhr-fy-alrwatb-aw-alamtnaa-an-dfaha", "athbat-alaqwd-amam-alqda-alsawdy"] },
  "alfrq-byn-alfskh-waltawyd-fy-alaqwd-altjaryh": { editorialUpdatedAt: "2026-09-07", region: "sa", serviceSlug: "contracts", relatedWorkSlugs: ["kyf-qadt-astratyjyh-kawnslw-ila-rfd-dawa-fskh-aqd-bya-wtawydat-bmlayyn-alryalat", "fskh-aqd-snaay-wastrdad-aldfah-almqdmh"], relatedBlogSlugs: ["fskh-alaqd-altjary-fy-alnzam-alsawdy", "almswwlyh-alaqdyh-fy-almaamlat-altjaryh", "Penalty-clause-in-saudi"] },
  "bna-astratyjyh-aldfaa-qbl-bd-alkhswmh": { editorialUpdatedAt: "2026-09-06", region: null, serviceSlug: "business-law", relatedWorkSlugs: ["darsh-qdyh-qbl-alnzaa", "thwyl-qdyh-mn-rfd-ala-qbwl-wtayyd"], relatedBlogSlugs: ["mnhjyh-5why-fy-alaml-alqanwny", "mta-ykwn-alslh-afdl-mn-alastmrar-fy-alkhswmh", "hmayh-alamyl-mn-mswdh-alaqd-ala-altwqya"] },
  "mta-yfqd-shrt-althkym-athrh-alamly-fy-alnzaa": { editorialUpdatedAt: "2026-09-07", region: "sa", serviceSlug: "arbitration", relatedWorkSlugs: ["kyf-sahmt-kawnslw-fy-anjah-mlf-thkymy-kaml"], relatedBlogSlugs: ["altwsyat-alamlyh-lsyaghh-aqd-qwy", "fskh-alaqd-altjary-fy-alnzam-alsawdy", "mta-yqbl-altmas-aaadh-alnzr-atjahat-qdayyh-mhmh"] },
  "altwqya-ala-byad": { region: null, serviceSlug: "contracts", relatedWorkSlugs: [], editorialUpdatedAt: "2026-09-07", relatedBlogSlugs: ["hmayh-alamyl-mn-mswdh-alaqd-ala-altwqya", "syghh-mdhkrh-tfahm-qablh-lltadyl"] },
  "mta-ykwn-alqrar-aladary-qabla-llalgha-amam-dywan-almzalm": { editorialUpdatedAt: "2026-09-06", region: "sa", serviceSlug: "administrative-law", relatedWorkSlugs: [], relatedBlogSlugs: ["mta-ysbh-astamal-alhq-tasfa-fy-alnzam-alsawdy", "bna-astratyjyh-aldfaa-qbl-bd-alkhswmh"] },
  "syghh-mdhkrh-tfahm-qablh-lltadyl": { region: null, serviceSlug: "contracts", relatedWorkSlugs: [], editorialUpdatedAt: "2026-09-06", relatedBlogSlugs: ["hmayh-alamyl-mn-mswdh-alaqd-ala-altwqya", "altwqya-ala-byad", "mnhjyh-5why-fy-alaml-alqanwny"] },
  "almswwlyh-an-fal-alghyr": { editorialUpdatedAt: "2026-09-07", region: null, serviceSlug: "civil-law", relatedWorkSlugs: ["mn-alkhta-ala-altawyd-kyf-hddt-kawnslw-almswwl-almbashran-hadth", "maaljh-halh-khta-tby"], relatedBlogSlugs: ["almswwlyh-alaqdyh-fy-alqanwn-alswry", "contractual-liability-in-commercial-transactions"] },
  "hdwd-alymyn-alhasmh-fy-alathbat-almdny-swry": { editorialUpdatedAt: "2026-09-07", region: "syr", serviceSlug: "civil-law", relatedWorkSlugs: [], relatedBlogSlugs: ["contract-interpretation-syrian-courts", "alrda-fy-alqanwn-alswry", "almswwlyh-alaqdyh-fy-alqanwn-alswry"] },
  "mnhjyh-5why-fy-alaml-alqanwny": { editorialUpdatedAt: "2026-09-06", region: null, serviceSlug: "contracts", relatedWorkSlugs: [], relatedBlogSlugs: ["bna-astratyjyh-aldfaa-qbl-bd-alkhswmh", "hmayh-alamyl-mn-mswdh-alaqd-ala-altwqya", "mta-ykwn-alslh-afdl-mn-alastmrar-fy-alkhswmh"] },
  "mhl-alaqd-fy-alqanwn-alswry": { region: "syr", serviceSlug: "contracts", relatedWorkSlugs: [], editorialUpdatedAt: "2026-09-07", relatedBlogSlugs: ["alaqd-fy-alqanwn-alswry", "alrda-fy-alqanwn-alswry", "alahlyh-fy-altaaqd-fy-alqanwn-alswry"] },
  "anha-aqd-alaml-bdwn-sbb-mshrwa": { region: "sa", serviceSlug: "employment-law", relatedWorkSlugs: ["tshyh-altkyyf-alqanwny-lanha-aqd-alaml", "hyn-la-tnthy-alqdyh-balhkm-alawl-kyf-qlbt-kawnslw-msar-nzaa-amaly"], editorialUpdatedAt: "2026-09-07", relatedBlogSlugs: ["altakhr-fy-alrwatb-aw-alamtnaa-an-dfaha", "mta-ythwl-twqya-alaaml-ala-mhdr-almrajah-ala-aqrar-balmswwlyh"] },
  "altakhr-fy-alrwatb-aw-alamtnaa-an-dfaha": { region: "sa", serviceSlug: "employment-law", relatedWorkSlugs: ["tshyh-altkyyf-alqanwny-lanha-aqd-alaml"], editorialUpdatedAt: "2026-09-07", relatedBlogSlugs: ["anha-aqd-alaml-bdwn-sbb-mshrwa", "mta-ythwl-twqya-alaaml-ala-mhdr-almrajah-ala-aqrar-balmswwlyh"] },
  "alahlyh-fy-altaaqd-fy-alqanwn-alswry": { region: "syr", serviceSlug: "contracts", relatedWorkSlugs: [], relatedBlogSlugs: ["alrda-fy-alqanwn-alswry", "defects-of-will-syrian-law", "mhl-alaqd-fy-alqanwn-alswry"], editorialUpdatedAt: "2026-09-07" },
  "adarh-almkhatr-fy-alaqwd-wfq-alnzam-alsawdy": { editorialUpdatedAt: "2026-09-07", region: "sa", serviceSlug: "contracts", relatedWorkSlugs: ["adrah-almkhatr-fy-aqd-tamyny", "mnhj-kawnslw-fy-mrajah-alaqwd-altjaryh"], relatedBlogSlugs: ["altwsyat-alamlyh-lsyaghh-aqd-qwy", "commercial-supply-contracts-in-saudi", "Penalty-clause-in-saudi"] },
  "altwsyat-alamlyh-lsyaghh-aqd-qwy": { editorialUpdatedAt: "2026-09-07", region: "sa", serviceSlug: "contracts", relatedWorkSlugs: ["atfaqyh-atar-ltqdym-alkhdmat-altqnyh-whlwl-aldhka-alastnaay", "mnhj-kawnslw-fy-mrajah-alaqwd-altjaryh"], relatedBlogSlugs: ["formation-of-commercial-contracts-saudi-law", "adarh-almkhatr-fy-alaqwd-wfq-alnzam-alsawdy", "athbat-alaqwd-amam-alqda-alsawdy"] },
  "alrda-fy-alqanwn-alswry": { region: "syr", serviceSlug: "contracts", relatedWorkSlugs: [], editorialUpdatedAt: "2026-09-07", relatedBlogSlugs: ["alahlyh-fy-altaaqd-fy-alqanwn-alswry", "mhl-alaqd-fy-alqanwn-alswry", "defects-of-will-syrian-law"] },
  "athbat-alaqwd-amam-alqda-alsawdy": { editorialUpdatedAt: "2026-09-07", region: "sa", serviceSlug: "contracts", relatedWorkSlugs: ["thwyl-qdyh-mn-rfd-ala-qbwl-wtayyd", "kawnslw-tdam-shrkh-lastrdad-448958-ryala-an-aqd-mqawlat"], relatedBlogSlugs: ["e-contracts-legal-validity-saudi-arabia", "mta-ythwl-twqya-alaaml-ala-mhdr-almrajah-ala-aqrar-balmswwlyh", "almswwlyh-alaqdyh-fy-almaamlat-altjaryh"] },
  "almswwlyh-alaqdyh-fy-almaamlat-altjaryh": { editorialUpdatedAt: "2026-09-06", region: "sa", serviceSlug: "contracts", relatedWorkSlugs: [], relatedBlogSlugs: ["contractual-liability-in-commercial-transactions", "athbat-alaqwd-amam-alqda-alsawdy", "lys-kl-mblgh-ytalb-bh-yhkm-bh-kyf-tfkk-almtalbat-altjaryh-qbl-bna-aldfaa"] },
  "hwkmh-alshrkat-kdmanh-mwdwayh-lhmayh-hqwq-msahmy-alaqlyh": { editorialUpdatedAt: "2026-09-07", region: "sa", serviceSlug: "companies-law", relatedWorkSlugs: ["kyf-athbtt-kawnslw-alshrakh", "almttlbat-alqanwnyh-walhwkmh-aldakhlyh"], relatedBlogSlugs: ["aqwd-alwkalat-altjaryh-fy-alnzam-alsawd", "aqwd-alamtyaz-altjary-alfrnshayz-fy-alnzam-alsawdy", "altwsyat-alamlyh-lsyaghh-aqd-qwy"] },
  "alaqd-fy-alqanwn-alswry": { editorialUpdatedAt: "2026-09-07", region: "syr", serviceSlug: "contracts", relatedWorkSlugs: [], relatedBlogSlugs: ["alrda-fy-alqanwn-alswry", "alahlyh-fy-altaaqd-fy-alqanwn-alswry", "mhl-alaqd-fy-alqanwn-alswry"] },
  "altawyd-an-alakhlal-balaqd-fy-alqanwn-alswry": { region: "syr", serviceSlug: "contracts", relatedWorkSlugs: [], relatedBlogSlugs: ["almswwlyh-alaqdyh-fy-alqanwn-alswry", "performance-of-contracts-in-good-faith-under-syrian-law", "contract-interpretation-syrian-courts"], editorialUpdatedAt: "2026-09-06" },
  "aqwd-alamtyaz-altjary-alfrnshayz-fy-alnzam-alsawdy": { editorialUpdatedAt: "2026-09-07", region: "sa", serviceSlug: "business-law", relatedWorkSlugs: ["rfd-dawa-fskh-aqd-amtyaz-tjary-wtawyd"], relatedBlogSlugs: ["aqwd-alwkalat-altjaryh-fy-alnzam-alsawd", "hwkmh-alshrkat-kdmanh-mwdwayh-lhmayh-hqwq-msahmy-alaqlyh", "altwsyat-alamlyh-lsyaghh-aqd-qwy"] },
  "aqwd-alwkalat-altjaryh-fy-alnzam-alsawd": { editorialUpdatedAt: "2026-09-07", region: "sa", serviceSlug: "business-law", relatedWorkSlugs: [], relatedBlogSlugs: ["aqwd-alamtyaz-altjary-alfrnshayz-fy-alnzam-alsawdy", "hwkmh-alshrkat-kdmanh-mwdwayh-lhmayh-hqwq-msahmy-alaqlyh", "altwsyat-alamlyh-lsyaghh-aqd-qwy"] },
  "almswwlyh-alaqdyh-fy-alqanwn-alswry": { region: "syr", serviceSlug: "contracts", relatedWorkSlugs: [], relatedBlogSlugs: ["altawyd-an-alakhlal-balaqd-fy-alqanwn-alswry", "performance-of-contracts-in-good-faith-under-syrian-law", "contract-interpretation-syrian-courts"], editorialUpdatedAt: "2026-09-06" },
  "aqwd-almqawlat-fy-alnzam-alsawdy": { editorialUpdatedAt: "2026-09-07", region: "sa", serviceSlug: "contracts", relatedWorkSlugs: ["mswwlyh-almqawlyn", "kawnslw-tdam-shrkh-lastrdad-448958-ryala-an-aqd-mqawlat"], relatedBlogSlugs: ["commercial-supply-contracts-in-saudi", "Penalty-clause-in-saudi", "adarh-almkhatr-fy-alaqwd-wfq-alnzam-alsawdy"] },
  "performance-of-contracts-in-good-faith-under-syrian-law": { editorialUpdatedAt: "2026-09-07", region: "syr", serviceSlug: "contracts", relatedWorkSlugs: [], relatedBlogSlugs: ["contract-interpretation-syrian-courts", "almswwlyh-alaqdyh-fy-alqanwn-alswry", "altawyd-an-alakhlal-balaqd-fy-alqanwn-alswry"] },
  "commercial-supply-contracts-in-saudi": { editorialUpdatedAt: "2026-09-07", region: "sa", serviceSlug: "contracts", relatedWorkSlugs: [], relatedBlogSlugs: ["alaywb-alkhfyh-fy-alaqwd-wathrha-alqanwny", "aqwd-almqawlat-fy-alnzam-alsawdy", "Penalty-clause-in-saudi"] },
  "contract-interpretation-syrian-courts": { editorialUpdatedAt: "2026-09-07", region: "syr", serviceSlug: "contracts", relatedWorkSlugs: [], relatedBlogSlugs: ["performance-of-contracts-in-good-faith-under-syrian-law", "alrda-fy-alqanwn-alswry", "alaqd-fy-alqanwn-alswry"] },
  "e-contracts-legal-validity-saudi-arabia": { editorialUpdatedAt: "2026-09-07", region: "sa", serviceSlug: "contracts", relatedWorkSlugs: ["astsharh-fy-ahtyal-maly", "mnazah-tnfydh"], relatedBlogSlugs: ["athbat-alaqwd-amam-alqda-alsawdy", "formation-of-commercial-contracts-saudi-law", "altwsyat-alamlyh-lsyaghh-aqd-qwy"] },
  "fskh-alaqd-altjary-fy-alnzam-alsawdy": { editorialUpdatedAt: "2026-09-07", region: "sa", serviceSlug: "contracts", relatedWorkSlugs: ["fskh-aqd-snaay-wastrdad-aldfah-almqdmh", "fskh-aqd-iyjar-tjary-bsbb-khta-byanat-mnsh-iyjar"], relatedBlogSlugs: ["alfrq-byn-alfskh-waltawyd-fy-alaqwd-altjaryh", "almswwlyh-alaqdyh-fy-almaamlat-altjaryh", "Penalty-clause-in-saudi"] },
  "defects-of-will-syrian-law": { region: "syr", serviceSlug: "contracts", relatedWorkSlugs: [], relatedBlogSlugs: ["alahlyh-fy-altaaqd-fy-alqanwn-alswry", "alrda-fy-alqanwn-alswry", "alaqd-fy-alqanwn-alswry"], editorialUpdatedAt: "2026-09-06" },
  "consensual-formal-real-contracts-syrian-law": { editorialUpdatedAt: "2026-09-06", region: "syr", serviceSlug: "contracts", relatedWorkSlugs: ["drash-qdyh-aqaryh-maqdh-fy-swrya"], relatedBlogSlugs: ["alaqd-fy-alqanwn-alswry", "alrda-fy-alqanwn-alswry", "mhl-alaqd-fy-alqanwn-alswry"] },
  "contractual-liability-in-commercial-transactions": { editorialUpdatedAt: "2026-09-07", region: "sa", serviceSlug: "contracts", relatedWorkSlugs: [], relatedBlogSlugs: ["almswwlyh-alaqdyh-fy-almaamlat-altjaryh", "alfrq-byn-alfskh-waltawyd-fy-alaqwd-altjaryh", "Penalty-clause-in-saudi"] },
  "formation-of-commercial-contracts-saudi-law": { editorialUpdatedAt: "2026-09-07", region: "sa", serviceSlug: "contracts", relatedWorkSlugs: [], relatedBlogSlugs: ["altwsyat-alamlyh-lsyaghh-aqd-qwy", "e-contracts-legal-validity-saudi-arabia", "athbat-alaqwd-amam-alqda-alsawdy"] },
  "Penalty-clause-in-saudi": { region: "sa", serviceSlug: "contracts", relatedWorkSlugs: ["mswwlyh-almqawlyn"], editorialUpdatedAt: "2026-09-07", relatedBlogSlugs: ["adarh-almkhatr-fy-alaqwd-wfq-alnzam-alsawdy", "fskh-alaqd-altjary-fy-alnzam-alsawdy", "commercial-supply-contracts-in-saudi"] },
};

export function articleContextRegion(input: { slug?: string; jurisdiction?: string | null; titleEn?: string; titleAr?: string; excerptEn?: string; excerptAr?: string }): Region | undefined {
  const assigned = input.slug ? ARTICLE_CONTEXT[input.slug] : undefined;
  if (assigned) return assigned.region ?? undefined;
  if (input.jurisdiction === "sa" || input.jurisdiction === "syr" || input.jurisdiction === "uae") return input.jurisdiction;
  const text = `${input.titleEn ?? ""} ${input.titleAr ?? ""} ${input.excerptEn ?? ""} ${input.excerptAr ?? ""}`;
  const regions: Region[] = [];
  if (/\bSaudi\b|\bKSA\b|السعودي/i.test(text)) regions.push("sa");
  if (/\bSyria\b|\bSyrian\b|سوريا|سورية|السوري/i.test(text)) regions.push("syr");
  if (/United Arab Emirates|\bUAE\b|الإمارات|الامارات/i.test(text)) regions.push("uae");
  return regions.length === 1 ? regions[0] : undefined;
}
