import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { LEGAL_PROBLEM_PAGES, legalProblemPath } from "../artifacts/legal-site/src/lib/legal-problem-pages.js";
import { getMatterAnswer } from "../artifacts/legal-site/src/lib/matter-answer.js";
import { MATTER_ANSWER_ADDITIONS } from "../artifacts/legal-site/src/lib/matter-answer-additions.js";
import { matterSourceGuidance } from "../artifacts/legal-site/src/lib/matter-source-guidance.js";

const out = fileURLToPath(new URL("../output/full-growth-audit-2026-09-07/", import.meta.url));
mkdirSync(out, { recursive: true });
const key = (region: string, service: string, slug: string) => `${region}/${service}/${slug}`;
// Immutable140-topic queue captured by the live/repository audit before remediation.
const missingBefore = new Set<string>([
  "sa/arbitration/recognition-and-enforcement-of-awards",
  "sa/arbitration/foreign-arbitral-award-enforcement",
  "sa/arbitration/challenge-to-arbitration-jurisdiction",
  "sa/enforcement/commercial-debt-recovery",
  "sa/enforcement/unpaid-invoices-and-payment-claims",
  "sa/enforcement/payment-order-and-urgent-debt-recovery",
  "sa/enforcement/execution-against-an-unavailable-or-absconding-debtor",
  "sa/enforcement/bounced-cheque-defence-and-criminal-complaint-concern",
  "sa/banking-finance/guarantees-and-security-enforcement",
  "sa/banking-finance/personal-guarantee-enforcement",
  "sa/banking-finance/frozen-bank-account-and-lifting-request",
  "sa/banking-finance/credit-report-and-banking-record-dispute",
  "sa/tax-zakat/tax-and-zakat-assessments",
  "sa/tax-zakat/objections-and-appeals",
  "sa/tax-zakat/tax-penalties-and-disputes",
  "sa/tax-zakat/tax-audit-and-assessment-objection",
  "sa/tax-zakat/customs-penalty-challenge",
  "sa/tax-zakat/tax-certificate-and-clearance-problem",
  "sa/tax-zakat/corporate-tax-registration-and-filing-problem",
  "sa/tax-zakat/vat-invoice-and-tax-correction-dispute",
  "sa/insurance-law/insurer-and-broker-disputes",
  "sa/insurance-law/traffic-report-and-fault-dispute",
  "sa/insurance-law/uninsured-accident-compensation-claim",
  "sa/insurance-law/personal-injury-compensation-after-an-accident",
  "syr/family-law/child-custody-and-visitation",
  "syr/family-law/alimony-and-child-maintenance",
  "syr/family-law/visitation-order-enforcement",
  "syr/family-law/child-relocation-and-travel-disputes",
  "syr/family-law/recognition-of-foreign-family-judgments",
  "syr/family-law/paternity-dispute",
  "syr/family-law/recognition-and-enforcement-of-a-syrian-family-judgment",
  "syr/employment-law/wrongful-termination",
  "syr/employment-law/workplace-and-disciplinary-disputes",
  "syr/employment-law/resignation-because-of-unpaid-wages",
  "syr/employment-law/experience-certificate-and-service-transfer-dispute",
  "syr/employment-law/sponsorship-transfer-dispute",
  "syr/employment-law/disciplinary-warning-and-workplace-investigation",
  "syr/employment-law/work-permit-or-employment-status-problem",
  "syr/employment-law/work-permit-residency-or-employment-status-problem",
  "syr/employment-law/visa-exit-and-re-entry-restriction-affecting-employment",
  "syr/business-law/commercial-disputes",
  "syr/business-law/supplier-and-customer-claims",
  "syr/business-law/business-contract-risk",
  "syr/business-law/commercial-liability",
  "syr/business-law/negotiation-and-settlement-strategy",
  "syr/business-law/unpaid-business-invoices",
  "syr/business-law/commercial-supply-contract-dispute",
  "syr/business-law/commercial-agency-termination",
  "syr/business-law/commercial-concealment-dispute",
  "syr/business-law/shareholder-and-partner-dispute",
  "syr/business-law/government-tender-dispute",
  "syr/business-law/commercial-agency-and-distribution-termination",
  "syr/real-estate/construction-and-contractor-claims",
  "syr/real-estate/unpaid-rent-and-rental-payment-claim",
  "syr/real-estate/security-deposit-recovery",
  "syr/real-estate/construction-delay-and-defective-construction",
  "syr/real-estate/property-encroachment-and-boundary-dispute",
  "syr/real-estate/expropriation-and-compensation-claim",
  "syr/real-estate/property-service-charge-and-maintenance-dispute",
  "syr/foreign-investment/investor-and-cross-border-disputes",
  "syr/foreign-investment/foreign-investor-compensation-claim",
  "syr/foreign-investment/foreign-investor-and-local-partner-dispute",
  "syr/foreign-investment/cross-border-investment-payment-or-exit-dispute",
  "syr/administrative-law/public-procurement-disputes",
  "syr/administrative-law/public-procurement-dispute",
  "syr/arbitration/urgent-protective-measures",
  "syr/enforcement/unpaid-invoices-and-payment-claims",
  "syr/enforcement/bounced-cheque-execution",
  "syr/enforcement/foreign-judgment-enforcement",
  "syr/enforcement/payment-order-and-urgent-debt-recovery",
  "syr/enforcement/asset-tracing-and-debtor-investigation",
  "syr/enforcement/bounced-cheque-defence-and-criminal-complaint-concern",
  "syr/enforcement/wrongful-debt-collection-or-creditor-harassment-complaint",
  "syr/companies-law/shareholder-and-partner-disputes",
  "syr/companies-law/corporate-governance",
  "syr/companies-law/director-and-manager-liability",
  "syr/companies-law/mergers-dissolution-and-liquidation",
  "syr/companies-law/shareholder-exit-and-buyout-dispute",
  "syr/companies-law/company-dissolution-and-liquidation-dispute",
  "syr/companies-law/partner-withdrawal-and-liquidation-dispute",
  "syr/contracts/contract-drafting-and-review",
  "syr/contracts/breach-of-contract",
  "syr/contracts/penalty-and-compensation-clauses",
  "syr/contracts/negotiation-and-enforcement",
  "syr/contracts/supply-contract-non-delivery",
  "syr/contracts/service-agreement-breach",
  "syr/contracts/contract-evidence-and-electronic-messages",
  "syr/contracts/commercial-contract-dispute-under-syrian-law",
  "syr/contracts/legal-notice-and-demand-letter-drafting",
  "syr/contracts/unpaid-professional-fees-and-service-invoice-dispute",
  "syr/criminal-law/criminal-complaints-and-defence",
  "syr/criminal-law/investigation-and-questioning",
  "syr/criminal-law/trial-and-appeal-preparation",
  "syr/criminal-law/police-complaint-defence",
  "syr/criminal-law/criminal-complaint-before-syrian-authorities",
  "syr/criminal-law/criminal-case-settlement-and-compensation-claim",
  "syr/banking-finance/financing-agreement-review",
  "syr/banking-finance/guarantees-and-security-enforcement",
  "syr/banking-finance/financial-regulatory-compliance",
  "syr/banking-finance/unauthorized-bank-transaction",
  "syr/banking-finance/loan-default-and-restructuring",
  "syr/banking-finance/personal-guarantee-enforcement",
  "syr/banking-finance/loan-guarantee-or-collateral-enforcement-dispute",
  "syr/tax-zakat/objections-and-appeals",
  "syr/tax-zakat/tax-penalties-and-disputes",
  "syr/cyber-law/data-protection-incidents",
  "syr/cyber-law/personal-data-breach-response",
  "syr/cyber-law/personal-data-access-correction-or-deletion-request",
  "syr/cyber-law/online-account-recovery-and-platform-complaint",
  "syr/medical-malpractice/medical-negligence-claims",
  "syr/medical-malpractice/misdiagnosis-and-delayed-diagnosis",
  "syr/medical-malpractice/surgical-and-treatment-errors",
  "syr/medical-malpractice/compensation-and-professional-liability-disputes",
  "syr/medical-malpractice/treatment-injury-and-compensation-claim",
  "syr/medical-malpractice/medical-record-access-and-expert-evidence-dispute",
  "syr/insurance-law/insurer-and-broker-disputes",
  "syr/insurance-law/denied-insurance-claim",
  "syr/insurance-law/delayed-insurance-settlement",
  "syr/insurance-law/policy-coverage-dispute",
  "syr/insurance-law/traffic-report-and-fault-dispute",
  "syr/insurance-law/insurance-claim-dispute-with-a-syrian-insurer",
  "syr/insurance-law/personal-injury-compensation-after-an-accident",
  "syr/civil-law/civil-claims-and-private-disputes",
  "syr/civil-law/contractual-and-non-contractual-liability",
  "syr/civil-law/compensation-claims",
  "syr/civil-law/obligations-and-remedies",
  "syr/civil-law/civil-compensation-claim-in-syria",
  "syr/civil-procedure/evidence-and-procedural-objections",
  "syr/civil-procedure/expert-evidence-and-report-dispute",
  "syr/criminal-procedure/evidence-challenges",
  "syr/criminal-procedure/appeals-and-post-judgment-remedies",
  "syr/criminal-procedure/evidence-challenge-in-criminal-case",
  "syr/criminal-procedure/criminal-appeal-deadline",
  "syr/criminal-procedure/criminal-appeal-and-evidence-objection-in-syria",
  "uae/enforcement-debt-recovery/asset-tracing-and-debtor-investigation",
  "uae/enforcement-debt-recovery/travel-ban-application-for-debt-recovery",
  "uae/enforcement-debt-recovery/service-suspension-and-asset-freezing-request",
  "uae/banking-finance/personal-guarantee-enforcement",
  "uae/insurance/traffic-report-and-fault-dispute",
  "uae/administrative-regulatory/licence-refusal-or-cancellation"
]);
const records = LEGAL_PROBLEM_PAGES.map(page => {
  const id = key(page.region, page.parentServiceSlug, page.slug);
  const answer = getMatterAnswer(page.region, page.parentServiceSlug, page.slug)!;
  const addition = MATTER_ANSWER_ADDITIONS.find(item => item.region === page.region && item.service === page.parentServiceSlug && item.problems.includes(page.slug));
  const inherited = matterSourceGuidance(page.region, page.parentServiceSlug, page.slug);
  return {
    id,
    region: page.region,
    service: page.parentServiceSlug,
    topic: { en: page.titleEn, ar: page.titleAr },
    urls: { en: `https://counselo-legal.com${legalProblemPath(page.region, "en", page.parentServiceSlug, page.slug)}`, ar: `https://counselo-legal.com${legalProblemPath(page.region, "ar", page.parentServiceSlug, page.slug)}` },
    wasInOriginal140GapQueue: missingBefore.has(id),
    evidenceStatus: answer.evidenceStatus,
    coverageMeaning: answer.evidenceStatus === "source-routing-only" ? "Issue-specific preparation only; current substantive procedure still missing" : addition?.sourceLimitation ? "Substantive scoped framework with explicit remaining source checks" : "Explicitly assigned substantive guidance; no claim of comprehensive legal review",
    evidenceSelection: addition?.sourceMethod ?? "inherited-explicit-guidance",
    evidenceIds: answer.evidenceIds,
    existingGuidanceIds: inherited.map(item => item.id),
    sources: answer.sources,
    remainingSourceChecks: answer.sourceLimitation ?? "The cited issue guidance is retained within its stated scope. Full current-law consolidation, case-specific application and professional legal review are not certified by this coverage ledger.",
    sourceResearch: addition ? addition.sourceMethod === "existing-explicit-guidance" ? "Expressly remapped existing source guidance; source provenance retained" : "New source research and scoped drafting in this remediation pass" : "Existing exact-topic source guidance retained; not every source was independently reopened in this pass",
    legalProfessionalReviewClaimed: false,
    updatedAt: answer.updatedAt,
    question: answer.question,
    answer: answer.answer,
    description: answer.description,
    descriptionCharacters: { en: answer.description.en.length, ar: answer.description.ar.length },
  };
});
const descriptions = records.flatMap(item => [item.description.en, item.description.ar]);
const unresolved = records.filter(item => item.evidenceStatus === "source-routing-only").map(item => ({ id: item.id, remainingSourceChecks: item.remainingSourceChecks }));
const result = {
  generatedAt: new Date().toISOString(),
  scope: "Local implementation evidence; not deployed output, search performance or a professional legal review",
  summary: {
    totalTopics: records.length,
    localizedUrls: records.length * 2,
    originalGapTopics: missingBefore.size,
    originalGapsNowWithScopedSubstantiveGuidance: records.filter(item => item.wasInOriginal140GapQueue && item.evidenceStatus === "source-supported").length,
    explicitAdditions: MATTER_ANSWER_ADDITIONS.length,
    topicsUsingAdditions: records.filter(item => item.evidenceSelection !== "inherited-explicit-guidance").length,
    additionTopicsWithExplicitRemainingSourceChecks: records.filter(item => item.coverageMeaning.startsWith("Substantive scoped framework")).length,
    topicsUsingNewSourceResearch: records.filter(item => item.sourceResearch.startsWith("New source research")).length,
    topicsUsingExpressExistingGuidanceRemapping: records.filter(item => item.sourceResearch.startsWith("Expressly remapped")).length,
    topicsWithSubstantiveGuidance: records.filter(item => item.evidenceStatus === "source-supported").length,
    currentProcedureExceptions: unresolved,
    duplicateEnglishAnswers: records.length - new Set(records.map(item => item.answer.en)).size,
    duplicateArabicAnswers: records.length - new Set(records.map(item => item.answer.ar)).size,
    duplicateDescriptions: descriptions.length - new Set(descriptions).size,
    descriptionsBetween110And170Characters: descriptions.filter(value => value.length >= 110 && value.length <= 170).length,
    descriptionMinCharacters: Math.min(...descriptions.map(value => value.length)),
    descriptionMaxCharacters: Math.max(...descriptions.map(value => value.length)),
  },
  records,
};
writeFileSync(`${out}/matter-answer-coverage.json`, `${JSON.stringify(result, null, 2)}\n`);
console.log(JSON.stringify(result.summary, null, 2));
