import type { MatterEditorial } from "./matter-editorial.js";

/** Exact intent assignments; preparation guidance does not establish a local filing rule. */
export const ADDITIONAL_MATTER_EDITORIAL: readonly MatterEditorial[] = [
  {
    id: "medical-record-access",
    titles: ["Medical-record access dispute", "Medical-record review"],
    factsEn: "which treatment records were requested, who holds them, the patient's authority or representative's consent and the provider's reason for withholding or supplying an incomplete copy",
    factsAr: "السجلات العلاجية المطلوبة والجهة الحائزة لها وصفة المريض أو موافقته على التمثيل وسبب حجب النسخة أو تقديمها ناقصة",
    evidenceEn: "the dated records request, proof of identity or authority, the provider's reply and an inventory of missing consultations, scans, test results or discharge records",
    evidenceAr: "طلب السجلات المؤرخ وإثبات الهوية أو الصفة ورد مقدم الرعاية وقائمة الاستشارات أو الصور أو نتائج الفحوص أو تقارير الخروج الناقصة",
    outcomeEn: "identify the missing material and the appropriate access or clarification request before assessing a separate treatment complaint",
    outcomeAr: "تحديد المواد الناقصة وطلب الاطلاع أو الاستيضاح المناسب قبل تقييم شكوى علاجية مستقلة",
    summaryEn: "Start by listing the medical records requested and comparing them with the provider's response. Missing records, disagreement with a diagnosis and a negligence complaint are different issues; the access request should identify exactly what is needed.",
    summaryAr: "ابدأ بحصر السجلات الطبية المطلوبة ومقارنتها برد مقدم الرعاية. نقص السجلات والخلاف حول التشخيص والشكوى عن الخطأ الطبي مسائل مختلفة؛ وينبغي أن يحدد طلب الاطلاع بدقة المواد المطلوبة.",
    questions: { en: ["Which dates, departments and records does the request cover?", "Are you the patient or an authorised representative?", "Was access refused, delayed or only partly provided?"], ar: ["ما التواريخ والأقسام والسجلات التي يشملها الطلب؟", "هل أنت المريض أم ممثل مأذون له؟", "هل رُفض الاطلاع أم تأخر أم قُدمت سجلات جزئية؟"] },
    faqs: {
      en: [{ q: "What if I received only a discharge summary?", a: "Compare the material received with your original request. Identify the missing dates and record types, such as imaging or test results, and keep the provider's explanation. Whether a particular record can be disclosed requires checking the applicable access rules and your authority." }, { q: "Does an incomplete file prove medical negligence?", a: "An incomplete file identifies an evidence gap; it does not by itself establish a treatment error or causation. Separate the request for records from the clinical concerns and preserve the chronology for appropriate medical and legal assessment." }],
      ar: [{ q: "ماذا لو استلمت ملخص الخروج فقط؟", a: "قارن ما استلمته بالطلب الأصلي، وحدد التواريخ وأنواع السجلات الناقصة مثل الصور أو نتائج الفحوص، واحتفظ بتفسير مقدم الرعاية. يتطلب تحديد جواز تسليم سجل معين التحقق من قواعد الاطلاع المنطبقة وصفتك." }, { q: "هل يثبت الملف الناقص وقوع خطأ طبي؟", a: "يكشف الملف الناقص عن فجوة في الأدلة، ولا يثبت بمفرده خطأً علاجياً أو علاقة سببية. افصل طلب السجلات عن الملاحظات السريرية واحفظ التسلسل الزمني للتقييم الطبي والقانوني المناسب." }],
    },
  },
  {
    id: "salary-arrears",
    titles: ["Delayed or unpaid salary", "Unpaid wages and benefits"],
    factsEn: "the agreed wage components, each unpaid pay period, deductions, amounts actually received and whether employment is continuing",
    factsAr: "عناصر الأجر المتفق عليها وكل فترة غير مدفوعة والاستقطاعات والمبالغ المستلمة فعلاً وما إذا كانت علاقة العمل مستمرة",
    evidenceEn: "the employment terms, payslips, relevant bank credits, attendance records and a period-by-period schedule of amounts due, received and disputed",
    evidenceAr: "شروط العمل وكشوف الرواتب والتحويلات المصرفية ذات الصلة وسجلات الحضور وجدول لكل فترة يوضح المستحق والمستلم والمتنازع عليه",
    outcomeEn: "reconcile the wage shortfall and distinguish a salary complaint from termination, resignation or a final settlement",
    outcomeAr: "مطابقة نقص الأجر والتمييز بين شكوى الراتب وإنهاء العمل أو الاستقالة أو التسوية النهائية",
    summaryEn: "An unpaid-salary assessment starts with a pay-period ledger showing what was due and what was received. Separate salary, allowances and deductions so the disputed balance is clear; resignation and final-settlement questions need their own assessment.",
    summaryAr: "يبدأ تقييم الأجر غير المدفوع بجدول لكل فترة يبين المستحق والمستلم. افصل الراتب والبدلات والاستقطاعات لتحديد الرصيد المتنازع عليه؛ وتحتاج مسائل الاستقالة والتسوية النهائية إلى تقييم مستقل.",
    questions: { en: ["Which pay periods and wage components remain unpaid?", "Do bank credits match the payslips?", "Has the employer disputed the amount or only postponed payment?"], ar: ["ما فترات الأجر وعناصره التي لم تُدفع؟", "هل تطابق التحويلات كشوف الرواتب؟", "هل نازع صاحب العمل في المبلغ أم أجّل الدفع فقط؟"] },
    faqs: {
      en: [{ q: "How should I show partial salary payments?", a: "Record each pay period separately, with the agreed amount, deductions, payment date and amount received. Keep supporting statements and avoid counting a later payment twice. This reconciliation helps identify the dispute; it is not an official filing-document checklist." }, { q: "Should I combine unpaid salary with my end-of-service calculation?", a: "Show them as separate items, even if raised together. Wage arrears concern earlier pay periods; a final settlement may include other disputed components. Identify the dates and basis of each amount before treating an employer's total as correct." }],
      ar: [{ q: "كيف أوضح دفعات الراتب الجزئية؟", a: "سجّل كل فترة على حدة مع الأجر المتفق عليه والاستقطاعات وتاريخ الدفع والمبلغ المستلم. احتفظ بالكشوف المؤيدة وتجنب احتساب دفعة لاحقة مرتين. تساعد المطابقة في تحديد الخلاف، وليست قائمة رسمية لمستندات القيد." }, { q: "هل أدمج الراتب المتأخر مع حساب نهاية الخدمة؟", a: "اعرضهما كبندين منفصلين ولو أُثيرا معاً. تتعلق متأخرات الأجر بفترات سابقة، وقد تشمل التسوية النهائية عناصر أخرى متنازعاً عليها. حدّد تواريخ كل مبلغ وأساسه قبل اعتبار إجمالي صاحب العمل صحيحاً." }],
    },
  },
  {
    id: "rental-deposit",
    titles: ["Security deposit recovery"],
    factsEn: "the deposit paid, end of the tenancy, handover condition, return of keys and each deduction claimed by the landlord",
    factsAr: "التأمين المدفوع وانتهاء الإيجار وحالة العقار عند التسليم وإعادة المفاتيح وكل حسم يدعيه المؤجر",
    evidenceEn: "the lease and deposit receipt, entry and exit inventories, dated condition photographs, key-handover acknowledgement and itemised deductions with supporting invoices",
    evidenceAr: "عقد الإيجار وإيصال التأمين ومحضري الاستلام والتسليم والصور المؤرخة للحالة وإقرار تسليم المفاتيح والحسميات المفصلة مع فواتيرها المؤيدة",
    outcomeEn: "compare the deposit balance with evidenced deductions and assess a focused refund request",
    outcomeAr: "مقارنة رصيد التأمين بالحسميات المثبتة وتقييم طلب استرداد محدد",
    summaryEn: "A rental-deposit dispute turns on the amount paid, the condition at handover and the reasons for deductions. Compare entry and exit records and ask for an itemised account; a repair allegation alone does not explain the amount withheld.",
    summaryAr: "تتمحور منازعة التأمين الإيجاري حول المبلغ المدفوع وحالة العقار عند التسليم وأسباب الحسم. قارن سجلات الاستلام والتسليم واطلب كشفاً مفصلاً؛ فمجرد الادعاء بإصلاحات لا يوضح قيمة المبلغ المحتجز.",
    questions: { en: ["Was the deposit paid to the landlord, agent or another party?", "What records show the property's condition at entry and exit?", "Which deductions are accepted and which lack an explanation?"], ar: ["هل دُفع التأمين للمؤجر أم الوسيط أم جهة أخرى؟", "ما السجلات التي تبين حالة العقار عند الاستلام والتسليم؟", "ما الحسميات المقبولة وما الحسميات غير المفسرة؟"] },
    faqs: {
      en: [{ q: "What if the landlord sends only a total repair charge?", a: "Request a breakdown identifying each item, its condition at handover and the supporting cost record. Compare it with the move-in inventory, photographs and lease. The assessment must distinguish a documented item from an unexplained lump sum." }, { q: "Can the deposit simply be treated as the last rent payment?", a: "Do not assume the two balances can be offset unilaterally. Record rent and deposit separately and check the agreement and applicable rules before acting. A deposit refund dispute and an unpaid-rent allegation may otherwise arise together." }],
      ar: [{ q: "ماذا لو أرسل المؤجر إجمالي الإصلاحات فقط؟", a: "اطلب تفصيلاً يحدد كل بند وحالته عند التسليم ومستند تكلفته. قارنه بمحضر الاستلام والصور والعقد. يجب أن يميز التقييم بين بند موثق ومبلغ إجمالي غير مفسر." }, { q: "هل يمكن اعتبار التأمين دفعة الإيجار الأخيرة؟", a: "لا تفترض جواز المقاصة بين الرصيدين بإرادة منفردة. سجّل الأجرة والتأمين منفصلين وتحقق من الاتفاق والقواعد المنطبقة قبل التصرف، فقد يجتمع خلاف استرداد التأمين مع ادعاء بعدم سداد الأجرة." }],
    },
  },
  {
    id: "business-invoice",
    titles: ["Unpaid business invoices", "Unpaid business invoice", "Unpaid invoices and payment claims", "Unpaid professional fees and service invoice dispute"],
    factsEn: "the contracting customer, agreed fee or price, work or goods supplied, acceptance, due date and the customer's stated reason for withholding payment",
    factsAr: "العميل المتعاقد والأتعاب أو الثمن المتفق عليه والعمل أو البضاعة المقدمة والقبول والاستحقاق والسبب الذي ذكره العميل لحجب الدفع",
    evidenceEn: "the engagement or purchase order, agreed terms, invoice ledger, delivery or work-acceptance records, credit notes, part payments and the customer's replies",
    evidenceAr: "اتفاق التكليف أو أمر الشراء والشروط المتفق عليها وسجل الفواتير وإثبات التسليم أو قبول العمل والإشعارات الدائنة والدفعات الجزئية وردود العميل",
    outcomeEn: "reconcile the recoverable amount claimed and distinguish a payment delay from a dispute over performance, authority or price",
    outcomeAr: "مطابقة المبلغ المطالب بتحصيله والتمييز بين تأخر الدفع والخلاف على التنفيذ أو الصلاحية أو الثمن",
    summaryEn: "An unpaid invoice needs a clear connection to the agreed work or delivery and the correct customer. Reconcile credits and part payments, then identify whether the customer disputes performance, price or only the timing of payment.",
    summaryAr: "تحتاج الفاتورة غير المدفوعة إلى صلة واضحة بالعمل أو التسليم المتفق عليه والعميل الصحيح. طابق الإشعارات الدائنة والدفعات الجزئية، ثم حدد ما إذا كان العميل ينازع في التنفيذ أو الثمن أو توقيت الدفع فقط.",
    questions: { en: ["Which person or entity agreed to pay?", "Was the work or delivery accepted, rejected or left unanswered?", "What remains after credits, deductions and part payments?"], ar: ["من الشخص أو المنشأة التي اتفقت على الدفع؟", "هل قُبل العمل أو التسليم أم رُفض أم بقي دون رد؟", "ما الرصيد بعد الإشعارات الدائنة والحسميات والدفعات الجزئية؟"] },
    faqs: {
      en: [{ q: "Is the invoice alone enough to explain the claim?", a: "An invoice records a demand for payment but may not explain the underlying agreement or performance. Preserve the order, agreed scope, delivery or acceptance evidence and replies. A disputed price or incomplete delivery needs its own analysis." }, { q: "What if the customer acknowledges only part of the invoice?", a: "Record the accepted and disputed amounts separately, including the reason given. Preserve any payment allocation and settlement proposal. Do not label a partial payment as a full settlement unless that is what the relevant agreement establishes." }],
      ar: [{ q: "هل تكفي الفاتورة وحدها لشرح المطالبة؟", a: "تسجّل الفاتورة طلب الدفع، لكنها قد لا تشرح الاتفاق الأصلي أو تنفيذه. احفظ الطلب والنطاق المتفق عليه وإثبات التسليم أو القبول والردود. يحتاج الثمن المتنازع عليه أو التسليم الناقص إلى تحليل مستقل." }, { q: "ماذا لو أقر العميل بجزء من الفاتورة فقط؟", a: "سجّل المبلغ المقبول والمبلغ المتنازع عليه منفصلين مع السبب المذكور. احفظ تخصيص أي دفعة ومقترح التسوية. لا تصف الدفعة الجزئية بأنها تسوية نهائية إلا إذا كان الاتفاق المعني يقرر ذلك." }],
    },
  },
  {
    id: "data-rights-request",
    titles: ["Personal-data access, correction or deletion request"],
    factsEn: "the organisation holding the data, the information or correction requested, identity verification, previous responses and the stated reason for retention or refusal",
    factsAr: "المنظمة الحائزة للبيانات والمعلومات أو التصحيح المطلوب والتحقق من الهوية والردود السابقة والسبب المذكور للاحتفاظ أو الرفض",
    evidenceEn: "the original request and delivery record, the relevant privacy notice, the organisation's reply and a redacted example of the disputed data",
    evidenceAr: "الطلب الأصلي وإثبات إرساله وإشعار الخصوصية ذي الصلة ورد المنظمة ومثال على البيانات محل الخلاف بعد حجب غير اللازم",
    outcomeEn: "clarify the request and assess the applicable right, exceptions and escalation route without assuming every record must be erased",
    outcomeAr: "توضيح الطلب وتقييم الحق المنطبق واستثناءاته وطريق التصعيد دون افتراض وجوب محو كل سجل",
    summaryEn: "Access, correction and deletion are different requests. Identify the organisation, the data concerned and the response sought. The applicable privacy framework and any retention duty must be checked before assuming a refusal is unlawful.",
    summaryAr: "الاطلاع والتصحيح والحذف طلبات مختلفة. حدّد المنظمة والبيانات المعنية والرد المطلوب. يلزم التحقق من إطار الخصوصية المنطبق وأي واجب للاحتفاظ قبل افتراض أن الرفض غير مشروع.",
    questions: { en: ["Do you want a copy, a correction or deletion of a specific record?", "Which organisation received the request and when?", "Has it explained an identity check, retention duty or refusal?"], ar: ["هل تريد نسخة أم تصحيحاً أم حذف سجل محدد؟", "ما المنظمة التي استلمت الطلب ومتى؟", "هل فسرت التحقق من الهوية أو واجب الاحتفاظ أو الرفض؟"] },
    faqs: {
      en: [{ q: "Does deleting an online account necessarily delete every record?", a: "Account closure and a personal-data deletion request may have different scopes. Identify the records still held and ask for the reason and applicable retention basis. Do not assume that closing access proves all underlying data has been erased." }, { q: "What should a correction request identify?", a: "Specify the inaccurate entry, the proposed correction and the minimum supporting evidence. Keep a copy of the request and response. Avoid sending unrelated personal records, and use an agreed secure channel when identity evidence is needed." }],
      ar: [{ q: "هل يؤدي حذف الحساب الإلكتروني بالضرورة إلى محو كل سجل؟", a: "قد يختلف نطاق إغلاق الحساب عن طلب حذف البيانات الشخصية. حدّد السجلات التي بقيت واطلب سبب الاحتفاظ وأساسه المنطبق. لا تفترض أن إغلاق الوصول يثبت محو جميع البيانات الأساسية." }, { q: "ماذا ينبغي أن يحدد طلب التصحيح؟", a: "حدّد القيد غير الدقيق والتصحيح المقترح والحد الأدنى من الإثبات المؤيد. احتفظ بالطلب والرد، وتجنب إرسال سجلات شخصية غير مرتبطة، واستخدم قناة آمنة متفقاً عليها عند الحاجة لإثبات الهوية." }],
    },
  },
];
