export interface SubServiceLink {
  id: string;
  titleEn: string;
  titleAr: string;
}

export const SUB_SERVICE_MAP: Record<string, SubServiceLink[]> = {
  "family-law": [
    { id: "divorce",             titleEn: "Divorce",                       titleAr: "الطلاق" },
    { id: "khul",                titleEn: "Khul' (Wife-Initiated Divorce)", titleAr: "الخلع" },
    { id: "alimony",             titleEn: "Alimony & Nafaqa",              titleAr: "النفقة" },
    { id: "child-custody",       titleEn: "Child Custody",                 titleAr: "حضانة الأطفال" },
    { id: "inheritance-disputes",titleEn: "Inheritance Disputes",          titleAr: "نزاعات الميراث" },
    { id: "marriage-contracts",  titleEn: "Marriage Contracts",            titleAr: "عقود الزواج" },
  ],
  "business-law": [
    { id: "commercial-contracts",               titleEn: "Commercial Contracts",                  titleAr: "العقود التجارية" },
    { id: "commercial-instruments",             titleEn: "Commercial Instruments",                titleAr: "الأوراق التجارية" },
    { id: "commercial-agency",                  titleEn: "Commercial Agency",                     titleAr: "الوكالة التجارية" },
    { id: "bankruptcy-liquidation",             titleEn: "Bankruptcy & Liquidation",              titleAr: "الإفلاس والتصفية" },
    { id: "company-partnership-disputes",       titleEn: "Company & Partnership Disputes",        titleAr: "نزاعات الشركات والشراكات" },
    { id: "unfair-competition-commercial-fraud",titleEn: "Unfair Competition & Commercial Fraud", titleAr: "المنافسة غير المشروعة والغش التجاري" },
    { id: "trademarks",                         titleEn: "Trademarks",                            titleAr: "العلامات التجارية" },
  ],
  "real-estate": [
    { id: "ownership-disputes",      titleEn: "Ownership Disputes",          titleAr: "نزاعات الملكية" },
    { id: "sale-purchase-disputes",  titleEn: "Sale & Purchase Disputes",    titleAr: "نزاعات البيع والشراء" },
    { id: "property-encroachment",   titleEn: "Property Encroachment",       titleAr: "التعدي على العقارات" },
    { id: "lease-rental-disputes",   titleEn: "Lease & Rental Disputes",     titleAr: "نزاعات الإيجار" },
    { id: "real-estate-registration",titleEn: "Real Estate Registration",    titleAr: "تسجيل العقارات" },
    { id: "construction-disputes",   titleEn: "Construction Disputes",       titleAr: "نزاعات البناء والمقاولات" },
  ],
  "employment-law": [
    { id: "unpaid-wages",          titleEn: "Unpaid Wages",               titleAr: "الأجور غير المدفوعة" },
    { id: "labor-compensation",    titleEn: "Work Injury Compensation",   titleAr: "تعويض إصابات العمل" },
    { id: "unfair-dismissal",      titleEn: "Unfair Dismissal",           titleAr: "الفصل التعسفي" },
    { id: "end-of-service",        titleEn: "End of Service Benefits",    titleAr: "مكافأة نهاية الخدمة" },
    { id: "contract-disputes",     titleEn: "Employment Contract Disputes",titleAr: "نزاعات عقد العمل" },
    { id: "workplace-discrimination",titleEn: "Workplace Discrimination", titleAr: "التمييز في مكان العمل" },
  ],
  "foreign-investment": [
    { id: "investment-disputes",      titleEn: "Investment Disputes",        titleAr: "نزاعات الاستثمار" },
    { id: "investment-appeals",       titleEn: "Investment Appeals",         titleAr: "استئناف قرارات الاستثمار" },
    { id: "investment-licensing",     titleEn: "Investment Licensing",       titleAr: "ترخيص الاستثمار" },
    { id: "license-renewal",          titleEn: "License Renewal",            titleAr: "تجديد الترخيص" },
    { id: "license-cancellation",     titleEn: "License Cancellation",       titleAr: "إلغاء الترخيص" },
    { id: "company-formation",        titleEn: "Company Formation",          titleAr: "تأسيس الشركات" },
    { id: "foreign-investment-dispute",titleEn: "Foreign Investment Dispute",titleAr: "نزاع الاستثمار الأجنبي" },
    { id: "investor-compensation",    titleEn: "Investor Compensation",      titleAr: "تعويض المستثمر" },
    { id: "share-transfer",           titleEn: "Share Transfer",             titleAr: "نقل الأسهم" },
  ],
  "administrative-law": [
    { id: "board-of-grievances",    titleEn: "Board of Grievances / State Council", titleAr: "ديوان المظالم / مجلس الدولة" },
    { id: "administrative-appeals", titleEn: "Administrative Appeals",              titleAr: "الاستئناف الإداري" },
    { id: "government-contracts",   titleEn: "Government Contracts",               titleAr: "العقود الحكومية" },
    { id: "public-procurement",     titleEn: "Public Procurement",                 titleAr: "المناقصات الحكومية" },
    { id: "regulatory-licensing",   titleEn: "Regulatory Licensing",               titleAr: "التراخيص التنظيمية" },
    { id: "customs-tax-disputes",   titleEn: "Customs & Tax Disputes",             titleAr: "النزاعات الجمركية والضريبية" },
    { id: "disciplinary-proceedings",titleEn: "Disciplinary Proceedings",          titleAr: "التحقيقات التأديبية" },
    { id: "government-compensation",titleEn: "Government Compensation",            titleAr: "التعويضات الحكومية" },
  ],
  "arbitration": [
    { id: "commercial-arbitration",  titleEn: "Commercial Arbitration",    titleAr: "التحكيم التجاري" },
    { id: "mediation-adr",           titleEn: "Mediation & ADR",           titleAr: "الوساطة وحل النزاعات" },
    { id: "award-enforcement",       titleEn: "Award Enforcement",         titleAr: "تنفيذ أحكام التحكيم" },
    { id: "international-arbitration",titleEn: "International Arbitration",titleAr: "التحكيم الدولي" },
    { id: "investment-arbitration",  titleEn: "Investment Arbitration",    titleAr: "تحكيم الاستثمار" },
  ],
  "enforcement": [
    { id: "judgment-enforcement",          titleEn: "Court Judgment Enforcement",    titleAr: "تنفيذ الأحكام القضائية" },
    { id: "debt-recovery",                 titleEn: "Debt Recovery",                 titleAr: "استرداد الديون" },
    { id: "asset-attachment",              titleEn: "Asset Attachment",              titleAr: "الحجز على الأصول" },
    { id: "travel-bans",                   titleEn: "Travel Bans",                   titleAr: "منع السفر" },
    { id: "enforcement-against-government",titleEn: "Enforcement Against Government",titleAr: "التنفيذ ضد الحكومة" },
  ],
  "companies-law": [
    { id: "company-formation-disputes",     titleEn: "Company Formation Disputes",      titleAr: "نزاعات تأسيس الشركات" },
    { id: "share-equity-disputes",          titleEn: "Share & Equity Disputes",         titleAr: "نزاعات الأسهم والحصص" },
    { id: "partner-shareholder-disputes",   titleEn: "Partner & Shareholder Disputes",  titleAr: "نزاعات الشركاء والمساهمين" },
    { id: "director-liability",             titleEn: "Director Liability",              titleAr: "مسؤولية المديرين" },
    { id: "general-assembly-disputes",      titleEn: "General Assembly Disputes",       titleAr: "نزاعات الجمعية العمومية" },
    { id: "assembly-resolution-nullity",    titleEn: "Assembly Resolution Nullity",     titleAr: "بطلان قرارات الجمعية" },
    { id: "capital-change-disputes",        titleEn: "Capital Change Disputes",         titleAr: "نزاعات تغيير رأس المال" },
    { id: "profit-distribution-disputes",   titleEn: "Profit Distribution Disputes",    titleAr: "نزاعات توزيع الأرباح" },
    { id: "conflict-of-interest",           titleEn: "Conflict of Interest",            titleAr: "تضارب المصالح" },
    { id: "director-removal-disputes",      titleEn: "Director Removal Disputes",       titleAr: "نزاعات عزل المديرين" },
    { id: "company-records-access",         titleEn: "Company Records Access",          titleAr: "الوصول لسجلات الشركة" },
    { id: "share-transfer-disputes",        titleEn: "Share Transfer Disputes",         titleAr: "نزاعات نقل الأسهم" },
    { id: "partner-entry-exit",             titleEn: "Partner Entry & Exit",            titleAr: "دخول وخروج الشركاء" },
    { id: "merger-conversion-disputes",     titleEn: "Merger & Conversion Disputes",    titleAr: "نزاعات الاندماج والتحويل" },
    { id: "company-dissolution-liquidation",titleEn: "Company Dissolution & Liquidation",titleAr: "حل الشركات وتصفيتها" },
    { id: "liquidator-liability",           titleEn: "Liquidator Liability",            titleAr: "مسؤولية المصفّي" },
    { id: "shareholder-compensation-claims",titleEn: "Shareholder Compensation Claims", titleAr: "مطالبات تعويض المساهمين" },
    { id: "family-company-disputes",        titleEn: "Family Company Disputes",         titleAr: "نزاعات الشركات العائلية" },
    { id: "shareholder-agreements-disputes",titleEn: "Shareholder Agreement Disputes",  titleAr: "نزاعات اتفاقيات المساهمين" },
    { id: "articles-of-association-disputes",titleEn: "Articles of Association Disputes",titleAr: "نزاعات النظام الأساسي" },
  ],
  "contracts": [
    { id: "contract-drafting",      titleEn: "Contract Drafting",           titleAr: "صياغة العقود" },
    { id: "contract-disputes",      titleEn: "Contract Disputes",           titleAr: "نزاعات العقود" },
    { id: "government-contracts",   titleEn: "Government Contracts",        titleAr: "العقود الحكومية" },
    { id: "real-estate-contracts",  titleEn: "Real Estate Contracts",       titleAr: "عقود العقارات" },
    { id: "employment-contracts",   titleEn: "Employment Contracts",        titleAr: "عقود العمل" },
    { id: "partnership-agreements", titleEn: "Partnership Agreements",      titleAr: "اتفاقيات الشراكة" },
    { id: "international-contracts",titleEn: "International Contracts",     titleAr: "العقود الدولية" },
    { id: "contract-enforcement",   titleEn: "Contract Enforcement",        titleAr: "تنفيذ العقود" },
  ],
  "criminal-law": [
    { id: "criminal-defense",       titleEn: "Criminal Defense",          titleAr: "الدفاع الجنائي" },
    { id: "bail-release",           titleEn: "Bail & Pre-trial Release",  titleAr: "الكفالة والإفراج" },
    { id: "criminal-appeals",       titleEn: "Criminal Appeals",          titleAr: "الاستئناف الجنائي" },
    { id: "cybercrime-cases",       titleEn: "Cybercrime Cases",          titleAr: "جرائم الفضاء الإلكتروني" },
    { id: "financial-crimes",       titleEn: "Financial Crimes",          titleAr: "الجرائم المالية" },
    { id: "drug-offenses",          titleEn: "Drug Offenses",             titleAr: "جرائم المخدرات" },
    { id: "criminal-investigations",titleEn: "Criminal Investigations",   titleAr: "التحقيقات الجنائية" },
    { id: "public-order",           titleEn: "Public Order Offenses",     titleAr: "جرائم النظام العام" },
  ],
  "banking-finance": [
    { id: "islamic-finance",    titleEn: "Islamic Finance",         titleAr: "التمويل الإسلامي" },
    { id: "banking-disputes",   titleEn: "Banking Disputes",         titleAr: "النزاعات المصرفية" },
    { id: "loan-agreements",    titleEn: "Loan Agreements",          titleAr: "اتفاقيات القروض" },
    { id: "financial-regulatory",titleEn: "Financial Regulatory",   titleAr: "الرقابة المالية" },
    { id: "sukuk-bonds",        titleEn: "Sukuk & Bonds",            titleAr: "الصكوك والسندات" },
    { id: "banking-fraud",      titleEn: "Banking Fraud",            titleAr: "الاحتيال المصرفي" },
    { id: "credit-facilities",  titleEn: "Credit Facilities",        titleAr: "التسهيلات الائتمانية" },
  ],
  "intellectual-property": [
    { id: "trademark-registration",titleEn: "Trademark Registration",  titleAr: "تسجيل العلامات التجارية" },
    { id: "patent-protection",     titleEn: "Patent Protection",       titleAr: "حماية براءات الاختراع" },
    { id: "copyright-disputes",    titleEn: "Copyright Disputes",      titleAr: "نزاعات حق المؤلف" },
    { id: "trade-secrets",         titleEn: "Trade Secrets",           titleAr: "الأسرار التجارية" },
    { id: "ip-licensing",          titleEn: "IP Licensing",            titleAr: "ترخيص الملكية الفكرية" },
    { id: "brand-protection",      titleEn: "Brand Protection",        titleAr: "حماية العلامة التجارية" },
    { id: "ip-disputes",           titleEn: "IP Disputes",             titleAr: "نزاعات الملكية الفكرية" },
    { id: "ip-due-diligence",      titleEn: "IP Due Diligence",        titleAr: "العناية الواجبة للملكية الفكرية" },
  ],
  "tax-zakat": [
    { id: "vat-compliance",  titleEn: "VAT Compliance",          titleAr: "الامتثال لضريبة القيمة المضافة" },
    { id: "zakat-disputes",  titleEn: "Zakat Disputes",           titleAr: "نزاعات الزكاة" },
    { id: "zatca-appeals",   titleEn: "Tax Authority Appeals",    titleAr: "استئناف هيئة الضرائب" },
    { id: "corporate-tax",   titleEn: "Corporate Tax",            titleAr: "ضريبة الشركات" },
    { id: "transfer-pricing",titleEn: "Transfer Pricing",         titleAr: "أسعار التحويل" },
    { id: "customs-disputes",titleEn: "Customs Disputes",         titleAr: "النزاعات الجمركية" },
    { id: "tax-advisory",    titleEn: "Tax Advisory",             titleAr: "الاستشارات الضريبية" },
    { id: "excise-tax",      titleEn: "Excise Tax",               titleAr: "ضريبة الانتقائية" },
  ],
  "cyber-law": [
    { id: "cybercrime-defense", titleEn: "Cybercrime Defense",    titleAr: "الدفاع عن جرائم الإنترنت" },
    { id: "data-protection",    titleEn: "Data Protection",       titleAr: "حماية البيانات" },
    { id: "online-fraud",       titleEn: "Online Fraud",          titleAr: "الاحتيال الإلكتروني" },
    { id: "hacking-defense",    titleEn: "Hacking Defense",       titleAr: "الدفاع عن القرصنة" },
    { id: "online-defamation",  titleEn: "Online Defamation",     titleAr: "التشهير الإلكتروني" },
    { id: "ecommerce-disputes", titleEn: "E-Commerce Disputes",   titleAr: "نزاعات التجارة الإلكترونية" },
    { id: "digital-privacy",    titleEn: "Digital Privacy",       titleAr: "الخصوصية الرقمية" },
    { id: "it-contracts",       titleEn: "IT Contracts",          titleAr: "عقود تكنولوجيا المعلومات" },
  ],
  "medical-malpractice": [
    { id: "medical-negligence",  titleEn: "Medical Negligence",   titleAr: "الإهمال الطبي" },
    { id: "surgical-errors",     titleEn: "Surgical Errors",      titleAr: "أخطاء جراحية" },
    { id: "misdiagnosis",        titleEn: "Misdiagnosis",         titleAr: "الخطأ في التشخيص" },
    { id: "hospital-liability",  titleEn: "Hospital Liability",   titleAr: "مسؤولية المستشفى" },
    { id: "pharmaceutical-claims",titleEn: "Pharmaceutical Claims",titleAr: "مطالبات الأدوية" },
    { id: "dental-malpractice",  titleEn: "Dental Malpractice",   titleAr: "الأخطاء الطبية السنية" },
    { id: "healthcare-regulatory",titleEn: "Healthcare Regulatory",titleAr: "التنظيم الصحي" },
    { id: "patient-rights",      titleEn: "Patient Rights",       titleAr: "حقوق المريض" },
  ],
  "insurance-law": [
    { id: "insurance-disputes",   titleEn: "Insurance Disputes",    titleAr: "نزاعات التأمين" },
    { id: "health-insurance",     titleEn: "Health Insurance",      titleAr: "التأمين الصحي" },
    { id: "property-insurance",   titleEn: "Property Insurance",    titleAr: "تأمين الممتلكات" },
    { id: "motor-insurance",      titleEn: "Motor Insurance",       titleAr: "تأمين السيارات" },
    { id: "life-insurance",       titleEn: "Life Insurance",        titleAr: "التأمين على الحياة" },
    { id: "commercial-insurance", titleEn: "Commercial Insurance",  titleAr: "التأمين التجاري" },
    { id: "insurance-bad-faith",  titleEn: "Insurance Bad Faith",   titleAr: "التأمين بسوء نية" },
    { id: "insurance-regulatory", titleEn: "Insurance Regulatory",  titleAr: "التنظيم التأميني" },
  ],
  "immigration-law": [
    { id: "iqama-residency",      titleEn: "Iqama & Residency",       titleAr: "الإقامة" },
    { id: "work-visas",           titleEn: "Work Visas",              titleAr: "تأشيرات العمل" },
    { id: "kafala-transfer",      titleEn: "Kafala Sponsorship Transfer",titleAr: "نقل الكفالة" },
    { id: "deportation-defense",  titleEn: "Deportation Defense",     titleAr: "الدفاع ضد الترحيل" },
    { id: "family-visas",         titleEn: "Family Visas",            titleAr: "تأشيرات العائلة" },
    { id: "premium-residency",    titleEn: "Premium Residency",       titleAr: "الإقامة المميزة" },
    { id: "business-visas",       titleEn: "Business Visas",          titleAr: "تأشيرات العمل التجاري" },
    { id: "immigration-violations",titleEn: "Immigration Violations", titleAr: "مخالفات الإقامة" },
  ],
  "civil-law": [
    { id: "civil-liability",   titleEn: "Civil Liability & Damages",      titleAr: "المسؤولية المدنية والتعويضات" },
    { id: "real-rights",       titleEn: "Real Rights & Ownership",        titleAr: "الحقوق العينية والملكية" },
    { id: "civil-obligations", titleEn: "Civil Obligations & Contracts",  titleAr: "الالتزامات المدنية والعقود" },
    { id: "inheritance-wills", titleEn: "Inheritance & Wills",            titleAr: "الميراث والوصايا" },
    { id: "neighbor-disputes", titleEn: "Neighbor Disputes & Easements",  titleAr: "نزاعات الجيران والارتفاق" },
    { id: "legal-capacity",    titleEn: "Legal Capacity & Civil Status",  titleAr: "الأهلية القانونية والحالة المدنية" },
  ],
  "civil-procedure": [
    { id: "filing-civil-claim",titleEn: "Filing a Civil Claim",          titleAr: "رفع دعوى مدنية" },
    { id: "interim-measures",  titleEn: "Interim & Provisional Measures",titleAr: "التدابير المؤقتة والاحترازية" },
    { id: "evidence-proof",    titleEn: "Evidence & Proof",              titleAr: "الإثبات والأدلة" },
    { id: "civil-appeals",     titleEn: "Civil Appeals",                 titleAr: "الاستئناف المدني" },
    { id: "civil-cassation",   titleEn: "Civil Cassation",               titleAr: "النقض المدني" },
    { id: "foreign-judgment",  titleEn: "Foreign Judgment Enforcement",  titleAr: "تنفيذ الأحكام الأجنبية" },
  ],
  "criminal-procedure": [
    { id: "preliminary-investigation",titleEn: "Preliminary Investigation",         titleAr: "التحقيق الابتدائي" },
    { id: "detention-bail",           titleEn: "Detention & Bail",                 titleAr: "الاحتجاز والكفالة" },
    { id: "criminal-trial",           titleEn: "Criminal Trial & Defense",         titleAr: "المحاكمة الجنائية والدفاع" },
    { id: "criminal-appeal",          titleEn: "Criminal Appeal",                  titleAr: "الاستئناف الجنائي" },
    { id: "criminal-cassation",       titleEn: "Criminal Cassation",               titleAr: "النقض الجنائي" },
    { id: "civil-in-criminal",        titleEn: "Civil Action in Criminal Proceedings",titleAr: "الدعوى المدنية في القضايا الجنائية" },
  ],
};

export const PARENT_SERVICE_IDS = new Set(Object.keys(SUB_SERVICE_MAP));
