import { brief } from "./types.js";
export const ARBITRATION_ENFORCEMENT_BRIEFS = [
  brief(["Commercial arbitration"],
    "What must be established before starting commercial arbitration?", "ما الذي يجب تحديده قبل بدء التحكيم التجاري؟",
    "Identify the arbitration agreement, parties, covered dispute, seat and rules. Check any prior negotiation or notice step and the relief sought. Starting arbitration, defending a claim and enforcing an award are different stages with different documents and decisions.",
    "حدّد اتفاق التحكيم والأطراف والنزاع المشمول والمقر والقواعد. افحص أي تفاوض أو إخطار سابق والطلبات المقصودة. بدء التحكيم والدفاع في مطالبة وتنفيذ الحكم مراحل مختلفة في مستنداتها وقراراتها.",
    "contract and arbitration clause, incorporated rules, dispute notices, claim chronology and available procedural correspondence",
    "العقد وشرط التحكيم والقواعد المحال إليها وإخطارات النزاع وتسلسله والمراسلات الإجرائية المتاحة"),
  brief(["Arbitration clause review"],
    "Does the arbitration clause provide a workable procedure?", "هل يوفر شرط التحكيم إجراءً قابلاً للتطبيق؟",
    "Review the seat, institution or ad hoc rules, language, appointment method and disputes covered. Check consistency across connected contracts and any court-jurisdiction clause. Ambiguous or conflicting provisions should be addressed before a dispute forces the parties to argue about the procedure itself.",
    "راجع المقر والمؤسسة أو القواعد الخاصة واللغة وآلية التعيين والنزاعات المشمولة. افحص الاتساق بين العقود المرتبطة وشرط اختصاص المحاكم. عالج الغموض والتعارض قبل أن يضطر الأطراف إلى التنازع على الإجراء نفسه.",
    "complete draft contract, dispute clauses in related agreements, proposed rules and signing-authority information",
    "مسودة العقد كاملة وشروط النزاع في الاتفاقات المرتبطة والقواعد المقترحة وبيانات صلاحية التوقيع"),
  brief(["Urgent protective measures"],
    "What needs protection before the underlying dispute is decided?", "ما الذي يحتاج إلى حماية قبل الفصل في أصل النزاع؟",
    "Identify the threatened asset, evidence or position and explain why ordinary timing may be inadequate. Record the imminent act and evidence of urgency. Check which court or tribunal can consider the request; an urgent application should be tied to a specific risk and proposed measure.",
    "حدّد الأصل أو الدليل أو المركز المهدد وسبب عدم كفاية التوقيت المعتاد. وثّق التصرف الوشيك ودليل الاستعجال. تحقّق من المحكمة أو الهيئة التي تنظر الطلب؛ واربطه بخطر محدد وتدبير مقترح.",
    "underlying agreement, evidence of the imminent risk, asset or evidence identifiers and existing court or arbitration papers",
    "الاتفاق الأصلي وأدلة الخطر الوشيك ومعرّفات الأصل أو الدليل وأوراق المحكمة أو التحكيم القائمة"),
  brief(["Recognition and enforcement of awards"],
    "What remains to be checked after an arbitral award is issued?", "ما الذي يبقى للتحقق منه بعد صدور الحكم التحكيمي؟",
    "Identify the award, seat, parties, relief ordered and intended enforcement location. Record service, corrections, challenges and any compliance. Obtaining an award and recovering against identified assets are separate steps; the enforcement framework must match the award and destination.",
    "حدّد الحكم والمقر والأطراف وما قُضي به ومكان التنفيذ المقصود. وثّق التبليغ والتصحيح والطعون وما نُفذ. الحصول على الحكم والتحصيل من أصول محددة خطوتان منفصلتان؛ ويلزم مطابقة إطار التنفيذ بالحكم والوجهة.",
    "award and arbitration agreement, service records, correction or challenge papers, payment history and asset-location information",
    "الحكم واتفاق التحكيم وسجلات التبليغ وأوراق التصحيح أو الطعن وسجل الدفع وبيانات مواقع الأصول"),
  brief(["Mediation and negotiated settlement"],
    "What should be prepared before a mediation session?", "ما الذي يُجهز قبل جلسة الوساطة؟",
    "Define the issues, interests, evidence and settlement authority for each participant. Consider payment, performance and non-financial terms together. Check the mediation terms on confidentiality and use of material, and ensure any final agreement states who must do what and when.",
    "حدّد المسائل والمصالح والأدلة وصلاحية كل مشارك في التسوية. ابحث الدفع والتنفيذ والشروط غير المالية معاً. راجع شروط الوساطة بشأن السرية واستعمال المواد، واجعل الاتفاق النهائي واضحاً في المسؤول عن كل إجراء وموعده.",
    "mediation agreement, issue summary, key evidence, settlement authority and proposed payment or performance terms",
    "اتفاق الوساطة وملخص المسائل والأدلة الأساسية وصلاحية التسوية وشروط الدفع أو التنفيذ المقترحة"),
  brief(["Foreign arbitral award enforcement"],
    "What connects the foreign award to the intended enforcement country?", "ما صلة الحكم التحكيمي الأجنبي بدولة التنفيذ المقصودة؟",
    "Identify the debtor and assets in the destination, the award's seat and status, and the arbitration agreement. Record any set-aside or suspension proceeding. Recognition requirements and available objections must be checked in the destination; the foreign award is not a local execution order by itself.",
    "حدّد المدين وأصوله في الوجهة ومقر الحكم وحالته واتفاق التحكيم. وثّق أي دعوى بطلان أو إجراء وقف. تُفحص شروط الاعتراف والدفوع المتاحة في دولة التنفيذ؛ فالحكم الأجنبي ليس بذاته أمراً تنفيذياً محلياً.",
    "certified award and agreement, translations, service and status records, challenge papers and debtor asset information",
    "الحكم والاتفاق بصور معتمدة والترجمات وسجلات التبليغ والحالة وأوراق الطعن وبيانات أصول المدين"),
  brief(["Emergency arbitration and interim measures", "Urgent relief in arbitration: agreed rules and court measures"],
    "Do the agreed rules provide an emergency-arbitrator procedure?", "هل تتضمن القواعد المتفق عليها إجراء محكم طوارئ؟",
    "Check the arbitration agreement, applicable rules and whether the tribunal is already constituted. Explain the urgent harm, requested measure and evidence supporting it. Emergency arbitration and court interim relief may involve different authority and effect; do not assume one is available because the other is.",
    "راجع اتفاق التحكيم والقواعد وما إذا كانت الهيئة قد تشكلت. بيّن الضرر العاجل والتدبير المطلوب ودليله. قد تختلف صلاحية تحكيم الطوارئ وأثره عن القضاء المستعجل؛ فلا تفترض توافر أحدهما لتوافر الآخر.",
    "arbitration clause and rules, tribunal-status record, urgency evidence and the proposed interim measure",
    "شرط التحكيم وقواعده وسجل تشكيل الهيئة وأدلة الاستعجال والتدبير المؤقت المقترح"),
  brief(["Challenge to arbitration jurisdiction"],
    "What is the specific objection to the tribunal's authority?", "ما الاعتراض المحدد على اختصاص هيئة التحكيم؟",
    "Identify whether the objection concerns consent, a party's authority, the scope of the clause or the dispute submitted. Record when the objection was raised and subsequent participation. A jurisdiction objection should address the actual agreement and procedural stage, not merely disagreement with arbitration.",
    "حدّد هل الاعتراض على الرضا أو صلاحية الطرف أو نطاق الشرط أو النزاع المحال. وثّق وقت إثارته والمشاركة اللاحقة. ينبغي أن يتناول الاعتراض الاتفاق والمرحلة الفعليين، لا مجرد عدم الرغبة في التحكيم.",
    "arbitration agreement, authority documents, claim and response, procedural orders and jurisdiction-objection correspondence",
    "اتفاق التحكيم ومستندات الصلاحية والمطالبة والرد والأوامر الإجرائية ومراسلات الدفع بعدم الاختصاص"),
  brief(["Challenge to a Syrian arbitration agreement or award"],
    "Is the challenge directed at the agreement or an issued award?", "هل يتوجه الطعن إلى اتفاق التحكيم أم إلى حكم صادر؟",
    "Separate an objection to consent or clause scope from a challenge to an award after proceedings. Identify the seat, applicable framework, service date and precise grounds. A disagreement with the result should not be assumed to permit a full rehearing of the merits.",
    "افصل الاعتراض على الرضا أو نطاق الشرط عن الطعن في حكم بعد الإجراءات. حدّد المقر والإطار المنطبق وتاريخ التبليغ والأسباب الدقيقة. لا يُفترض أن عدم الرضا بالنتيجة يجيز إعادة نظر الموضوع كاملاً.",
    "arbitration agreement, award if issued, procedural record, service evidence and the specific challenge grounds",
    "اتفاق التحكيم والحكم إن صدر والسجل الإجرائي وإثبات التبليغ وأسباب الطعن المحددة"),
  brief(["Appointment or removal of an arbitrator dispute"],
    "What appointment rule or impartiality concern is disputed?", "ما قاعدة التعيين أو مسألة الحياد المتنازع عليها؟",
    "Check the agreed appointment mechanism and the stage reached. For a challenge, identify the disclosed relationship or conduct, when it became known and supporting evidence. Dissatisfaction with a procedural ruling should be distinguished from a substantiated concern about the arbitrator's position.",
    "راجع آلية التعيين المتفق عليها والمرحلة الحالية. وعند طلب الرد حدّد العلاقة أو السلوك ووقت العلم والدليل. ميّز عدم الرضا بقرار إجرائي عن قلق مؤيد بشأن مركز المحكم.",
    "appointment clause and rules, nomination records, disclosures, relevant correspondence and evidence of the alleged conflict",
    "شرط التعيين والقواعد وسجلات الترشيح والإفصاحات والمراسلات ذات الصلة وأدلة التعارض المدعى به"),
  brief(["Enforcement of court judgments"],
    "Is the judgment ready for enforcement and what remains unpaid?", "هل الحكم جاهز للتنفيذ وما الذي بقي دون وفاء؟",
    "Identify the operative orders, finality or enforceability status, service and any stay. Reconcile payments and the parties named in the judgment. Enforcement should target the obligation actually ordered and the correct debtor, rather than repeat the original claim amount without adjustment.",
    "حدّد منطوق الحكم ونهائيته أو قابليته للتنفيذ والتبليغ وأي وقف. طابق المدفوعات وأسماء المحكوم عليهم. ينبغي أن يستهدف التنفيذ الالتزام المقضي به والمدين الصحيح، لا تكرار مبلغ الدعوى الأصلي دون تعديل.",
    "judgment, enforceability and service records, stay or appeal papers, payment ledger and debtor identifiers",
    "الحكم ومستندات قابلية التنفيذ والتبليغ وأوراق الوقف أو الطعن وبيان المدفوعات ومعرّفات المدين"),
  brief(["Commercial debt recovery"],
    "Does the debt need to be established before it can be enforced?", "هل يلزم إثبات الدين قبل إمكان تنفيذه؟",
    "Identify the debt's basis, due date, amount and any dispute or acknowledgement. Check whether there is already an enforceable instrument or a claim must first be brought. Assess debtor identity and lawful recovery options without assuming that proof of an invoice guarantees collection.",
    "حدّد أساس الدين واستحقاقه ومبلغه وأي منازعة أو إقرار. افحص وجود سند قابل للتنفيذ أو الحاجة إلى إقامة مطالبة أولاً. قيّم هوية المدين ووسائل التحصيل القانونية دون افتراض أن إثبات الفاتورة يضمن التحصيل.",
    "debt agreement, invoices and acceptance records, acknowledgements, payment history and any judgment or instrument",
    "اتفاق الدين والفواتير وإثبات القبول والإقرارات وسجل السداد وأي حكم أو سند"),
  brief(["Enforcement objections and settlement"],
    "Is the objection to the debt, the amount or an enforcement measure?", "هل الاعتراض على الدين أم المبلغ أم إجراء التنفيذ؟",
    "Identify the instrument, enforcement file and precise objection, then reconcile payments or settlement terms. A challenge to the underlying obligation differs from correcting an execution balance or opposing a measure. A proposed settlement should state how the pending enforcement will be handled.",
    "حدّد السند وملف التنفيذ والاعتراض الدقيق ثم طابق السداد أو شروط التسوية. يختلف الطعن في الالتزام الأصلي عن تصحيح الرصيد التنفيذي أو الاعتراض على إجراء. ينبغي أن توضح التسوية المقترحة مصير التنفيذ القائم.",
    "execution instrument, enforcement notices, payment evidence, objection grounds and draft settlement terms",
    "السند التنفيذي وإخطارات التنفيذ وإثبات السداد وأسباب الاعتراض وشروط التسوية المقترحة"),
  brief(["Bounced cheque execution"],
    "What should be checked before seeking execution on a returned cheque?", "ما الذي يُفحص قبل طلب التنفيذ بشيك مرتجع؟",
    "Identify the drawer, payee, amount, date and bank return reason. Record partial or replacement payments and any transfer of the cheque. The instrument's execution route and any separate dispute about the underlying transaction must be checked under the applicable framework.",
    "حدّد الساحب والمستفيد والمبلغ والتاريخ وسبب الإرجاع المصرفي. وثّق الدفعات الجزئية أو البديلة وأي تداول للشيك. تُفحص طريقة تنفيذه وأي منازعة مستقلة في المعاملة الأصلية وفق الإطار المنطبق.",
    "cheque and return memo, underlying transaction, payment records, endorsement information and prior notices",
    "الشيك وإشعار الإرجاع والمعاملة الأصلية وسجلات السداد وبيانات التظهير والإخطارات السابقة"),
  brief(["Foreign judgment enforcement"],
    "What is needed to assess enforcement of a foreign court judgment?", "ما المطلوب لتقييم تنفيذ حكم قضائي أجنبي؟",
    "Identify the issuing court, parties, orders, finality and service, then locate the debtor or assets in the destination. Check recognition requirements and any competing local proceedings. The foreign judgment should be reviewed as a whole, including its procedural history and translations.",
    "حدّد المحكمة والأطراف والمنطوق والنهائية والتبليغ، ثم مكان المدين أو أصوله في الوجهة. افحص متطلبات الاعتراف وأي إجراءات محلية مرتبطة. يُراجع الحكم الأجنبي كاملاً مع تاريخه الإجرائي وترجماته.",
    "complete foreign judgment, finality and service certificates, translations, appeal status and debtor asset details",
    "الحكم الأجنبي كاملاً وشهادات النهائية والتبليغ والترجمات وحالة الطعن وبيانات أصول المدين"),
  brief(["Payment order and urgent debt recovery"],
    "Does the debt fit the requirements of a payment-order procedure?", "هل يطابق الدين شروط إجراء أمر الأداء؟",
    "Identify the written debt evidence, due date, fixed amount and any dispute or prior demand. Check the specific procedure before choosing it. A need for quick recovery does not by itself establish eligibility for a payment order or an urgent protective measure.",
    "حدّد دليل الدين المكتوب والاستحقاق والمبلغ المحدد وأي منازعة أو مطالبة سابقة. افحص الإجراء الخاص قبل اختياره. لا تثبت الحاجة إلى التحصيل السريع وحدها أهلية أمر الأداء أو التدبير العاجل.",
    "written debt instrument, due-date evidence, amount reconciliation, prior demand and debtor responses",
    "سند الدين المكتوب وإثبات الاستحقاق ومطابقة المبلغ والمطالبة السابقة وردود المدين"),
  brief(["Asset tracing and debtor investigation"],
    "What lawful information is available about the debtor and assets?", "ما المعلومات المتاحة قانوناً عن المدين وأصوله؟",
    "Confirm the debtor's identity and distinguish company assets from personal or third-party property. Organise public records and information lawfully obtained through the transaction or proceedings. Asset tracing is an evidence exercise, not permission to access private accounts or databases without authority.",
    "أكّد هوية المدين وافصل أصول الشركة عن أموال الأشخاص أو الغير. نظّم السجلات العامة والمعلومات المحصلة قانوناً من المعاملة أو الإجراءات. تتبع الأصول عمل إثباتي، وليس إذناً بدخول حسابات أو قواعد بيانات خاصة دون صلاحية.",
    "debtor identifiers, lawful registry records, transaction information, judgment or claim documents and known asset references",
    "معرّفات المدين والسجلات المتاحة قانوناً وبيانات المعاملة والحكم أو المطالبة ومراجع الأصول المعروفة"),
  brief(["Travel-ban application for debt recovery"],
    "What facts would support or answer the proposed travel-restriction request?", "ما الوقائع التي تؤيد طلب قيد السفر أو الرد عليه؟",
    "Identify the debt, procedural stage and evidence relied on for the requested restriction. Separate recovery of money from a measure affecting travel. Such a request requires the applicable legal conditions and authority to be checked; an unpaid balance alone should not be treated as sufficient.",
    "حدّد الدين والمرحلة الإجرائية والدليل المستند إليه لطلب القيد. افصل تحصيل المال عن التدبير المؤثر في السفر. يلزم فحص الشروط القانونية والجهة المختصة، ولا يُعامل الرصيد غير المدفوع وحده بوصفه كافياً.",
    "debt or judgment documents, existing proceedings, specific supporting facts and any travel-restriction decision",
    "مستندات الدين أو الحكم والإجراءات القائمة والوقائع المؤيدة المحددة وأي قرار بقيد السفر"),
  brief(["Asset attachment and protective-measure request"],
    "Are you requesting attachment or challenging an existing measure in Syria?", "هل تطلب الحجز أم تعترض على تدبير قائم في سوريا؟",
    "Identify the property, location, debt and requested measure. Obtain any existing attachment order and its legal basis. Civil and security-based attachments are distinct; neither means general suspension of government services. Explain urgency and ownership before selecting a filing.",
    "حدّد المال وموقعه وحق الدائن والتدبير المطلوب بدقة. وعند وجود حجز قائم، احصل على قرار إصداره وسنده القانوني. يختلف الحجز التحفظي المدني عن الحجز الإداري المبني على سبب أمني؛ ولا يُسمى أي منهما إيقافاً عاماً للخدمات الحكومية. بيّن الاستعجال وأدلة الملكية قبل اختيار الطلب.",
    "claim evidence, asset and ownership records, existing attachment decision, issuing authority and urgency evidence",
    "دليل المطالبة وسجلات المال والملكية وقرار الحجز القائم والجهة المصدرة وأدلة الاستعجال"),
  brief(["Service suspension and asset-freezing request"],
    "Which restriction or asset measure is actually sought?", "ما القيد أو التدبير على الأموال المطلوب فعلاً؟",
    "Identify the asset, account or service affected and the existing court or enforcement file. Do not combine distinct restrictions under one label. The available measure, safeguards and authority depend on the jurisdiction and stage, and should be assessed before a request is drafted.",
    "حدّد الأصل أو الحساب أو الخدمة المتأثرة وملف المحكمة أو التنفيذ القائم. لا تجمع قيوداً مختلفة تحت تسمية واحدة. يتوقف التدبير والضمانات والجهة على الاختصاص والمرحلة، ويجب تقييمها قبل صياغة الطلب.",
    "enforcement instrument, file reference, asset identifiers, existing orders and the precise proposed measure",
    "السند التنفيذي ومرجع الملف ومعرّفات الأصول والأوامر القائمة والتدبير المقترح بدقة"),
  brief(["Promissory-note and commercial-paper enforcement"],
    "What must be checked in the note or commercial instrument?", "ما الذي يُراجع في السند لأمر أو الورقة التجارية؟",
    "Examine the original instrument, parties, amount, maturity and transfer history. Record payments and the specific defence or execution request. Formal requirements and the underlying transaction are separate questions; the document's label does not settle its enforceability.",
    "افحص أصل الورقة وأطرافها ومبلغها واستحقاقها وتسلسل تداولها. وثّق المدفوعات والدفع أو طلب التنفيذ المحدد. الشروط الشكلية والمعاملة الأصلية مسألتان منفصلتان؛ ولا تحسم تسمية المستند قابليته للتنفيذ.",
    "original note or instrument, endorsements, maturity and payment records, underlying agreement and execution notices",
    "أصل السند أو الورقة والتظهيرات وسجلات الاستحقاق والسداد والاتفاق الأصلي وإخطارات التنفيذ"),
  brief(["Bank-account and salary seizure dispute"],
    "What funds were seized and under which order?", "ما الأموال المحجوزة وبموجب أي أمر؟",
    "Obtain the seizure order and identify the account holder, source of funds and amount affected. Reconcile the execution balance and any previous payment. Questions about protected amounts, third-party funds or excessive seizure require the applicable rules and account evidence to be reviewed.",
    "احصل على أمر الحجز وحدّد صاحب الحساب ومصدر الأموال والمبلغ المتأثر. طابق الرصيد التنفيذي والسداد السابق. تحتاج مسائل المبالغ المحمية وأموال الغير أو تجاوز الحجز إلى مراجعة القواعد وأدلة الحساب.",
    "seizure order, bank statements, salary records, execution balance, payment evidence and any third-party ownership documents",
    "أمر الحجز وكشوف الحساب وسجلات الراتب والرصيد التنفيذي وإثبات السداد ومستندات ملكية الغير إن وجدت"),
  brief(["Execution against an unavailable or absconding debtor"],
    "What can be established when the debtor cannot be contacted?", "ما الذي يمكن إثباته عند تعذر الوصول إلى المدين؟",
    "Confirm identity, last known address, service attempts and lawfully known assets. Distinguish inability to contact the debtor from evidence of evasion. The next execution step depends on valid procedure and identifiable assets, not an assumption that absence proves misconduct.",
    "أكّد الهوية وآخر عنوان معروف ومحاولات التبليغ والأصول المعروفة قانوناً. ميّز تعذر التواصل عن دليل التهرب. تتوقف الخطوة التنفيذية على الإجراء الصحيح والأصول المحددة، لا افتراض أن الغياب يثبت سوء السلوك.",
    "enforcement title, debtor identifiers, service-attempt records, address information and lawful asset references",
    "السند التنفيذي ومعرّفات المدين وسجلات محاولات التبليغ وبيانات العنوان ومراجع الأصول المتاحة قانوناً"),
  brief(["Objection to an execution judge's decision"],
    "Which execution decision is challenged and when was it notified?", "ما قرار قاضي التنفيذ المعترض عليه ومتى بُلّغ؟",
    "Obtain the decision's operative terms and reasons, notification record and current file status. State the alleged procedural or substantive error precisely. An objection to that decision differs from reopening the original judgment, and the available review route must be checked.",
    "احصل على منطوق القرار وأسبابه وإثبات التبليغ وحالة الملف. حدّد الخطأ الإجرائي أو الموضوعي المدعى به بدقة. يختلف الاعتراض على القرار عن إعادة فتح الحكم الأصلي، ويلزم التحقق من طريق المراجعة المتاح.",
    "execution decision, notification, original instrument, relevant applications and evidence supporting the alleged error",
    "قرار التنفيذ وتبليغه والسند الأصلي والطلبات ذات الصلة وأدلة الخطأ المدعى به"),
  brief(["Bounced-cheque defence and criminal complaint concern"],
    "Is there an execution demand, a criminal complaint or both?", "هل توجد مطالبة تنفيذية أم شكوى جزائية أم الاثنتان؟",
    "Identify the cheque return reason and the actual document received from the bank or authority. Record payments, signature or authority disputes and the transaction context. Civil recovery and any alleged offence require separate assessment; do not assume every returned cheque has the same criminal consequence.",
    "حدّد سبب إرجاع الشيك والمستند الفعلي الوارد من المصرف أو الجهة. وثّق السداد والخلاف على التوقيع أو الصلاحية وسياق المعاملة. يحتاج التحصيل المدني والاتهام إلى تقييم منفصل؛ فليست لكل شيك مرتجع النتيجة الجزائية نفسها.",
    "cheque and return memo, summons or execution notice, payment evidence, transaction records and signing-authority documents",
    "الشيك وإشعار الإرجاع والاستدعاء أو إخطار التنفيذ وإثبات السداد وسجلات المعاملة ومستندات صلاحية التوقيع"),
  brief(["Wrongful debt-collection or creditor harassment complaint"],
    "What collection conduct is being challenged separately from the debt?", "ما سلوك التحصيل المعترض عليه بصورة مستقلة عن الدين؟",
    "Record who contacted whom, the messages, frequency and any threats or disclosure to others. Keep the disputed balance separate from the conduct complaint. A legitimate debt does not answer every question about collection methods, and a conduct complaint does not automatically erase the debt.",
    "وثّق المتصل والمخاطب والرسائل وتكرارها وأي تهديد أو إفصاح للغير. افصل الرصيد المتنازع عليه عن شكوى السلوك. لا يجيب ثبوت الدين عن كل مسألة تخص التحصيل، ولا تمحو شكوى السلوك الدين تلقائياً.",
    "collection messages and call log, creditor or collector identity, debt statement and previous complaints",
    "رسائل التحصيل وسجل الاتصالات وهوية الدائن أو المحصل وكشف الدين والشكاوى السابقة"),
  brief(["Execution of a Syrian court judgment"],
    "What does the Syrian judgment order and what stage has execution reached?", "بماذا قضى الحكم السوري وإلى أي مرحلة وصل التنفيذ؟",
    "Read the operative judgment and identify its enforceability, parties, notification and any stay. Reconcile compliance and the execution file. If assets are abroad, distinguish Syrian execution steps from recognition required in the country where recovery is sought.",
    "اقرأ منطوق الحكم وحدّد قابليته للتنفيذ وأطرافه وتبليغه وأي وقف. طابق ما نُفذ مع الملف التنفيذي. وعند وجود أصول بالخارج افصل إجراءات التنفيذ السورية عن الاعتراف المطلوب في دولة التحصيل.",
    "Syrian judgment, execution copy and file, service records, stay decisions, payment evidence and asset location",
    "الحكم السوري وصورته وملفه التنفيذي وسجلات التبليغ وقرارات الوقف وإثبات السداد وموقع الأصول"),
  brief(["Objection to an execution measure or seizure"],
    "Why is the specific execution measure said to be incorrect?", "لماذا يُقال إن إجراء التنفيذ أو الحجز المحدد غير صحيح؟",
    "Identify the measure, property affected and the objector's interest. Compare the order with the actual seizure and execution balance. Separate a third party's ownership claim from a debtor's procedural objection or payment defence so the requested correction is precise.",
    "حدّد الإجراء والمال المتأثر ومصلحة المعترض. قارن الأمر بالحجز الفعلي والرصيد التنفيذي. افصل ادعاء ملكية الغير عن الاعتراض الإجرائي للمدين أو الدفع بالسداد ليكون التصحيح المطلوب دقيقاً.",
    "measure or seizure record, execution order, ownership documents, payment ledger and notification evidence",
    "محضر الإجراء أو الحجز وأمر التنفيذ ومستندات الملكية وبيان السداد وإثبات التبليغ"),
];
