import { brief } from "./types.js";
export const BUSINESS_BRIEFS = [
  brief(["Commercial disputes"],
    "How do I identify the central issue in a commercial dispute?", "كيف أحدد المسألة الأساسية في النزاع التجاري؟",
    "Map the parties, transaction, promised performance and disputed outcome. Separate an unpaid balance from defective performance, ownership rights or a regulatory complaint. This identifies the agreement and evidence to review before selecting negotiation, a contractual process or proceedings.",
    "حدّد الأطراف والمعاملة والأداء المتفق عليه والنتيجة المتنازع عليها. افصل الرصيد غير المدفوع عن التنفيذ المعيب وحقوق الملكية والشكوى التنظيمية. بذلك يتحدد الاتفاق والدليل المطلوبان قبل اختيار التفاوض أو المسار العقدي أو التقاضي.",
    "transaction agreements, orders, performance and payment records, notices and a chronology of the dispute",
    "اتفاقات المعاملة والطلبات وسجلات التنفيذ والسداد والإخطارات وتسلسل النزاع"),
  brief(["Supplier and customer claims"],
    "What did the supplier promise and what did the customer accept?", "ماذا تعهد المورد بتقديمه وماذا قبل العميل؟",
    "Match each order to delivery, inspection, acceptance or rejection and the corresponding invoice. Record returns, credits and complaints. Identify whether the claim concerns quantity, quality, timing or payment rather than describing every disagreement as a general supply failure.",
    "اربط كل طلب بالتسليم والفحص والقبول أو الرفض والفاتورة المقابلة. سجّل المرتجعات والإشعارات الدائنة والشكاوى. حدّد هل المطالبة على الكمية أو الجودة أو التوقيت أو السداد بدلاً من وصف كل خلاف بأنه فشل توريد عام.",
    "purchase orders, specifications, delivery notes, inspection records, invoices, returns and customer complaints",
    "أوامر الشراء والمواصفات وأذونات التسليم ومحاضر الفحص والفواتير والمرتجعات وشكاوى العميل"),
  brief(["Business contract risk"],
    "Which contract terms could disrupt the proposed business transaction?", "ما البنود التي قد تعرقل المعاملة التجارية المقترحة؟",
    "Review who can change scope or price, when payment is due, how performance is accepted and what happens on delay or exit. Identify obligations that depend on third parties. Prioritise risks by their effect on the actual deal rather than using a generic clause checklist.",
    "راجع من يملك تغيير النطاق أو السعر وموعد السداد وآلية قبول الأداء وأثر التأخير أو الخروج. حدّد الالتزامات المعتمدة على الغير. رتّب المخاطر بحسب أثرها في المعاملة الفعلية بدلاً من الاكتفاء بقائمة بنود عامة.",
    "complete contract draft, commercial term sheet, pricing model, delivery plan and assumptions about third-party performance",
    "مسودة العقد كاملة والشروط التجارية ونموذج التسعير وخطة التسليم وافتراضات أداء الأطراف الأخرى"),
  brief(["Commercial liability"],
    "Whose obligation and conduct caused the alleged business loss?", "التزام من وتصرف من تسببا بالخسارة التجارية المدعاة؟",
    "Identify the legal entity or person alleged to be responsible, the obligation breached and the connection to each loss item. Separate company obligations, personal guarantees and alleged misconduct. A large loss alone does not identify who is liable or on what basis.",
    "حدّد الشخص أو المنشأة المدعى بمسؤوليتهما والالتزام المخالف والصلة بكل بند خسارة. افصل التزامات الشركة عن الكفالات الشخصية والسلوك المنسوب. لا تحدد ضخامة الخسارة وحدها المسؤول أو أساس مسؤوليته.",
    "relevant agreements, authority records, alleged breach evidence, loss calculation and mitigation correspondence",
    "الاتفاقات ذات الصلة وسجلات الصلاحية وأدلة الإخلال المدعى به وحساب الخسارة ومراسلات الحد منها"),
  brief(["Negotiation and settlement strategy"],
    "What should be agreed before making a settlement offer?", "ما الذي أحدده قبل تقديم عرض تسوية؟",
    "Define the objective, evidence-supported position, payment capacity and non-financial terms that matter. Identify who can bind each party and which claims would be released. A workable settlement needs clear performance, timing and consequences of default, not only an agreed headline amount.",
    "حدّد الهدف والموقف المؤيد بالأدلة والقدرة على السداد والشروط غير المالية المهمة. تحقّق ممن يملك إلزام كل طرف والمطالبات المشمولة بالمخالصة. تحتاج التسوية القابلة للتنفيذ إلى أداء وموعد وأثر واضح للتعثر، لا إلى مبلغ إجمالي فقط.",
    "claim and defence documents, offer history, financial proposal, authority to settle and draft release terms",
    "مستندات المطالبة والدفاع والعروض السابقة والمقترح المالي وصلاحية التسوية وشروط المخالصة المقترحة"),
  brief(["Company formation and registration"],
    "What business decisions should precede company registration?", "ما القرارات التجارية التي تسبق تسجيل الشركة؟",
    "Set out the owners, activity, funding, management authority and intended operating locations. Compare the proposed structure with licensing and tax questions before filing. Registration documents should reflect the real business arrangement, including who contributes assets and controls decisions.",
    "حدّد الملاك والنشاط والتمويل وصلاحيات الإدارة ومواقع التشغيل. قارن الهيكل المقترح بمسائل الترخيص والضريبة قبل التقديم. ينبغي أن تعكس مستندات التسجيل الترتيب الفعلي، بما فيه مقدم الأصول وصاحب القرار.",
    "owner details, business plan, proposed capital and ownership split, draft constitutional documents and activity-licensing information",
    "بيانات الملاك وخطة النشاط ورأس المال والحصص المقترحة ومسودة وثائق التأسيس وبيانات ترخيص النشاط"),
  brief(["Commercial supply contract dispute"],
    "Does the supply dispute arise from the framework contract or a specific order?", "هل نزاع التوريد ناشئ عن العقد الإطاري أم طلب معين؟",
    "Read the framework terms alongside the disputed order and any later change. Identify the agreed specification, delivery point, acceptance process and payment trigger. A disagreement about one shipment may not justify treating every order or the whole relationship as terminated.",
    "اقرأ الشروط الإطارية مع الطلب المتنازع عليه وأي تعديل لاحق. حدّد المواصفة ومكان التسليم وآلية القبول وشرط السداد. قد لا يبرر الخلاف على شحنة واحدة اعتبار كل الطلبات أو العلاقة بأكملها منتهية.",
    "framework agreement, disputed orders, specifications, delivery and acceptance records, variations and termination notices",
    "الاتفاق الإطاري والطلبات محل النزاع والمواصفات وسجلات التسليم والقبول والتعديلات وإخطارات الإنهاء"),
  brief(["Commercial agency termination"],
    "What distinguishes ending an agency from ending an ordinary supply arrangement?", "ما الذي يميز إنهاء الوكالة عن إنهاء علاقة توريد عادية؟",
    "Identify the agency terms, territory, products, registration position and termination ground. Record notice, remaining stock, commissions and customer commitments. The legal treatment should follow the actual relationship and applicable agency framework rather than the contract's label alone.",
    "حدّد شروط الوكالة والإقليم والمنتجات وحالة التسجيل وسبب الإنهاء. وثّق الإخطار والمخزون والعمولات والتزامات العملاء. يتبع التقييم العلاقة الفعلية وإطار الوكالة المنطبق، لا اسم العقد وحده.",
    "agency agreement and registration, termination notice, sales and commission accounts, inventory and customer commitments",
    "عقد الوكالة وتسجيلها وإخطار الإنهاء وحسابات المبيعات والعمولات والمخزون والتزامات العملاء"),
  brief(["Commercial concealment dispute"],
    "What arrangement is alleged to conceal ownership or control?", "ما الترتيب المدعى بأنه يخفي الملكية أو السيطرة؟",
    "Identify the registered owner, actual operator, funding, decision-making and revenue flows. Keep the allegation and evidence separate. The meaning and consequences of a concealment allegation depend on the jurisdiction and activity; a nominee arrangement should not be assessed from its name alone.",
    "حدّد المالك المسجل والمشغل الفعلي والتمويل وصنع القرار وتدفقات الإيراد. افصل الادعاء عن الدليل. يتوقف معنى التستر وآثاره على الاختصاص والنشاط؛ فلا يُقيّم ترتيب اسمي من تسميته وحدها.",
    "business registration, ownership and management agreements, funding records, account authority and the actual allegation or notice",
    "السجل التجاري واتفاقات الملكية والإدارة وسجلات التمويل وصلاحيات الحساب والادعاء أو الإخطار الفعلي"),
  brief(["Shareholder and partner dispute"],
    "Is the business partner's claim contractual or based on share ownership?", "هل مطالبة الشريك التجاري عقدية أم ناشئة عن ملكية الحصص؟",
    "Identify each party's contributions and promises, then separate the business agreement from company ownership. Profit-sharing, repayment of funding and shareholder rights are different claims. This review addresses the commercial relationship; governance questions need the constitutional documents too.",
    "حدّد مساهمة كل طرف وتعهداته، ثم افصل الاتفاق التجاري عن سجلات ملكية الشركة. اقتسام الربح ورد التمويل وحقوق المساهم مطالبات مختلفة. تتناول هذه المسألة العلاقة التجارية، وتحتاج حوكمة الشركة أيضاً إلى وثائق تأسيسها.",
    "partnership or joint-business agreement, contributions, profit accounts, ownership records and disputed commitments",
    "اتفاق الشراكة أو النشاط المشترك والمساهمات وحسابات الأرباح وسجلات الملكية والتعهدات المتنازع عليها"),
  brief(["Government tender dispute"],
    "At what stage did the government tender dispute arise?", "في أي مرحلة نشأ نزاع المنافسة الحكومية؟",
    "Distinguish tender eligibility, bid evaluation, award and performance after signing. Obtain the decision and relevant tender condition. A pre-award challenge differs from a government-contract payment claim, so the complaint should identify the specific decision and stage.",
    "ميّز التأهيل وتقييم العرض والترسية والتنفيذ بعد التوقيع. احصل على القرار وشرط المنافسة ذي الصلة. يختلف الاعتراض قبل الترسية عن مطالبة سداد في عقد حكومي، لذا حدّد القرار والمرحلة في الشكوى.",
    "tender documents, submitted bid, clarifications, evaluation or award notice and evidence of notification",
    "وثائق المنافسة والعرض المقدم والاستيضاحات وإخطار التقييم أو الترسية وإثبات التبليغ"),
  brief(["Franchise agreement and termination dispute"],
    "Which franchise obligations remain disputed at termination?", "ما التزامات الامتياز المتنازع عليها عند الإنهاء؟",
    "Review the brand licence, operating standards, fees, territory and termination provisions. Identify outstanding stock, customer obligations, de-branding and data access. Ending the franchise relationship may require several coordinated steps; the notice alone may not resolve them.",
    "راجع ترخيص العلامة ومعايير التشغيل والرسوم والإقليم وشروط الإنهاء. حدّد المخزون والتزامات العملاء وإزالة الهوية التجارية والوصول إلى البيانات. قد يتطلب إنهاء الامتياز خطوات مترابطة لا يحسمها الإخطار وحده.",
    "franchise contract, disclosure material, fee accounts, operational notices, inventory and termination correspondence",
    "عقد الامتياز ومواد الإفصاح وحسابات الرسوم والإخطارات التشغيلية والمخزون ومراسلات الإنهاء"),
  brief(["Commercial distribution and agency dispute"],
    "Is the intermediary a distributor, agent or another type of partner?", "هل الوسيط موزع أم وكيل أم شريك من نوع آخر؟",
    "Examine who contracts with customers, owns stock, bears payment risk and earns a margin or commission. Compare the actual conduct with the written terms. Classification matters to the review of exclusivity, territory, termination and unpaid amounts.",
    "افحص من يتعاقد مع العملاء ويملك المخزون ويتحمل مخاطر السداد ويحصل على هامش أو عمولة. قارن السلوك الفعلي بالشروط المكتوبة. يهم التكييف عند بحث الحصرية والإقليم والإنهاء والمبالغ غير المدفوعة.",
    "distribution or agency terms, customer contracts, invoices, stock ownership records and commission arrangements",
    "شروط التوزيع أو الوكالة وعقود العملاء والفواتير وسجلات ملكية المخزون وترتيبات العمولة"),
  brief(["Commercial due diligence before acquisition or investment"],
    "Which commercial commitments could change the value of the transaction?", "ما الالتزامات التجارية التي قد تغير قيمة المعاملة؟",
    "Review material customer and supplier contracts, concentration of revenue, termination rights, disputes and obligations triggered by a change of control. Separate verified documents from management explanations. The findings should inform price, conditions and protections in the proposed transaction.",
    "راجع العقود الجوهرية للعملاء والموردين وتركز الإيرادات وحقوق الإنهاء والنزاعات والالتزامات المرتبطة بتغير السيطرة. افصل المستندات المثبتة عن شروح الإدارة. ينبغي أن تؤثر النتائج في السعر والشروط والحماية ضمن المعاملة المقترحة.",
    "material contracts, revenue schedules, dispute list, change-of-control terms and the proposed transaction structure",
    "العقود الجوهرية وجداول الإيراد وقائمة النزاعات وشروط تغير السيطرة وهيكل المعاملة المقترح"),
  brief(["Business sale and purchase dispute"],
    "What did the business sale include and what was actually transferred?", "ماذا شمل بيع النشاط وما الذي نُقل فعلاً؟",
    "Compare the assets, shares, liabilities and operating rights promised with the closing records. Identify price adjustments, warranties and post-closing obligations. A dispute about a transferred business should distinguish an omitted asset from an inaccurate representation or unpaid purchase price.",
    "قارن الأصول والحصص والالتزامات وحقوق التشغيل الموعودة بسجلات الإتمام. حدّد تعديلات السعر والضمانات والالتزامات اللاحقة. ميّز الأصل غير المنقول عن البيان غير الدقيق أو ثمن الشراء غير المدفوع.",
    "sale agreement, asset and liability schedules, closing documents, price calculations and warranty notices",
    "عقد البيع وجداول الأصول والالتزامات ومستندات الإتمام وحسابات الثمن وإخطارات الضمان"),
  brief(["Competition and unfair-trade-practice complaint"],
    "Which market conduct is the competition complaint about?", "ما السلوك السوقي الذي تتناوله شكوى المنافسة؟",
    "Identify the conduct, parties, relevant products and effect on customers or market access. Keep evidence of pricing, exclusivity or exclusion separate from a private contract grievance. A difficult competitor or lost sale alone does not establish a competition-law infringement.",
    "حدّد السلوك والأطراف والمنتجات وأثره في العملاء أو دخول السوق. افصل أدلة التسعير أو الحصرية أو الإقصاء عن خلاف عقدي خاص. لا يثبت وجود منافس قوي أو خسارة بيع وحدهما مخالفة لقواعد المنافسة.",
    "agreements, pricing and market-access evidence, communications, relevant transaction data and prior authority correspondence",
    "الاتفاقات وأدلة التسعير ودخول السوق والمراسلات وبيانات المعاملات ذات الصلة ومراسلات الجهة السابقة"),
  brief(["Commercial-register and company-record dispute"],
    "Does the commercial register reflect the authorised business position?", "هل يعكس السجل التجاري وضع النشاط المعتمد؟",
    "Identify the disputed business name, activity, manager or registration status and the underlying decision authorising it. Compare the register with company resolutions and filings. A record correction differs from challenging whether the corporate decision itself was valid.",
    "حدّد الاسم أو النشاط أو المدير أو حالة التسجيل محل الخلاف والقرار المؤيد لها. قارن السجل بقرارات الشركة وطلباتها. يختلف تصحيح القيد عن الطعن في صحة القرار المؤسسي نفسه.",
    "current registry extract, company resolutions, filed applications, authority records and refusal or correction correspondence",
    "المستخرج التجاري الحالي وقرارات الشركة والطلبات المقدمة وسجلات الصلاحية ومراسلات الرفض أو التصحيح"),
  brief(["Termination of an exclusive distribution relationship"],
    "What survives the end of an exclusive distribution arrangement?", "ما الذي يبقى بعد إنهاء علاقة توزيع حصرية؟",
    "Identify the territory and products covered, notice given, remaining inventory and customer commitments. Review exclusivity alongside minimum purchases and exit obligations. Stock disposal, use of branding and outstanding rebates need explicit treatment rather than assuming termination settles every account.",
    "حدّد الإقليم والمنتجات والإخطار والمخزون والتزامات العملاء. راجع الحصرية مع الحد الأدنى للمشتريات والتزامات الخروج. تحتاج تصفية المخزون واستعمال العلامة والخصومات المتبقية إلى معالجة صريحة، لا افتراض أن الإنهاء يسوي كل الحسابات.",
    "exclusive distribution agreement, sales targets, termination notice, inventory, rebates and customer-order commitments",
    "عقد التوزيع الحصري وأهداف المبيعات وإخطار الإنهاء والمخزون والخصومات والتزامات طلبات العملاء"),
];
