import { brief } from "./types.js";
export const COMPANY_INVESTMENT_BRIEFS = [
  brief(["Foreign-owned company formation"],
    "What must be checked before incorporating a foreign-owned business?", "ما الذي يُفحص قبل تأسيس نشاط مملوك لأجانب؟",
    "Identify the investors, ownership chain, proposed activity and operating location. Separate incorporation from investment approval, activity licensing and permission to employ or occupy premises. The proposed ownership structure should be checked against the actual business model before funds are committed.",
    "حدّد المستثمرين وتسلسل الملكية والنشاط ومكان التشغيل. افصل التأسيس عن موافقة الاستثمار وترخيص النشاط وأذونات التوظيف أو إشغال المقر. ينبغي فحص هيكل الملكية وفق نموذج العمل الفعلي قبل الالتزام بالأموال.",
    "investor and beneficial-owner records, ownership chart, business plan, proposed premises and activity description",
    "مستندات المستثمرين والمستفيدين الحقيقيين ومخطط الملكية وخطة العمل والمقر المقترح ووصف النشاط"),
  brief(["Investment and business licensing"],
    "Which approvals are needed for the proposed investment activity?", "ما الموافقات التي يحتاج إليها النشاط الاستثماري المقترح؟",
    "Describe what the business will actually do, where it will operate and who will own and manage it. List existing approvals and their limits. An investment approval, commercial registration and sector licence may address different questions and should not be treated as interchangeable.",
    "صف ما سيفعله النشاط فعلياً وأين سيعمل ومن يملكه ويديره. احصر الموافقات القائمة وحدودها. قد تعالج موافقة الاستثمار والسجل التجاري وترخيص القطاع مسائل مختلفة، ولا ينبغي اعتبارها بدائل متطابقة.",
    "activity plan, investor documents, existing approvals, licence conditions and application correspondence",
    "خطة النشاط ومستندات المستثمر والموافقات القائمة وشروط الترخيص ومراسلات الطلبات"),
  brief(["Market-entry legal structure"],
    "How should I compare a subsidiary, branch or contractual entry model?", "كيف أقارن الشركة التابعة والفرع والدخول عبر عقد؟",
    "Compare ownership, operational control, liability, contracting, tax questions and exit needs for the actual activity. Include licensing and local execution requirements in the comparison. The most convenient formation process is not necessarily the structure that fits the intended investment.",
    "قارن الملكية والسيطرة التشغيلية والمسؤولية والتعاقد والمسائل الضريبية واحتياجات الخروج بحسب النشاط. أدخل متطلبات الترخيص والتنفيذ المحلي في المقارنة. ليست سهولة إجراءات التأسيس وحدها دليلاً على ملاءمة الهيكل للاستثمار.",
    "business and funding plans, group structure, intended customer contracts, proposed activities and exit assumptions",
    "خطتا العمل والتمويل وهيكل المجموعة وعقود العملاء المقصودة والأنشطة المقترحة وافتراضات الخروج"),
  brief(["Regulatory compliance"],
    "Which investment obligations need ongoing attention after approval?", "ما الالتزامات الاستثمارية التي تحتاج إلى متابعة بعد الموافقة؟",
    "List the licences, conditions, reporting duties and renewal dates attached to the actual operation. Identify changes in ownership, activity or premises since approval. Compliance review should compare current practice with the applicable permissions, rather than assume the original approval covers later changes.",
    "احصر التراخيص وشروطها وواجبات الإبلاغ ومواعيد التجديد المرتبطة بالتشغيل. حدّد تغيرات الملكية أو النشاط أو المقر منذ الموافقة. تقارن المراجعة الممارسة الحالية بالأذونات المنطبقة، ولا تفترض أن الموافقة الأصلية تشمل كل تغيير لاحق.",
    "licences and conditions, compliance calendar, ownership and activity changes, filings and regulator notices",
    "التراخيص وشروطها وجدول الامتثال وتغيرات الملكية والنشاط والإقرارات وإخطارات الجهة التنظيمية"),
  brief(["Investor and cross-border disputes"],
    "Which contracts and jurisdictions govern the investor's dispute?", "ما العقود والاختصاصات المرتبطة بنزاع المستثمر؟",
    "Map the investor, operating entity, counterparties and asset locations. Identify the agreement or decision challenged and any dispute-resolution clause. A claim against a private partner differs from a regulatory challenge; cross-border elements do not themselves establish a treaty or arbitration claim.",
    "حدّد المستثمر والمنشأة المشغلة والأطراف المقابلة ومواقع الأصول. بيّن الاتفاق أو القرار محل المنازعة وشرط تسوية النزاع إن وجد. تختلف المطالبة ضد شريك خاص عن الطعن التنظيمي؛ ولا ينشئ العنصر الأجنبي وحده مطالبة اتفاقية أو تحكيمية.",
    "investment agreements, ownership records, dispute clauses, authority decisions and a map of relevant assets and jurisdictions",
    "اتفاقات الاستثمار وسجلات الملكية وشروط النزاع وقرارات الجهات وبيان الأصول والاختصاصات ذات الصلة"),
  brief(["Investment licence refusal or cancellation"],
    "What reason did the authority give for refusing or cancelling the licence?", "ما السبب الذي ذكرته الجهة لرفض ترخيص الاستثمار أو إلغائه؟",
    "Obtain the decision, reasons and notification record. Compare the alleged deficiency with the application and licence conditions. Clarify whether the issue can be corrected, requires a response or challenges the decision itself; an informal explanation is not a substitute for the written decision.",
    "احصل على القرار وأسبابه وإثبات التبليغ. قارن النقص المدعى به بالطلب وشروط الترخيص. حدّد هل المطلوب استكمال أو رد أو طعن في القرار نفسه؛ فالتفسير غير الرسمي لا يغني عن القرار المكتوب.",
    "application and attachments, licence conditions, refusal or cancellation decision, service record and previous responses",
    "الطلب ومرفقاته وشروط الترخيص وقرار الرفض أو الإلغاء وإثبات التبليغ والردود السابقة"),
  brief(["Foreign investor compensation claim"],
    "What act and loss support the investor's compensation request?", "ما التصرف والخسارة اللذان تستند إليهما مطالبة المستثمر بالتعويض؟",
    "Identify the challenged act, responsible party, investment affected and each loss item. Separate contractual promises from government measures and commercial expectations. The basis for compensation, forum and causal link require specific evidence; the amount invested alone is not a complete loss calculation.",
    "حدّد التصرف المعترض عليه والطرف المسؤول والاستثمار المتأثر وكل بند خسارة. افصل الوعود العقدية عن التدابير الحكومية والتوقعات التجارية. يحتاج أساس التعويض والاختصاص والسببية إلى دليل محدد؛ ولا يكتمل حساب الخسارة بمبلغ الاستثمار وحده.",
    "investment and funding records, challenged decisions or breaches, financial loss schedule and mitigation evidence",
    "سجلات الاستثمار والتمويل والقرارات أو الإخلالات محل المنازعة وجدول الخسارة وأدلة الحد منها"),
  brief(["Foreign investor and local-partner dispute"],
    "What roles and contributions were agreed with the local partner?", "ما الأدوار والمساهمات المتفق عليها مع الشريك المحلي؟",
    "Compare registered ownership with the investment agreement, contributions, management powers and profit arrangements. Identify the disputed obligation and who controls accounts or assets. Ownership, funding repayment and operational control should be analysed separately before proposing an exit or claim.",
    "قارن الملكية المسجلة باتفاق الاستثمار والمساهمات وصلاحيات الإدارة وترتيبات الربح. حدّد الالتزام المختلف عليه ومن يسيطر على الحسابات أو الأصول. يلزم فصل الملكية ورد التمويل والسيطرة التشغيلية قبل اقتراح خروج أو مطالبة.",
    "joint-venture agreement, ownership chart, contribution records, management mandates and disputed accounts",
    "اتفاق المشروع المشترك ومخطط الملكية وسجلات المساهمات وتفويضات الإدارة والحسابات المتنازع عليها"),
  brief(["Foreign investor due diligence and market-entry review"],
    "What should be verified before relying on a local investment proposal?", "ما الذي يُتحقق منه قبل الاعتماد على عرض استثماري محلي؟",
    "Verify the proposed partner's identity, ownership, authority, licences and rights over the assets offered. Test material statements against documents and identify conditions that remain unconfirmed. Distinguish completed diligence from assumptions that must become conditions of the investment agreement.",
    "تحقّق من هوية الشريك المقترح وملكيته وصلاحياته وتراخيصه وحقوقه في الأصول المعروضة. قارن البيانات الجوهرية بالمستندات وحدّد الشروط غير المؤكدة. ميّز الفحص المنجز عن الافتراضات الواجب جعلها شروطاً لاتفاق الاستثمار.",
    "partner registration, licences, asset records, proposed investment terms, financial information and diligence responses",
    "سجل الشريك وتراخيصه ومستندات الأصول وشروط الاستثمار المقترحة والمعلومات المالية وردود الفحص"),
  brief(["Investment exit, repatriation and shareholder dispute"],
    "What must happen before the investor can complete the proposed exit?", "ما الذي يجب بحثه لإتمام خروج المستثمر المقترح؟",
    "Separate selling shares, settling shareholder funding, distributing proceeds and transferring money across borders. Identify approval, valuation and payment conditions and any ongoing liabilities. An agreed sale price does not establish that every corporate, banking or tax step is complete.",
    "افصل بيع الحصص وتسوية تمويل المساهم وتوزيع الحصيلة وتحويل الأموال عبر الحدود. حدّد شروط الموافقة والتقييم والسداد والالتزامات المستمرة. لا يعني الاتفاق على سعر البيع اكتمال كل خطوة مؤسسية أو مصرفية أو ضريبية.",
    "exit and shareholder agreements, valuations, funding balances, approvals, proposed payment route and liability schedule",
    "اتفاقات الخروج والمساهمين والتقييمات وأرصدة التمويل والموافقات ومسار الدفع المقترح وجدول الالتزامات"),
  brief(["Foreign-investor licensing and registration problem"],
    "Is the foreign-investor file missing approval, registration or an amendment?", "هل ينقص ملف المستثمر الأجنبي موافقة أم تسجيل أم تعديل؟",
    "Identify the investor's present registration and the exact activity or change requested. Compare the submitted file with the authority's written requirements. Separate a new approval from correcting an existing record or updating ownership, so the response addresses the actual deficiency.",
    "حدّد تسجيل المستثمر الحالي والنشاط أو التغيير المطلوب بدقة. قارن الملف المقدم بمتطلبات الجهة المكتوبة. افصل الموافقة الجديدة عن تصحيح سجل قائم أو تحديث الملكية ليتناول الرد النقص الفعلي.",
    "investor registration, current approvals, amendment request, ownership documents and written deficiency notice",
    "تسجيل المستثمر والموافقات الحالية وطلب التعديل ومستندات الملكية وإخطار النقص المكتوب"),
  brief(["Cross-border investment payment or exit dispute"],
    "Where did the cross-border payment or exit process stop?", "أين تعثر الدفع أو الخروج الاستثماري عبر الحدود؟",
    "Trace the agreed payment from the contractual payer through the banking route to the intended recipient. Identify whether the obstacle is a disputed obligation, incomplete exit condition or bank restriction. Keep contractual and transfer-compliance questions separate when assessing the response.",
    "تتبّع الدفع المتفق عليه من المدين العقدي عبر المسار المصرفي إلى المستفيد. حدّد هل العائق التزام متنازع عليه أو شرط خروج غير مكتمل أو قيد مصرفي. افصل مسائل العقد عن متطلبات التحويل عند تقييم الرد.",
    "investment or exit agreement, payment instructions, bank references, rejection reasons and evidence of completed conditions",
    "اتفاق الاستثمار أو الخروج وتعليمات الدفع والمراجع المصرفية وأسباب الرفض وإثبات استكمال الشروط"),
  brief(["Company formation and restructuring"],
    "Is the company being created or is an existing structure being changed?", "هل تُؤسس شركة جديدة أم يُغير هيكل شركة قائمة؟",
    "Identify the intended legal form, ownership, capital and management before comparing formation with restructuring. For an existing business, map contracts, employees, assets and liabilities affected by the change. A new registration should not obscure obligations that need consent, transfer or settlement.",
    "حدّد الشكل القانوني والملكية ورأس المال والإدارة قبل مقارنة التأسيس بإعادة الهيكلة. وفي النشاط القائم احصر العقود والعاملين والأصول والالتزامات المتأثرة. ينبغي ألا يحجب التسجيل الجديد التزامات تحتاج إلى موافقة أو نقل أو تسوية.",
    "current and proposed structure, constitutional documents, asset and liability schedules and required corporate approvals",
    "الهيكل الحالي والمقترح ووثائق التأسيس وجداول الأصول والالتزامات والموافقات المؤسسية اللازمة"),
  brief(["Shareholder and partner disputes"],
    "Which corporate right is disputed between shareholders?", "ما الحق المؤسسي المتنازع عليه بين الشركاء؟",
    "Identify the shareholding and the decision, account, distribution or access right challenged. Read the constitutional documents and shareholder agreement together. Separate the company's claim from a shareholder's personal claim, and record how the disputed decision was approved.",
    "حدّد الحصص والقرار أو الحساب أو التوزيع أو حق الاطلاع المعترض عليه. اقرأ وثائق التأسيس واتفاق المساهمين معاً. افصل مطالبة الشركة عن مطالبة المساهم الشخصية ووثّق كيفية اعتماد القرار المختلف عليه.",
    "share register, constitutional documents, shareholder agreement, meeting records and disputed accounts or resolutions",
    "سجل الحصص ووثائق التأسيس واتفاق المساهمين ومحاضر الاجتماعات والحسابات أو القرارات محل الخلاف"),
  brief(["Corporate governance"],
    "Who has authority to approve and implement the proposed company decision?", "من يملك اعتماد قرار الشركة المقترح وتنفيذه؟",
    "Map shareholder, board and manager powers against the constitutional documents and delegated authority. Check conflicts, voting and recordkeeping for the decision in question. A signature should be linked to proper authority, especially for borrowing, asset transfers and related-party dealings.",
    "طابق صلاحيات المساهمين والمجلس والمديرين بوثائق التأسيس والتفويضات. افحص التعارض والتصويت والتوثيق للقرار المعني. ينبغي ربط التوقيع بصلاحية صحيحة، خصوصاً في الاقتراض ونقل الأصول ومعاملات الأطراف المرتبطة.",
    "constitutional documents, authority matrix, board and shareholder resolutions, conflict disclosures and proposed transaction",
    "وثائق التأسيس ومصفوفة الصلاحيات وقرارات المجلس والمساهمين وإفصاحات التعارض والمعاملة المقترحة"),
  brief(["Director and manager liability"],
    "What conduct is alleged against the director or manager personally?", "ما السلوك المنسوب شخصياً إلى المدير أو عضو المجلس؟",
    "Identify the decision, authority, information available at the time and alleged loss. Distinguish company debt from personal guarantees, conflicts or alleged breach of duty. Holding office or signing for a company does not by itself explain the basis of personal liability.",
    "حدّد القرار والصلاحية والمعلومات المتاحة وقتها والخسارة المدعاة. افصل دين الشركة عن الكفالة الشخصية والتعارض أو الإخلال بالواجب. لا يفسر شغل المنصب أو التوقيع باسم الشركة وحده أساس المسؤولية الشخصية.",
    "appointment and authority records, decision papers, accounts, conflict disclosures, guarantees and the specific allegation",
    "مستندات التعيين والصلاحية وأوراق القرار والحسابات وإفصاحات التعارض والكفالات والادعاء المحدد"),
  brief(["Mergers, dissolution, and liquidation"],
    "Is the objective to combine businesses, end the company or wind up its affairs?", "هل الهدف دمج الأنشطة أم حل الشركة أم تصفية أعمالها؟",
    "Define the intended end state before selecting a corporate process. A merger, dissolution decision and liquidation perform different functions. Map assets, creditors, contracts and ownership interests so the chosen route deals with continuing obligations and required approvals.",
    "حدّد النتيجة المقصودة قبل اختيار الإجراء. للاندماج وقرار الحل والتصفية وظائف مختلفة. احصر الأصول والدائنين والعقود والحصص ليتناول المسار المختار الالتزامات المستمرة والموافقات اللازمة.",
    "corporate records, proposed transaction or dissolution plan, accounts, creditor list and asset schedule",
    "سجلات الشركة وخطة المعاملة أو الحل والحسابات وقائمة الدائنين وجدول الأصول"),
  brief(["Shareholder exit and buyout dispute"],
    "What mechanism and price basis govern the shareholder's exit?", "ما الآلية وأساس السعر اللذان يحكمان تخارج المساهم؟",
    "Read the exit, transfer, pre-emption and deadlock provisions with the proposed offer. Identify valuation date, funding and release of guarantees. An agreement to buy shares needs clarity on completion conditions and liabilities that may survive the transfer.",
    "اقرأ شروط الخروج ونقل الحصص والأولوية والجمود مع العرض المقترح. حدّد تاريخ التقييم والتمويل وفك الكفالات. يحتاج شراء الحصص إلى وضوح شروط الإتمام والالتزامات التي قد تبقى بعد النقل.",
    "shareholder agreement, transfer restrictions, offer, valuation, funding arrangements and personal guarantees",
    "اتفاق المساهمين وقيود النقل والعرض والتقييم وترتيبات التمويل والكفالات الشخصية"),
  brief(["Company dissolution and liquidation dispute"],
    "What is contested in the dissolution or liquidation process?", "ما محل الخلاف في حل الشركة أو تصفيتها؟",
    "Identify whether the dispute concerns the decision to dissolve, appointment of the liquidator, asset sales, creditor claims or final distribution. Keep company and shareholder funds separate. A proposed distribution requires the outstanding liabilities and authority to act to be established.",
    "حدّد هل الخلاف على قرار الحل أو تعيين المصفي أو بيع الأصول أو مطالبات الدائنين أو التوزيع النهائي. افصل أموال الشركة والمساهمين. يحتاج التوزيع المقترح إلى تحديد الالتزامات المتبقية وصلاحية التصرف.",
    "dissolution resolution, liquidator appointment, accounts, asset sales, creditor claims and distribution proposal",
    "قرار الحل وتعيين المصفي والحسابات ومبيعات الأصول ومطالبات الدائنين ومقترح التوزيع"),
  brief(["Mergers and acquisitions legal due diligence"],
    "Which legal findings could prevent or change the acquisition?", "ما نتائج الفحص القانوني التي قد تمنع الاستحواذ أو تغيره؟",
    "Test title to shares and assets, authority, licences, litigation, security and consent requirements against the transaction structure. Record missing evidence separately from verified risks. Translate material findings into completion conditions, warranties, price treatment or a decision not to proceed.",
    "افحص ملكية الحصص والأصول والصلاحية والتراخيص والنزاعات والضمانات ومتطلبات الموافقة وفق هيكل المعاملة. افصل الأدلة الناقصة عن المخاطر المثبتة. حوّل النتائج الجوهرية إلى شروط إتمام أو ضمانات أو معالجة سعرية أو قرار بعدم المضي.",
    "data-room records, ownership evidence, licences, material contracts, litigation and security schedules and draft acquisition terms",
    "مستندات غرفة البيانات وإثبات الملكية والتراخيص والعقود الجوهرية وجداول النزاعات والضمانات وشروط الاستحواذ المقترحة"),
  brief(["Minority shareholder oppression dispute"],
    "Which majority decision or practice is said to prejudice the minority?", "ما قرار الأغلبية أو ممارستها المدعى بإضرارها بالأقلية؟",
    "Identify the challenged decisions, voting record, access to information and effect on the minority's rights. Separate disagreement with business judgment from alleged exclusion, diversion or unequal treatment. The requested remedy should follow the specific conduct and applicable company framework.",
    "حدّد القرارات المعترض عليها والتصويت وإتاحة المعلومات وأثرها في حقوق الأقلية. افصل اختلاف الرأي التجاري عن الإقصاء أو تحويل المنافع أو المعاملة غير المتكافئة المدعاة. يرتبط الطلب بالسلوك المحدد وإطار الشركات المنطبق.",
    "shareholding and voting records, disputed resolutions, information requests, related-party transactions and financial effects",
    "سجلات الحصص والتصويت والقرارات محل الخلاف وطلبات المعلومات ومعاملات الأطراف المرتبطة والآثار المالية"),
  brief(["Company valuation and shareholder buyout dispute"],
    "Why do the proposed share valuations differ?", "لماذا تختلف التقييمات المقترحة للحصص؟",
    "Compare valuation date, method, financial inputs, debt and assumptions about control or marketability. Identify any contractual valuation mechanism. Legal review addresses the agreed process and disputed assumptions; financial valuation may require an appropriately qualified expert.",
    "قارن تاريخ التقييم ومنهجه ومدخلاته المالية والديون وافتراضات السيطرة أو قابلية التداول. حدّد آلية التقييم العقدية إن وجدت. تتناول المراجعة القانونية الإجراء والافتراضات المتنازع عليها، وقد يحتاج التقييم المالي إلى خبير مؤهل.",
    "valuation reports, shareholder agreement, financial statements, debt schedules and offers using the disputed figures",
    "تقارير التقييم واتفاق المساهمين والقوائم المالية وجداول الديون والعروض المستندة إلى الأرقام المختلفة"),
  brief(["Company registration and amendment dispute"],
    "Does the proposed registry amendment have valid corporate support?", "هل يستند تعديل سجل الشركة المقترح إلى قرار مؤسسي صحيح؟",
    "Identify the amendment, approving body, voting record and filing response. Compare the proposed entry with the resolution and constitutional documents. A rejected filing, an inaccurate entry and an invalid corporate decision should not be treated as the same problem.",
    "حدّد التعديل والجهة المعتمدة والتصويت ورد التسجيل. قارن القيد المقترح بالقرار ووثائق التأسيس. لا تُعامل المعاملة المرفوضة والقيد غير الدقيق والقرار المؤسسي غير الصحيح باعتبارها مشكلة واحدة.",
    "current company extract, proposed amendment, authorising resolutions, constitutional documents and registry response",
    "مستخرج الشركة الحالي والتعديل المقترح وقرارات التفويض ووثائق التأسيس ورد التسجيل"),
  brief(["Partner withdrawal and liquidation dispute"],
    "Does the partner seek a personal exit or liquidation of the business?", "هل يريد الشريك خروجه الشخصي أم تصفية النشاط؟",
    "Clarify whether the business is intended to continue and how the departing partner's interest would be settled. Separate capital, loans, profits and guarantees. Withdrawal terms should address valuation and ongoing liabilities rather than assume that notice ends every obligation.",
    "وضّح هل سيستمر النشاط وكيف ستُسوّى حصة الشريك المغادر. افصل رأس المال والقروض والأرباح والكفالات. ينبغي أن تعالج شروط الانسحاب التقييم والالتزامات المستمرة بدلاً من افتراض أن الإخطار ينهي كل التزام.",
    "partnership terms, withdrawal notice, capital and loan accounts, valuation material and creditor or guarantee records",
    "شروط الشراكة وإخطار الانسحاب وحسابات رأس المال والقروض ومواد التقييم وسجلات الدائنين أو الكفالات"),
  brief(["Company formation and registration problem"],
    "What is preventing the company application from being completed?", "ما الذي يمنع استكمال طلب تأسيس الشركة وتسجيلها؟",
    "Obtain the application status and exact deficiency or refusal. Check name, ownership, activity, documents and signing authority against the proposed legal form. Distinguish correcting the submitted file from changing the business structure or obtaining a separate sector approval.",
    "احصل على حالة الطلب والنقص أو الرفض المحدد. افحص الاسم والملكية والنشاط والمستندات وصلاحية التوقيع وفق الشكل القانوني المقترح. ميّز تصحيح الملف المقدم عن تغيير الهيكل أو استصدار موافقة قطاعية مستقلة.",
    "formation application, proposed constitutional documents, shareholder identity records, signing authority and deficiency notice",
    "طلب التأسيس ووثائق التأسيس المقترحة وهوية المساهمين وصلاحية التوقيع وإخطار النقص"),
];
