import { brief } from "./types.js";
export const CONTRACT_BRIEFS = [
  brief(["Contract drafting and review"],
    "What commercial instructions are needed to draft or review the contract?", "ما التعليمات التجارية اللازمة لصياغة العقد أو مراجعته؟",
    "Define the parties, promised work, price, acceptance, changes and exit conditions before selecting clauses. Identify what could go wrong and who should bear each risk. Review the complete agreement and schedules together so the wording matches the intended transaction.",
    "حدّد الأطراف والعمل والثمن والقبول والتغييرات وشروط الخروج قبل اختيار البنود. بيّن المخاطر المحتملة ومن يتحمل كل خطر. راجع الاتفاق وملاحقه معاً لتطابق الصياغة المعاملة المقصودة.",
    "draft agreement, scope and specifications, pricing terms, negotiation notes and intended delivery and acceptance process",
    "مسودة الاتفاق والنطاق والمواصفات وشروط الثمن وملاحظات التفاوض وآلية التسليم والقبول المقصودة"),
  brief(["Breach of contract"],
    "Which contractual obligation was breached and what loss followed?", "ما الالتزام العقدي الذي أُخل به وما الخسارة الناتجة؟",
    "Identify the exact promise, when performance was due, what occurred and the other party's explanation. Record notice and any opportunity to cure. Separate proving breach from establishing loss and selecting a remedy; not every failure supports the same response.",
    "حدّد التعهد بدقة وموعد تنفيذه وما حدث وتفسير الطرف الآخر. وثّق الإخطار وأي فرصة للتدارك. افصل إثبات الإخلال عن إثبات الخسارة واختيار المعالجة؛ فليست لكل مخالفة الاستجابة نفسها.",
    "signed contract, performance records, breach notices, replies, loss schedule and evidence of mitigation",
    "العقد الموقع وسجلات التنفيذ وإخطارات الإخلال والردود وجدول الخسارة وأدلة الحد منها"),
  brief(["Termination and cancellation"],
    "What must be checked before sending a contract termination notice?", "ما الذي يُراجع قبل إرسال إخطار إنهاء العقد؟",
    "Identify the termination ground, notice method, cure provisions and consequences for work, payments and property. Compare the proposed notice with the contract and actual breach. Wanting to exit a deal does not establish that unilateral termination is available without consequences.",
    "حدّد سبب الإنهاء وطريقة الإخطار وفرصة التدارك وآثار الإنهاء في العمل والمدفوعات والممتلكات. قارن الإخطار المقترح بالعقد والإخلال الفعلي. لا تثبت الرغبة في الخروج جواز الإنهاء المنفرد دون آثار.",
    "complete contract, relevant breach evidence, notice provisions, draft termination and outstanding obligations",
    "العقد كاملاً وأدلة الإخلال وشروط الإخطار ومسودة الإنهاء والالتزامات المتبقية"),
  brief(["Penalty and compensation clauses"],
    "How does the agreed compensation clause relate to the actual breach?", "كيف يرتبط شرط التعويض المتفق عليه بالإخلال الفعلي؟",
    "Check the event triggering the clause, calculation, cap and interaction with other remedies. Compare it with performance and loss evidence. A stated amount should not be assumed automatically payable or immune from review under the applicable law.",
    "راجع الواقعة المشغلة للشرط وطريقة الحساب والحد الأقصى وعلاقته بوسائل المعالجة الأخرى. قارنه بأدلة التنفيذ والخسارة. لا يُفترض أن المبلغ المذكور مستحق تلقائياً أو محصن من المراجعة وفق القانون المنطبق.",
    "compensation clause and full contract, breach chronology, calculation, loss records and notices invoking the clause",
    "شرط التعويض والعقد كاملاً وتسلسل الإخلال والحساب وسجلات الخسارة وإخطارات التمسك بالشرط"),
  brief(["Negotiation and enforcement"],
    "How can a negotiated contract solution be made clear enough to implement?", "كيف تصبح المعالجة العقدية المتفاوض عليها واضحة للتنفيذ؟",
    "Set out the revised obligations, due dates, acceptance evidence and consequences of non-performance. Identify whether the proposal amends the contract or settles existing claims. Keep the route for enforcing the agreement distinct from the route for proving the original dispute.",
    "حدّد الالتزامات المعدلة ومواعيدها وإثبات قبولها وأثر عدم التنفيذ. بيّن هل المقترح يعدل العقد أم يسوي مطالبات قائمة. افصل طريق تنفيذ الاتفاق عن طريق إثبات النزاع الأصلي.",
    "original contract, negotiation record, proposed amendment or settlement, authority to sign and performance schedule",
    "العقد الأصلي وسجل التفاوض والتعديل أو التسوية المقترحة وصلاحية التوقيع وجدول التنفيذ"),
  brief(["Supply contract non-delivery"],
    "Was delivery missed, refused or prevented by an outstanding condition?", "هل فات التسليم أم رُفض أم منعته شروط لم تُستكمل؟",
    "Match the order and delivery date with payment, shipping and acceptance conditions. Record partial shipments, revised promises and the supplier's explanation. Distinguish requesting delivery from cancellation, replacement procurement or compensation for documented loss.",
    "طابق الطلب وموعد التسليم بشروط السداد والشحن والقبول. وثّق الشحنات الجزئية والوعود المعدلة وتفسير المورد. ميّز طلب التسليم عن الفسخ أو الشراء البديل أو التعويض عن خسارة موثقة.",
    "order and supply terms, payment proof, shipping records, delivery promises and non-delivery correspondence",
    "الطلب وشروط التوريد وإثبات السداد وسجلات الشحن ووعود التسليم ومراسلات عدم التسليم"),
  brief(["Defective goods and non-conforming delivery"],
    "How do the delivered goods differ from the agreed specification?", "كيف تختلف البضاعة المسلمة عن المواصفة المتفق عليها؟",
    "Record the defect or discrepancy by item, quantity and delivery date. Compare inspection and acceptance records with the agreed specification and notice requirements. Preserve samples or photographs where appropriate and distinguish repair, replacement, rejection and price adjustment requests.",
    "وثّق العيب أو الاختلاف بحسب الصنف والكمية وتاريخ التسليم. قارن سجلات الفحص والقبول بالمواصفة وشروط الإخطار. احفظ العينات أو الصور عند ملاءمتها وميّز طلب الإصلاح والاستبدال والرفض وتعديل الثمن.",
    "specifications, delivery records, inspection results, photographs or retained samples and defect notifications",
    "المواصفات وسجلات التسليم ونتائج الفحص والصور أو العينات المحفوظة وإخطارات العيوب"),
  brief(["Service agreement breach"],
    "Was the service outcome promised or only defined work and effort?", "هل وُعد بنتيجة للخدمة أم بعمل وجهد محددين؟",
    "Compare the scope, milestones, acceptance criteria and responsibilities with what was delivered. Identify missing work, delays, rejected outputs and client dependencies. Dissatisfaction should be tied to a specific obligation rather than an expectation absent from the agreement.",
    "قارن النطاق والمراحل ومعايير القبول والمسؤوليات بما سُلّم. حدّد العمل الناقص والتأخير والمخرجات المرفوضة والمهام المعتمدة على العميل. اربط عدم الرضا بالتزام محدد بدلاً من توقع غير وارد في الاتفاق.",
    "service agreement, scope and milestones, delivered work, acceptance or rejection messages and change requests",
    "اتفاق الخدمة والنطاق والمراحل والعمل المسلم ورسائل القبول أو الرفض وطلبات التغيير"),
  brief(["Contract evidence and electronic messages"],
    "How should electronic messages be preserved as contract evidence?", "كيف أحفظ الرسائل الإلكترونية كدليل عقدي؟",
    "Keep the full conversation, dates, sender details and original files where available. Identify the offer, acceptance, changes and performance referred to. Screenshots can lose context; preserve the underlying records and explain how the participants relate to the contracting parties.",
    "احفظ المحادثة كاملة وتواريخها وبيانات المرسل والملفات الأصلية المتاحة. حدّد الإيجاب والقبول والتعديلات والتنفيذ المشار إليه. قد تفقد لقطات الشاشة السياق؛ فاحفظ السجلات الأصلية ووضّح صلة المشاركين بالأطراف المتعاقدة.",
    "complete message exports, attachments, signed versions, identity or authority context and related performance records",
    "تصدير الرسائل كاملاً والمرفقات والنسخ الموقعة وبيانات الهوية أو الصلاحية وسجلات التنفيذ المرتبطة"),
  brief(["Power-of-attorney drafting and authority dispute", "Power-of-attorney drafting and authority problem"],
    "What acts must the proposed power of attorney authorise?", "ما التصرفات التي يجب أن تجيزها الوكالة المقترحة؟",
    "List the intended acts, recipient authority, duration and any limits on delegation, receiving money or settlement. Check the principal's identity and capacity and where the document will be used. Broad wording may not meet the receiving body's requirements or the principal's intended limits.",
    "احصر التصرفات والجهة المستقبلة والمدة وقيود التفويض وقبض المال والتسوية. تحقّق من هوية الموكل وأهليته ومكان الاستعمال. قد لا تحقق الصياغة الواسعة متطلبات الجهة أو الحدود التي يقصدها الموكل.",
    "principal and agent details, intended transaction, recipient requirements, draft authority and any existing power of attorney",
    "بيانات الموكل والوكيل والمعاملة المقصودة ومتطلبات الجهة ومسودة الصلاحيات وأي وكالة قائمة"),
  brief(["Document attestation and contract authentication problem"],
    "What is the receiving authority asking to authenticate?", "ما الذي تطلب الجهة المستقبلة توثيقه أو تصديقه؟",
    "Obtain the written requirement and identify the document's issuing country, signature and intended use. Separate authentication of a signature or seal from confirmation of the contract's legal effect. A translation, notarisation and consular step are not automatically substitutes for one another.",
    "احصل على المتطلب المكتوب وحدّد دولة إصدار المستند وتوقيعه وغرض استعماله. افصل تصديق التوقيع أو الختم عن تأكيد أثر العقد القانوني. ليست الترجمة والتوثيق والإجراء القنصلي بدائل متطابقة تلقائياً.",
    "original document, issuing details, existing certifications, translation and written receiving-authority requirements",
    "المستند الأصلي وبيانات إصداره والتصديقات القائمة والترجمة ومتطلبات الجهة المستقبلة المكتوبة"),
  brief(["Legal notice and demand letter drafting"],
    "What should a legal demand letter clearly state?", "ما الذي ينبغي أن يوضحه الإنذار أو خطاب المطالبة؟",
    "Identify the sender's capacity, obligation relied on, relevant facts, amount or action requested and a justified response date. Check the contractual notice method and recipient. Keep assertions supportable and distinguish a settlement proposal from a formal notice required for a later step.",
    "حدّد صفة المرسل والالتزام والوقائع والمبلغ أو الإجراء المطلوب وموعد رد مبرراً. راجع طريقة الإخطار العقدية والمخاطب. اجعل الادعاءات قابلة للإثبات وميّز عرض التسوية عن الإنذار اللازم لخطوة لاحقة.",
    "contract and notice clause, chronology, supporting invoices or decisions, recipient details and proposed demand",
    "العقد وشرط الإخطار والتسلسل الزمني والفواتير أو القرارات المؤيدة وبيانات المخاطب والمطلب المقترح"),
  brief(["Power-of-attorney misuse, rejection or scope dispute"],
    "Did the agent act outside the authority or did the recipient reject the document?", "هل تجاوز الوكيل صلاحياته أم رفضت الجهة الوكالة؟",
    "Compare the disputed act with the complete authority, amendments and any revocation record. Identify what the recipient knew and the reason for rejection or alleged misuse. A document-format problem and an unauthorised transaction require different assessment.",
    "قارن التصرف المختلف عليه بالوكالة كاملة وتعديلاتها وأي سجل عزل. حدّد ما علمت به الجهة وسبب الرفض أو إساءة الاستعمال المدعاة. تحتاج مشكلة شكل المستند والتصرف غير المأذون به إلى تقييم مختلف.",
    "power of attorney, disputed transaction, rejection notice, amendments or revocation and communications with the recipient",
    "الوكالة والتصرف محل النزاع وإخطار الرفض والتعديلات أو العزل والمراسلات مع الجهة المستقبلة"),
  brief(["Document attestation and legalisation problem"],
    "Where in the document legalisation chain has the process stopped?", "أين تعثر مسار تصديق المستند للاستخدام الخارجي؟",
    "Identify the issuing and receiving countries, document type and existing certifications. Obtain the exact rejection or missing-step requirement. The route depends on the document and destination; do not purchase repeated translations or certifications without checking what the receiving body accepts.",
    "حدّد دولتي الإصدار والاستقبال ونوع المستند وتصديقاته القائمة. احصل على سبب الرفض أو الخطوة الناقصة بدقة. يتوقف المسار على المستند والوجهة؛ فلا تكرر الترجمات أو التصديقات دون التحقق مما تقبله الجهة المستقبلة.",
    "document and current certifications, destination requirements, rejection correspondence and any translation already obtained",
    "المستند وتصديقاته الحالية ومتطلبات الوجهة ومراسلات الرفض والترجمة الموجودة"),
  brief(["Consumer refund and purchase cancellation dispute"],
    "Is the refund requested for a defect, non-delivery or a change of mind?", "هل طلب الاسترداد بسبب عيب أم عدم تسليم أم تغيير الرأي؟",
    "Identify the reason for cancellation, purchase terms, delivery status and seller response. Separate statutory protections, contractual return promises and discretionary goodwill. A refund request should explain its factual basis rather than assume every purchase can be cancelled on the same terms.",
    "حدّد سبب الإلغاء وشروط الشراء وحالة التسليم ورد البائع. افصل الحماية القانونية عن وعد الإرجاع العقدي والتسهيل الاختياري. ينبغي أن يوضح طلب الاسترداد أساسه الواقعي بدلاً من افتراض إلغاء كل شراء بالشروط نفسها.",
    "order, receipt, advertised return terms, delivery or defect evidence and refund correspondence",
    "الطلب والإيصال وشروط الإرجاع المعلنة وإثبات التسليم أو العيب ومراسلات الاسترداد"),
  brief(["Defective product and consumer compensation claim"],
    "What harm did the product defect cause beyond the purchase price?", "ما الضرر الذي سببه عيب المنتج إضافة إلى ثمنه؟",
    "Record the product, defect, use instructions and incident. Separate repair or replacement from a claim for injury or damage to other property. Preserve the product where safe and keep loss evidence; a defect allegation alone does not establish every claimed loss.",
    "وثّق المنتج والعيب وتعليمات الاستعمال والواقعة. افصل الإصلاح أو الاستبدال عن المطالبة بإصابة أو تلف مال آخر. احفظ المنتج عندما يكون ذلك آمناً وأدلة الخسارة؛ فادعاء العيب لا يثبت كل ضرر مطلوب.",
    "receipt, product and batch details, instructions, defect photographs, incident records and evidence of additional loss",
    "الإيصال وبيانات المنتج والتشغيلة والتعليمات وصور العيب وسجلات الواقعة وإثبات الخسارة الإضافية"),
  brief(["Commercial contract dispute under Syrian law"],
    "What connects the commercial contract and dispute to Syrian law?", "ما صلة العقد والنزاع التجاريين بالقانون السوري؟",
    "Identify the parties, place of performance, governing-law and forum terms, and the obligation disputed. Compare the signed versions and actual transaction. A Syrian connection should be assessed alongside any foreign element rather than assumed to resolve jurisdiction or enforcement abroad.",
    "حدّد الأطراف ومكان التنفيذ وشروط القانون والاختصاص والالتزام المختلف عليه. قارن النسخ الموقعة بالمعاملة الفعلية. تُقيّم الصلة السورية مع أي عنصر أجنبي، ولا يُفترض أنها تحسم الاختصاص أو التنفيذ في الخارج.",
    "full contract, governing-law and dispute clauses, performance records, Syrian transaction connection and foreign-party details",
    "العقد كاملاً وشروط القانون والنزاع وسجلات التنفيذ والصلة السورية للمعاملة وبيانات الطرف الأجنبي"),
  brief(["Contract authentication and evidence problem"],
    "Is the dispute about the signature, document authenticity or contractual meaning?", "هل الخلاف على التوقيع أم أصالة المستند أم معنى العقد؟",
    "Identify what is denied: signing, authority, alteration, date or the interpretation of an accepted document. Preserve originals and explain how each version was obtained. Authentication questions and the meaning of a contract require different evidence and should be addressed separately.",
    "حدّد المنكر: التوقيع أو الصلاحية أو التعديل أو التاريخ أو تفسير مستند مقبول. احفظ الأصول وبيّن كيفية الحصول على كل نسخة. تتطلب أصالة المستند ومعنى العقد أدلة مختلفة وينبغي معالجتهما بصورة منفصلة.",
    "original and disputed versions, signature context, authority records, transmission history and any authentication report",
    "الأصل والنسخ المختلف عليها وسياق التوقيع ومستندات الصلاحية وسجل الإرسال وأي تقرير تحقق"),
];
