import { brief } from "./types.js";
export const CRIMINAL_BRIEFS = [
  brief(["Criminal complaints and defence"],
    "Are you making a complaint, responding to an allegation or already in proceedings?", "هل تقدم شكوى أم ترد على اتهام أم توجد إجراءات قائمة؟",
    "Identify your role, the alleged conduct, authority involved and any summons or restriction. Prepare a factual chronology and preserve relevant records without alteration. A complaint and a defence require different preparation; state the immediate decision or attendance date first.",
    "حدّد صفتك والسلوك المدعى به والجهة وأي استدعاء أو قيد. أعد تسلسلاً واقعياً واحفظ السجلات دون تغيير. تختلف مستلزمات الشكوى والدفاع؛ فاذكر أولاً القرار العاجل أو موعد الحضور.",
    "complaint or summons, case reference, factual chronology, relevant documents and any restriction or hearing notice",
    "الشكوى أو الاستدعاء ومرجع القضية وتسلسل الوقائع والمستندات ذات الصلة وأي إخطار بقيد أو جلسة"),
  brief(["Investigation and questioning"],
    "What should I clarify when asked to attend questioning?", "ما الذي أوضحه عند طلبي للحضور للاستجواب؟",
    "Identify the requesting authority, your stated capacity, attendance details and subject of the inquiry. Seek advice about the applicable procedure, representation and interpretation needs. Preserve the notice and existing records; do not guess facts or alter evidence to fill gaps in your recollection.",
    "حدّد الجهة الطالبة وصفتك المذكورة وتفاصيل الحضور وموضوع الاستفسار. اطلب المشورة بشأن الإجراء والتمثيل والحاجة إلى ترجمة. احفظ الإخطار والسجلات؛ ولا تخمّن الوقائع أو تغير الأدلة لسد فجوات التذكر.",
    "questioning notice, identification, case reference, relevant chronology and documents relating to the stated inquiry",
    "إخطار الاستجواب والهوية ومرجع القضية والتسلسل ذي الصلة والمستندات المرتبطة بموضوع التحقيق"),
  brief(["Arrest and detention concerns"],
    "What information is most useful when a person is detained?", "ما المعلومات الأكثر فائدة عند احتجاز شخص؟",
    "Identify the person, authority, known location, time of detention and any reference or order. State urgent medical, interpretation or contact needs. The immediate task is to establish the actual position and available legal assistance, not infer the outcome from an allegation.",
    "حدّد الشخص والجهة والمكان المعروف ووقت الاحتجاز وأي مرجع أو أمر. اذكر الاحتياجات الطبية أو اللغوية أو التواصلية العاجلة. الأولوية لمعرفة الوضع الفعلي والمساعدة القانونية المتاحة، لا استنتاج النتيجة من الاتهام.",
    "identity and case details, detention or summons records, known authority contact and relevant urgent-needs information",
    "بيانات الهوية والقضية وسجلات الاحتجاز أو الاستدعاء وبيانات الجهة المعروفة والاحتياجات العاجلة ذات الصلة"),
  brief(["Digital and documentary evidence"],
    "How can the source and integrity of the evidence be explained?", "كيف يُوضح مصدر الدليل وسلامته؟",
    "Identify who created or obtained each record, when and in what form. Preserve originals, full context and an account of handling. Distinguish what a document or device shows from assumptions about the person responsible; authenticity and attribution need separate attention.",
    "حدّد منشئ كل سجل أو من حصل عليه ووقته وشكله. احفظ الأصل والسياق الكامل وبيان التعامل معه. افصل ما يظهره المستند أو الجهاز عن الافتراضات حول المسؤول؛ فأصالة الدليل ونسبته تحتاجان إلى بحث منفصل.",
    "original documents or lawful copies, complete digital records, source information and a chronology of evidence handling",
    "المستندات الأصلية أو صورها المشروعة والسجلات الرقمية كاملة وبيانات المصدر وتسلسل التعامل مع الأدلة"),
  brief(["Trial and appeal preparation"],
    "Is the task preparing for trial or challenging an issued judgment?", "هل المطلوب الاستعداد للمحاكمة أم الطعن في حكم صادر؟",
    "For trial, organise the accusation, disputed facts and evidence. For appeal, identify the judgment, reasons, notification and specific alleged errors. The two stages require different work; a general disagreement with the case should be converted into precise issues for the current stage.",
    "للمحاكمة نظّم الاتهام والوقائع المتنازع عليها والأدلة. وللطعن حدّد الحكم وأسبابه وتبليغه والأخطاء المنسوبة إليه. تختلف متطلبات المرحلتين؛ فحوّل الخلاف العام إلى مسائل دقيقة تخص المرحلة الحالية.",
    "charge and defence papers, evidence list, hearing records and, for an appeal, the judgment and notification record",
    "أوراق الاتهام والدفاع وقائمة الأدلة ومحاضر الجلسات، وللطعن الحكم وإثبات تبليغه"),
  brief(["Police complaint defence"],
    "What allegation and procedural status appear in the police notice?", "ما الاتهام والوضع الإجرائي الواردان في إخطار الشرطة؟",
    "Obtain the notice or case reference and identify whether you are being asked for information, questioned about an allegation or referred onward. Prepare relevant facts and records for legal review. Do not treat an informal account of a complaint as a substitute for the actual notice.",
    "احصل على الإخطار أو المرجع وحدّد هل يُطلب منك تقديم معلومات أو تُسأل عن اتهام أو أُحيل الملف. جهّز الوقائع والسجلات للمراجعة. لا تستبدل الإخطار الفعلي برواية غير رسمية عن الشكوى.",
    "police notice, case reference, relevant communications, transaction or incident records and any subsequent referral",
    "إخطار الشرطة ومرجع القضية والمراسلات ذات الصلة وسجلات المعاملة أو الواقعة وأي إحالة لاحقة"),
  brief(["Travel-ban and detention concern"],
    "Is there a verified travel restriction, detention order or only an informal warning?", "هل يوجد قيد سفر أو أمر احتجاز مثبت أم تحذير غير رسمي؟",
    "Identify the actual decision, issuing body and case reference before making travel assumptions. Keep a travel restriction separate from detention and from any civil enforcement file. Urgent review should address the specific order, its status and the lawful route for clarification or challenge.",
    "حدّد القرار الفعلي والجهة ومرجع القضية قبل بناء افتراضات عن السفر. افصل قيد السفر عن الاحتجاز وعن أي تنفيذ مدني. تتناول المراجعة العاجلة الأمر المحدد وحالته والطريق القانوني للاستفسار أو الطعن.",
    "restriction or detention notice, identity and travel documents, case reference and authority correspondence",
    "إخطار قيد السفر أو الاحتجاز والهوية ووثائق السفر ومرجع القضية ومراسلات الجهة"),
  brief(["Online defamation complaint"],
    "Which online statement is complained of and how was it published?", "ما العبارة الإلكترونية محل الشكوى وكيف نُشرت؟",
    "Preserve the exact words, full context, publication link, date and audience evidence. Distinguish alleged factual statements from opinion and identify the person or organisation affected. Removal, criminal complaint and a damages claim are separate objectives requiring the applicable framework to be checked.",
    "احفظ الكلمات الدقيقة والسياق والرابط والتاريخ ودليل الجمهور. ميّز الوقائع المدعاة عن الرأي وحدّد المتضرر. الإزالة والشكوى الجزائية ومطالبة التعويض أهداف مستقلة تستلزم فحص الإطار المنطبق.",
    "complete publication and URL, dated screenshots, context, attribution evidence and records of the alleged harm",
    "المنشور كاملاً ورابطه ولقطات مؤرخة وسياقه وأدلة نسبته وسجلات الضرر المدعى به"),
  brief(["Cybercrime accusation and defence"],
    "What digital act is alleged and how is it attributed to the accused?", "ما الفعل الرقمي المنسوب وكيف رُبط بالمتهم؟",
    "Identify the alleged access, publication, transfer or other conduct and the devices or accounts involved. Preserve available records and the procedural notices. Account ownership, device access and responsibility for a particular act are different questions; avoid assuming attribution from one identifier alone.",
    "حدّد الدخول أو النشر أو التحويل أو السلوك المنسوب والأجهزة أو الحسابات المعنية. احفظ السجلات والإخطارات. ملكية الحساب والوصول للجهاز والمسؤولية عن فعل محدد مسائل مختلفة؛ فلا تفترض النسبة من معرّف واحد فقط.",
    "accusation or summons, relevant account and device records, transaction references and evidence-handling information",
    "الاتهام أو الاستدعاء وسجلات الحساب والجهاز ذات الصلة ومراجع المعاملات وبيانات التعامل مع الأدلة"),
  brief(["Fraud and financial-crime accusation"],
    "Which representation, transaction or money flow is alleged to be criminal?", "ما البيان أو المعاملة أو حركة المال المدعى بأنها تشكل جريمة؟",
    "Map the alleged statement, reliance, payment and use of funds against the available records. Identify each participant's role and authority. A failed investment or unpaid contract is not a complete description of an alleged offence; the accusation needs to be examined element by element.",
    "اربط البيان المدعى به والاعتماد عليه والدفع واستعمال المال بالسجلات. حدّد دور كل مشارك وصلاحياته. لا يشكل فشل الاستثمار أو العقد غير المدفوع وصفاً مكتملاً لاتهام جزائي؛ بل يُفحص الاتهام بعناصره.",
    "complaint, contracts, statements made, bank and transaction records, authority documents and a chronology of the dealings",
    "الشكوى والعقود والبيانات المقدمة والسجلات المصرفية والمعاملات ومستندات الصلاحية وتسلسل التعامل"),
  brief(["Forgery and false-document accusation"],
    "What is alleged to be false in the disputed document?", "ما الجزء المدعى بتزويره في المستند؟",
    "Identify the signature, text, date, seal or use said to be false and preserve the original document and its source. Separate creating, altering and using a document. A disputed signature or inconsistent copy requires evidence review rather than assumptions about who was responsible.",
    "حدّد التوقيع أو النص أو التاريخ أو الختم أو الاستعمال المنسوب إليه التزوير واحفظ الأصل ومصدره. افصل إنشاء المستند وتعديله واستعماله. يحتاج التوقيع المختلف عليه أو النسخة المتعارضة إلى مراجعة دليل، لا افتراض المسؤول.",
    "original and disputed copies, transmission records, signature or seal context and any expert examination",
    "الأصل والنسخ المتنازع عليها وسجل تداولها وسياق التوقيع أو الختم وأي فحص خبير"),
  brief(["Breach-of-trust complaint or defence"],
    "What property was entrusted and what use was authorised?", "ما المال المسلم على سبيل الأمانة وما الاستعمال المأذون به؟",
    "Identify how the money or property was received, the instructions attached to it and the alleged unauthorised act. Reconcile returns, payments and explanations. A custody or agency relationship, an ordinary debt and a disputed investment may need different legal analysis.",
    "حدّد كيفية تسلم المال أو الشيء والتعليمات المرتبطة به والتصرف غير المأذون المدعى به. طابق ما رُد والمدفوعات والتفسيرات. قد يختلف تحليل الحفظ أو الوكالة عن الدين العادي أو الاستثمار المتنازع عليه.",
    "entrustment or agency agreement, transfer and receipt records, instructions, return demands and account reconciliation",
    "اتفاق الأمانة أو الوكالة وسجلات التحويل والاستلام والتعليمات ومطالبات الرد ومطابقة الحساب"),
  brief(["Public Prosecution investigation and questioning"],
    "What stage and allegation appear in the prosecution papers?", "ما المرحلة والاتهام الواردان في أوراق النيابة؟",
    "Identify the prosecution reference, capacity in which attendance is required and any prior police referral or decision. Prepare a chronology and relevant documents for advice on the current procedure. Representation, interpretation and responses should be considered before relying on informal descriptions of the file.",
    "حدّد مرجع النيابة وصفة الحضور وأي إحالة من الشرطة أو قرار سابق. جهّز تسلسلاً ومستندات للمشورة بشأن الإجراء الحالي. تُبحث المساعدة القانونية والترجمة والردود قبل الاعتماد على أوصاف غير رسمية للملف.",
    "prosecution summons, referral papers, prior statements, relevant evidence and any detention or attendance decision",
    "استدعاء النيابة وأوراق الإحالة والأقوال السابقة والأدلة ذات الصلة وأي قرار احتجاز أو حضور"),
  brief(["Criminal compensation and restitution claim"],
    "Is the request for return of property or compensation for additional loss?", "هل المطلوب رد المال أم التعويض عن خسارة إضافية؟",
    "Identify the property or amount sought, the alleged offence and the link to each loss. Record anything already recovered. Restitution, compensation and the criminal outcome are distinct; the available claim route and evidence must be checked for the case's current stage.",
    "حدّد المال أو المبلغ المطلوب والجريمة المدعاة والصلة بكل خسارة. وثّق ما استُرد بالفعل. الرد والتعويض والنتيجة الجزائية أمور متميزة؛ ويُفحص طريق المطالبة ودليلها وفق مرحلة القضية.",
    "criminal case papers, ownership and payment evidence, recovery records and a supported schedule of additional loss",
    "أوراق القضية الجزائية وإثبات الملكية والدفع وسجلات الاسترداد وجدول الخسارة الإضافية المؤيد"),
  brief(["Criminal complaint before Syrian authorities"],
    "What facts and Syrian connection should the complaint identify?", "ما الوقائع والصلة السورية التي ينبغي أن تحددها الشكوى؟",
    "State the alleged act, date, location, participants and evidence, distinguishing firsthand knowledge from inference. Identify the authority contacted and any related file. Present supportable facts and the requested action without treating an allegation as an established conviction.",
    "بيّن الفعل والتاريخ والمكان والمشاركين والأدلة المتاحة مع فصل العلم المباشر عن الاستنتاج. حدّد الجهة التي سبق التواصل معها والملفات المرتبطة. تعرض الشكوى وقائع قابلة للإثبات وطلباً محدداً دون اعتبار الاتهام إدانة ثابتة.",
    "factual chronology, identity and contact details relevant to the complaint, supporting records and prior complaint references",
    "تسلسل الوقائع وبيانات الهوية والتواصل المرتبطة بالشكوى والمستندات المؤيدة ومراجع الشكاوى السابقة"),
  brief(["Criminal case settlement and compensation claim"],
    "What does the proposed settlement resolve in the criminal case?", "ما الذي تحسمه التسوية المقترحة في القضية الجزائية؟",
    "Identify the private claim, compensation, property return and wording of any withdrawal or release. Check the effect on the particular proceedings separately. A private agreement should not be assumed to end every public-prosecution issue or erase an existing order.",
    "حدّد الحق الشخصي والتعويض ورد المال وصياغة التنازل أو المخالصة. افحص أثرها في الإجراءات المعينة بصورة مستقلة. لا يُفترض أن الاتفاق الخاص ينهي كل مسألة تخص الدعوى العامة أو يلغي أمراً قائماً.",
    "case status, proposed settlement and release, compensation calculation, proof of payment and existing orders",
    "حالة القضية والتسوية والمخالصة المقترحتان وحساب التعويض وإثبات السداد والأوامر القائمة"),
  brief(["Fraud and breach-of-trust accusation"],
    "Does the allegation concern obtaining property or misusing entrusted property?", "هل الاتهام على الحصول على المال أم إساءة استعمال مال مؤتمن عليه؟",
    "Identify how the property was obtained, what was represented or authorised and the later conduct challenged. Fraud and breach-of-trust allegations may involve different elements. Build a transaction chronology and separate the accused person's role from the actions of other participants.",
    "حدّد كيفية الحصول على المال والبيانات أو الصلاحيات المقدمة والسلوك اللاحق المعترض عليه. قد تختلف عناصر الاحتيال وخيانة الأمانة. أعد تسلسل المعاملة وافصل دور الشخص المتهم عن تصرفات المشاركين الآخرين.",
    "complaint or charge, transaction agreement, representations, entrustment instructions and payment or custody records",
    "الشكوى أو الاتهام واتفاق المعاملة والبيانات المقدمة وتعليمات الأمانة وسجلات السداد أو الحفظ"),
  brief(["Investigation rights"],
    "What procedural assistance is needed during the investigation?", "ما المساعدة الإجرائية المطلوبة أثناء التحقيق؟",
    "Identify your role, the investigating authority and any questioning or detention decision. Raise representation, language, medical or document-access needs for assessment under the applicable procedure. Keep a record of requests and responses rather than assume the same rules apply at every stage.",
    "حدّد صفتك وجهة التحقيق وأي قرار استجواب أو احتجاز. اطرح احتياجات التمثيل واللغة والعلاج والاطلاع لتقييمها وفق الإجراء المنطبق. وثّق الطلبات والردود بدلاً من افتراض تطبيق القواعد نفسها في كل مرحلة.",
    "investigation notice, case reference, procedural decisions and records of requests for assistance or access",
    "إخطار التحقيق ومرجع القضية والقرارات الإجرائية وسجلات طلبات المساعدة أو الاطلاع"),
  brief(["Arrest and detention procedure"],
    "Which detention decision and review stage are involved?", "ما قرار الاحتجاز ومرحلة مراجعته المعنيان؟",
    "Record the arrest, subsequent orders, issuing bodies and dates, including any renewal or transfer. Identify the current legal basis and available review question. The procedural history matters because an initial arrest, continued detention and post-judgment custody are not the same stage.",
    "وثّق التوقيف والأوامر اللاحقة وجهاتها وتواريخها بما فيها التجديد أو النقل. حدّد الأساس الحالي ومسألة المراجعة المتاحة. يهم التسلسل لأن التوقيف الأول واستمرار الاحتجاز والحبس بعد الحكم مراحل مختلفة.",
    "arrest and detention orders, renewal or transfer records, case status and prior review applications",
    "أوامر التوقيف والاحتجاز وسجلات التجديد أو النقل وحالة القضية وطلبات المراجعة السابقة"),
  brief(["Evidence challenges"],
    "Is the concern about how evidence was obtained, its reliability or its meaning?", "هل القلق على طريقة تحصيل الدليل أم موثوقيته أم معناه؟",
    "Identify the specific item and the claimed defect in collection, handling, authenticity or interpretation. Preserve the context and supporting records. Different objections need different grounds; a disagreement with the conclusion drawn from evidence is not necessarily an objection to admissibility.",
    "حدّد الدليل والخلل المدعى في جمعه أو التعامل معه أو أصالته أو تفسيره. احفظ السياق والسجلات المؤيدة. تختلف أسباب الاعتراضات؛ فعدم الموافقة على الاستنتاج لا يعني بالضرورة الاعتراض على قبول الدليل.",
    "disputed evidence, collection and handling records, source material, expert reports and the proposed objection",
    "الدليل المتنازع عليه وسجلات جمعه وتداوله ومواده الأصلية وتقارير الخبرة والاعتراض المقترح"),
  brief(["Trial procedure"],
    "What needs to be prepared for the next criminal hearing?", "ما الذي يجب تجهيزه للجلسة الجزائية المقبلة؟",
    "Identify the hearing's purpose, the accusation, pending applications and evidence to be addressed. Organise the defence issues and any witnesses or documents relevant to that stage. Keep procedural requests separate from arguments about the alleged conduct and the final outcome.",
    "حدّد غرض الجلسة والاتهام والطلبات القائمة والأدلة المطروحة. نظّم مسائل الدفاع والشهود أو المستندات المرتبطة بالمرحلة. افصل الطلبات الإجرائية عن الحجج المتعلقة بالسلوك المنسوب والنتيجة النهائية.",
    "hearing notice, charge, previous minutes, defence submissions, evidence list and pending applications",
    "إخطار الجلسة والاتهام والمحاضر السابقة ومذكرات الدفاع وقائمة الأدلة والطلبات القائمة"),
  brief(["Appeals and post-judgment remedies"],
    "Which part of the criminal judgment or subsequent decision is challenged?", "أي جزء من الحكم الجزائي أو القرار اللاحق محل الطعن؟",
    "Obtain the full judgment and notification, identify finality and any previous challenge, and state the alleged error. Appeal, review of a later execution decision and exceptional remedies may have different grounds. Match the proposed request to the actual procedural position.",
    "احصل على الحكم كاملاً وتبليغه وحدّد نهائيته والطعون السابقة والخطأ المدعى به. قد تختلف أسباب الطعن ومراجعة قرار تنفيذ لاحق والطرق الاستثنائية. طابق الطلب المقترح بالوضع الإجرائي الفعلي.",
    "judgment and reasons, notification, appeal history, later decisions and evidence relating to the asserted grounds",
    "الحكم وأسبابه وتبليغه وسجل الطعون والقرارات اللاحقة والأدلة المتعلقة بالأسباب المثارة"),
  brief(["Release and detention application"],
    "What facts support the requested review of detention?", "ما الوقائع المؤيدة لطلب مراجعة الاحتجاز؟",
    "Identify the current order, case stage, previous applications and any new relevant circumstances. State the precise request and supporting documents. Release conditions and the authority able to decide must be checked for the case; no outcome should be promised from a general example.",
    "حدّد الأمر الحالي ومرحلة القضية والطلبات السابقة والظروف الجديدة ذات الصلة. بيّن الطلب ومستنداته. تُفحص شروط إخلاء السبيل والجهة صاحبة القرار بحسب الملف؛ ولا تُضمن نتيجة من مثال عام.",
    "current detention order, prior decisions, case status and documents supporting the particular release grounds",
    "أمر الاحتجاز الحالي والقرارات السابقة وحالة القضية والمستندات المؤيدة لأسباب إخلاء السبيل المحددة"),
  brief(["Evidence challenge in criminal case"],
    "How does the disputed evidence relate to the alleged offence?", "كيف يرتبط الدليل المتنازع عليه بالاتهام؟",
    "Map the evidence to the factual proposition it is used to prove and identify the precise objection. Compare the original material, expert interpretation and other records. The response should explain why the alleged defect matters to the accusation rather than challenge the evidence in abstract terms.",
    "اربط الدليل بالواقعة المراد إثباتها وحدّد الاعتراض بدقة. قارن المادة الأصلية بتفسير الخبير والسجلات الأخرى. ينبغي أن يشرح الرد أثر الخلل المدعى به في الاتهام، لا الاعتراض على الدليل بعبارات مجردة.",
    "charge particulars, disputed exhibit, original source, expert interpretation and contradictory or contextual records",
    "تفاصيل الاتهام والمبرز المتنازع عليه ومصدره الأصلي وتفسير الخبير والسجلات المناقضة أو المكملة للسياق"),
  brief(["Criminal appeal deadline"],
    "Which event starts the time for the proposed criminal appeal?", "ما الواقعة التي يبدأ منها ميعاد الطعن الجزائي المقترح؟",
    "Record the judgment date, attendance, notification and any later decision or filing. Identify the type of judgment and challenge. Do not calculate the deadline from a remembered date alone; the triggering event, permitted route and filing requirements must be checked promptly.",
    "سجّل تاريخ الحكم والحضور والتبليغ وأي قرار أو قيد لاحق. حدّد نوع الحكم والطعن. لا تحسب الميعاد من تاريخ متذكر وحده؛ بل تحقّق سريعاً من واقعة بدء المدة وطريق الطعن ومتطلبات تقديمه.",
    "judgment, hearing and attendance record, service evidence, previous filings and any deadline notice",
    "الحكم ومحضر الجلسة والحضور وإثبات التبليغ والطلبات السابقة وأي إخطار بالميعاد"),
  brief(["Arrest, detention and release application in Syria"],
    "What is the current Syrian detention position and requested step?", "ما وضع الاحتجاز الحالي في سوريا والخطوة المطلوبة؟",
    "Identify the responsible authority, current order, case reference and known location. Record prior applications and urgent personal needs. The review should establish the actual procedural basis and available request in this file rather than rely on an assumed timetable or outcome.",
    "حدّد الجهة المسؤولة والأمر الحالي ومرجع القضية والمكان المعروف. وثّق الطلبات السابقة والاحتياجات الشخصية العاجلة. تستهدف المراجعة الأساس الإجرائي الفعلي والطلب المتاح في الملف، لا جدولاً أو نتيجة مفترضين.",
    "identity, Syrian case reference, available detention decisions, prior release requests and urgent-needs records",
    "الهوية ومرجع القضية السورية وقرارات الاحتجاز المتاحة وطلبات إخلاء السبيل السابقة وسجلات الاحتياجات العاجلة"),
  brief(["Criminal appeal and evidence objection in Syria"],
    "How does the evidence objection support the proposed Syrian appeal?", "كيف يؤيد الاعتراض على الدليل الطعن الجزائي المقترح في سوريا؟",
    "Identify the judgment's reasoning, the evidence relied on and the specific error alleged. Check when the point was raised and the current appeal stage. Preserve the complete record; a new explanation or document must be assessed within the permitted scope of the challenge.",
    "حدّد تعليل الحكم والدليل المعتمد والخطأ المدعى به. افحص وقت إثارة المسألة ومرحلة الطعن. احفظ الملف كاملاً؛ ويُقيّم أي تفسير أو مستند جديد ضمن النطاق المسموح للطعن.",
    "Syrian judgment and notification, hearing record, challenged evidence, prior objection and proposed appeal grounds",
    "الحكم السوري وتبليغه ومحاضر الجلسات والدليل المعترض عليه والاعتراض السابق وأسباب الطعن المقترحة"),
];
