import { brief } from "./types.js";

export const EMPLOYMENT_BRIEFS = [
  brief(["Changing employer and employment-record dispute"],
    "What needs resolving when changing employer in a Syria-related file?", "ما الذي يلزم حسمه عند تغيير صاحب العمل في ملف متعلق بسوريا؟",
    "Separate ending the old contract, starting the new job and correcting work records. Identify the employer, workplace and responsible authority. Gulf sponsorship-transfer procedures do not automatically govern Syrian employment; assess foreign permits under their issuing country's rules.",
    "افصل إنهاء العقد السابق عن بدء العلاقة الجديدة وتصحيح سجل العمل أو الترخيص. حدّد صاحب العمل ومكانه وصفة العامل والجهة المسؤولة عن السجل الفعلي. لا يُفترض أن إجراء نقل الكفالة في دولة خليجية يحكم علاقة عمل سورية؛ وتُراجع التصاريح الأجنبية وفق قواعد دولة إصدارها.",
    "old and proposed contracts, termination correspondence, employment or permit record, authority notice and work location",
    "العقد السابق والمقترح ومراسلات الإنهاء وسجل العمل أو الترخيص وإخطار الجهة ومكان العمل"),
  brief(["Travel and entry restrictions affecting employment"],
    "Which travel or entry decision is preventing work?", "ما قرار السفر أو الدخول الذي يمنع العمل؟",
    "Identify the restriction's issuing country, authority, reason and duration. Distinguish judicial travel bans, immigration decisions and employer demands. Establish the competent state and employment law; a Syria-related file does not itself imply an exit-and-re-entry visa procedure.",
    "احصل على القيد الفعلي وحدّد دولة إصداره وجهته وسببه ومدته. ميّز منع السفر القضائي عن قرار الهجرة وطلب صاحب العمل التعاقدي. حدّد الدولة المختصة بالدخول أو المغادرة والقانون الذي يحكم العمل قبل اختيار مسار المراجعة. لا يعني ارتباط الملف بسوريا وجود إجراء لتأشيرة خروج وعودة.",
    "restriction or refusal, passport and status records, employment contract, notification and required travel dates",
    "قرار القيد أو الرفض وجواز السفر وسجلات الوضع القانوني وعقد العمل والتبليغ ومواعيد السفر المطلوبة"),
  brief(["Wrongful termination", "Wrongful termination and labour complaint"],
    "What makes the reason and date of termination important?", "لماذا يهم سبب إنهاء العمل وتاريخه؟",
    "Compare the employer's stated reason with the contract, warnings and sequence of events. Record notice, the last working day and payments offered. A dismissal dispute needs separate assessment of the termination decision and each unpaid entitlement.",
    "قارن السبب الذي ذكره صاحب العمل بالعقد والإنذارات وتسلسل الوقائع. سجّل الإخطار وآخر يوم عمل والمبالغ المعروضة. يحتاج نزاع الفصل إلى تقييم منفصل لقرار الإنهاء ولكل مستحق غير مدفوع.",
    "contract, termination notice, warnings, performance records, complaint correspondence and final-pay breakdown",
    "العقد وإخطار الإنهاء والإنذارات وسجلات الأداء ومراسلات الشكوى وتفصيل الدفعة النهائية"),
  brief(["Employment contract review"],
    "Which employment terms should I clarify before signing?", "ما شروط العمل التي أوضحها قبل التوقيع؟",
    "Compare the offer and contract on role, pay components, workplace, probation, notice, working time and restrictive clauses. Identify differences and missing promises before signing. A familiar job title does not establish that every term matches the proposed arrangement.",
    "قارن العرض والعقد من حيث الوظيفة وعناصر الأجر ومكان العمل والتجربة والإخطار وساعات العمل والقيود. حدّد الاختلافات والوعود غير المدرجة قبل التوقيع. لا يعني وضوح المسمى الوظيفي أن كل بند يطابق الترتيب المقترح.",
    "job offer, full draft contract, pay schedule, policies incorporated by reference and written recruitment promises",
    "عرض العمل ومسودة العقد كاملة وجدول الأجر والسياسات المحال إليها ووعود التوظيف المكتوبة"),
  brief(["End-of-service entitlements", "End-of-service benefits and final-settlement dispute"],
    "How can I check an end-of-service calculation?", "كيف أراجع حساب مستحقات نهاية الخدمة؟",
    "Identify service dates, the applicable pay basis, unpaid leave or interruptions, the reason employment ended and sums already received. Separate end-of-service benefits from salary, leave and other items. Do not apply a calculator without confirming its jurisdiction and assumptions.",
    "حدّد تواريخ الخدمة وأساس الأجر المنطبق والإجازات غير المدفوعة أو الانقطاعات وسبب انتهاء العمل وما قُبض. افصل نهاية الخدمة عن الأجر والإجازة والبنود الأخرى. لا تستخدم حاسبة قبل التأكد من اختصاصها وافتراضاتها.",
    "employment dates and contract, wage history, leave record, termination or resignation papers and employer's calculation",
    "تواريخ العمل والعقد وسجل الأجر والإجازات وأوراق الإنهاء أو الاستقالة وحساب صاحب العمل"),
  brief(["Workplace and disciplinary disputes"],
    "What decision is being challenged in a workplace dispute?", "ما القرار المعترض عليه في النزاع الوظيفي؟",
    "Identify whether the issue is a warning, suspension, transfer, pay deduction or another workplace decision. Keep the allegation separate from the finding and sanction. A response should address the stated facts, relevant policy and opportunity given to explain.",
    "حدّد هل الخلاف على إنذار أو إيقاف أو نقل أو حسم من الأجر أو قرار آخر. افصل الاتهام عن النتيجة والجزاء. ينبغي أن يتناول الرد الوقائع المذكورة والسياسة ذات الصلة والفرصة المتاحة لتقديم الإيضاح.",
    "decision or warning, workplace policy, investigation correspondence, attendance records and the employee's written response",
    "القرار أو الإنذار والسياسة الوظيفية ومراسلات التحقيق وسجلات الحضور ورد العامل المكتوب"),
  brief(["Resignation because of unpaid wages"],
    "What should I consider before resigning over unpaid wages?", "ما الذي أبحثه قبل الاستقالة بسبب تأخر الأجور؟",
    "Document the unpaid periods and previous demands, then assess notice, the proposed resignation wording and its consequences before leaving. Wage arrears and the way employment ends are separate issues; non-payment should not be assumed to remove every procedural requirement.",
    "وثّق فترات الأجر غير المدفوعة والمطالبات السابقة، ثم قيّم الإخطار وصياغة الاستقالة المقترحة وآثارها قبل المغادرة. متأخرات الأجر وطريقة انتهاء العمل مسألتان منفصلتان؛ فلا يُفترض أن عدم الدفع يلغي كل متطلب إجرائي.",
    "contract, wage-arrears schedule, payment demands, employer replies, proposed resignation and any complaint reference",
    "العقد وجدول الأجور المتأخرة ومطالبات الدفع وردود صاحب العمل ومسودة الاستقالة ومرجع الشكوى إن وجد"),
  brief(["Experience certificate and service-transfer dispute", "Experience certificate and work-permit dispute"],
    "Is the problem the service certificate or the ability to start another job?", "هل المشكلة في شهادة الخبرة أم في إمكانية بدء عمل آخر؟",
    "Identify the certificate requested, any inaccurate service dates and the employer's response. Keep that request separate from work-permit or transfer approval. A certificate of past employment and authorisation for a new role serve different purposes.",
    "حدّد الشهادة المطلوبة وأي تواريخ خدمة غير صحيحة ورد صاحب العمل. افصل الطلب عن الموافقة على تصريح العمل أو النقل. شهادة العمل السابق والترخيص بوظيفة جديدة لهما غرضان مختلفان.",
    "certificate request, employment and exit records, employer response and the separate permit or transfer notice",
    "طلب الشهادة وسجلات العمل وانتهائه ورد صاحب العمل وإخطار التصريح أو النقل المستقل"),
  brief(["Sponsorship transfer dispute", "Sponsorship and work-permit transfer dispute"],
    "Which part of the employment transfer has been refused?", "أي جزء من نقل العمل رُفض؟",
    "Identify the current employment status, proposed employer, application stage and written reason for refusal. Distinguish employer disagreement from an authority's restriction or a missing record. Do not assume an accepted job offer completes the transfer or work authorisation.",
    "حدّد الوضع الوظيفي الحالي وصاحب العمل المقترح ومرحلة الطلب وسبب الرفض المكتوب. ميّز اعتراض صاحب العمل عن قيد تفرضه الجهة أو سجل ناقص. لا تفترض أن قبول عرض العمل يكمل النقل أو تصريح العمل.",
    "current and proposed contracts, permit details, transfer application, refusal notice and relevant employment-status records",
    "العقدان الحالي والمقترح وبيانات التصريح وطلب النقل وإخطار الرفض وسجلات الوضع الوظيفي ذات الصلة"),
  brief(["Work injury and compensation claim"],
    "What connects the injury to the work performed?", "ما الذي يربط الإصابة بالعمل المنجز؟",
    "Record where the incident occurred, the task being performed, who was notified and the treatment received. Distinguish workplace reporting, insurance or social-insurance benefits and any separate liability claim. Preserve the incident evidence without delaying necessary treatment.",
    "سجّل مكان الواقعة والمهمة المنفذة ومن أُبلغ والعلاج المتلقى. افصل الإبلاغ الوظيفي ومنافع التأمين أو التأمين الاجتماعي عن مطالبة المسؤولية المستقلة. احفظ أدلة الواقعة دون تأخير العلاج اللازم.",
    "incident report, duty roster, witness details, medical records, employer notification and insurance or benefit correspondence",
    "محضر الواقعة وجدول المهام وبيانات الشهود والسجلات الطبية وإبلاغ صاحب العمل ومراسلات التأمين أو المنافع"),
  brief(["Disciplinary warning and workplace investigation"],
    "How should I respond to an investigation or warning?", "كيف أرد على تحقيق وظيفي أو إنذار؟",
    "Ask which allegation and policy are involved and note the response date. Prepare a factual chronology and identify records or witnesses that address the allegation. Preserve the original warning and response; an investigation notice should not be confused with a final finding.",
    "حدّد الاتهام والسياسة المعنية وميعاد الرد. أعد تسلسلاً واقعياً وبيّن السجلات أو الشهود الذين يتناولون الاتهام. احفظ أصل الإنذار والرد؛ ولا تخلط إخطار التحقيق بنتيجة نهائية.",
    "investigation invitation, allegation details, applicable policy, relevant messages and records supporting the response",
    "دعوة التحقيق وتفاصيل الاتهام والسياسة المنطبقة والرسائل ذات الصلة والمستندات المؤيدة للرد"),
  brief(["Workplace discrimination and harassment complaint"],
    "How can I describe a workplace complaint clearly and safely?", "كيف أصف شكوى التمييز أو التحرش بوضوح وأمان؟",
    "Record specific incidents, dates, people involved and the effect on work. Separate what you witnessed from what others reported, and identify prior complaints or retaliation concerns. Keep relevant evidence securely; avoid circulating private material beyond what the complaint requires.",
    "وثّق وقائع محددة وتواريخها والأشخاص المعنيين وأثرها في العمل. افصل ما شاهدته عما نقله الآخرون وحدّد الشكاوى السابقة أو مخاوف الانتقام. احفظ الأدلة بأمان وتجنب تداول مواد خاصة تتجاوز حاجة الشكوى.",
    "dated incident account, relevant messages, witness details, workplace policy and prior complaint or HR responses",
    "سرد مؤرخ للوقائع والرسائل ذات الصلة وبيانات الشهود والسياسة الوظيفية والشكاوى السابقة أو ردود الموارد البشرية"),
  brief(["Commission and bonus payment dispute"],
    "What triggers entitlement to the disputed commission or bonus?", "ما الشرط الذي يربط به استحقاق العمولة أو المكافأة؟",
    "Read the scheme's trigger: a signed sale, collected payment, target achievement or discretionary approval. Match each claimed amount to the relevant period and supporting transaction. Distinguish a promised formula from a discretionary award and record any change to the scheme.",
    "اقرأ شرط الاستحقاق: بيع موقع أو مبلغ محصل أو هدف محقق أو موافقة تقديرية. اربط كل مبلغ بفترته ومعاملته المؤيدة. ميّز المعادلة المتفق عليها عن المكافأة التقديرية وسجّل أي تعديل للنظام.",
    "commission or bonus scheme, targets, sales and collection records, approval messages and prior calculations",
    "نظام العمولة أو المكافأة والأهداف وسجلات المبيعات والتحصيل ورسائل الموافقة والحسابات السابقة"),
  brief(["GOSI registration or contribution dispute"],
    "Which GOSI record or contribution period is disputed?", "ما القيد أو فترة الاشتراك المتنازع عليها في التأمينات الاجتماعية؟",
    "Compare the registered employer, service dates and wage information with the actual employment records. Identify whether the request concerns missing registration, an incorrect entry or contributions. Keep the authority's response and supporting payroll evidence together.",
    "قارن صاحب العمل المسجل وتواريخ الخدمة وبيانات الأجر بسجلات العمل الفعلية. حدّد هل الطلب بشأن غياب التسجيل أو خطأ في القيد أو الاشتراكات. اجمع رد الجهة مع أدلة الرواتب المؤيدة.",
    "GOSI record, contract, payroll evidence, joining and leaving dates and the correction or complaint response",
    "سجل التأمينات والعقد وإثبات الرواتب وتاريخي الالتحاق والمغادرة والرد على طلب التصحيح أو الشكوى"),
  brief(["Sick leave and annual leave entitlement dispute"],
    "How do I separate leave balance, approval and pay disputes?", "كيف أفصل خلاف رصيد الإجازة عن الموافقة والأجر؟",
    "Create a record of leave accrued, requested, approved and taken. Keep sickness-related documents separate from annual-leave records. Identify whether the dispute is about permission, classification, payment or a balance on exit; each needs its own supporting facts.",
    "أعد سجلاً للإجازة المتراكمة والمطلوبة والموافق عليها والمستعملة. افصل المستندات المرضية عن سجلات الإجازة السنوية. حدّد هل الخلاف على الإذن أو التصنيف أو الأجر أو رصيد المغادرة؛ فلكل منها وقائع مؤيدة خاصة.",
    "leave ledger, requests and approvals, medical certificates where relevant, payslips and exit calculation",
    "سجل الإجازات والطلبات والموافقات والشهادات الطبية عند صلتها وكشوف الأجر وحساب المغادرة"),
  brief(["Non-compete and confidentiality clause dispute"],
    "What activity does the restrictive clause actually cover?", "ما النشاط الذي يشمله الشرط المقيد فعلاً؟",
    "Identify the prohibited activity, duration, geography and information said to be confidential. Compare those terms with the proposed job or alleged disclosure. Confidentiality and non-compete obligations are different; enforceability should be assessed rather than assumed from the clause's presence.",
    "حدّد النشاط المحظور والمدة والنطاق الجغرافي والمعلومات المدعى بسريتها. قارن الشروط بالعمل المقترح أو الإفصاح المنسوب. السرية وعدم المنافسة التزامان مختلفان؛ ويجب تقييم قابلية الإنفاذ لا افتراضها لمجرد وجود الشرط.",
    "signed restriction, role description, proposed duties, confidentiality policy and the specific allegation or demand",
    "الشرط الموقع ووصف الوظيفة والمهام المقترحة وسياسة السرية والادعاء أو المطالبة المحددة"),
  brief(["Employment dispute after resignation or job transfer"],
    "Which obligations remain disputed after leaving the job?", "ما الالتزامات التي بقيت محل خلاف بعد ترك العمل؟",
    "Separate the resignation or transfer record from unpaid sums, notice, property return and restrictive clauses. Record what was handed over and any release signed. A change of employer does not by itself settle every claim arising from the previous relationship.",
    "افصل سجل الاستقالة أو النقل عن المبالغ غير المدفوعة والإخطار ورد العهد والقيود. وثّق ما سُلّم وأي مخالصة وُقعت. لا يحسم تغيير صاحب العمل وحده كل مطالبة ناشئة عن العلاقة السابقة.",
    "resignation and acceptance, handover record, transfer confirmation, settlement documents and outstanding-payment schedule",
    "الاستقالة وقبولها ومحضر التسليم وتأكيد النقل ومستندات التسوية وجدول المبالغ المتبقية"),
  brief(["Employment settlement and final-dues calculation"],
    "What should I check before signing an employment settlement?", "ما الذي أراجعه قبل توقيع تسوية عمالية؟",
    "Reconcile each payment item and identify the claims the document releases. Check the payment date, instalments, deductions and what happens if payment is delayed. Distinguish acknowledging money already received from agreeing to accept a future payment as settlement.",
    "طابق كل بند مالي وحدّد المطالبات التي تتناولها المخالصة. راجع تاريخ الدفع والأقساط والحسميات وأثر التأخر. ميّز الإقرار بمبلغ قُبض بالفعل عن الموافقة على اعتبار مبلغ مستقبلي تسوية.",
    "draft settlement, itemised dues, payments received, disputed claims and correspondence about payment conditions",
    "مسودة التسوية وتفصيل المستحقات والمدفوعات المستلمة والمطالبات المتنازع عليها ومراسلات شروط الدفع"),
  brief(["Residency or employment-status restriction affecting work authorisation"],
    "Which authority imposed the restriction affecting work?", "ما الجهة التي فرضت القيد المؤثر في العمل؟",
    "Obtain the actual notice and distinguish an immigration restriction from an employment record or permit issue. State current residence status, employer and intended work. A labour complaint may not resolve a separate immigration decision, so identify both files.",
    "احصل على الإخطار الفعلي وميّز قيد الإقامة عن مشكلة السجل العمالي أو التصريح. بيّن وضع الإقامة وصاحب العمل والعمل المقصود. قد لا تحسم الشكوى العمالية قراراً مستقلاً متعلقاً بالإقامة، لذا حدّد الملفين.",
    "residence and work-permit records, restriction notice, employment documents and authority application references",
    "سجلات الإقامة وتصريح العمل وإخطار القيد ومستندات التوظيف ومراجع الطلبات لدى الجهات"),
  brief(["Visa, exit and re-entry restriction affecting employment"],
    "Is the obstacle to travel, re-entry or continuing employment?", "هل العائق أمام السفر أم العودة أم استمرار العمل؟",
    "Identify the specific visa or travel restriction, the issuing authority and planned dates. Keep employer consent, immigration permission and any court restriction separate. Before making travel commitments, verify which record must be corrected or which decision requires a response.",
    "حدّد التأشيرة أو قيد السفر والجهة المصدرة والتواريخ المقترحة. افصل موافقة صاحب العمل عن إذن الإقامة وأي قيد قضائي. قبل الالتزام بالسفر تحقّق من السجل الواجب تصحيحه أو القرار الذي يحتاج إلى رد.",
    "passport and visa details, written restriction, travel history, employer correspondence and relevant case references",
    "بيانات الجواز والتأشيرة والقيد المكتوب وسجل السفر ومراسلات صاحب العمل ومراجع القضايا ذات الصلة"),
  brief(["Employment termination and labour-record dispute"],
    "Does the labour record accurately describe how employment ended?", "هل يصف السجل العمالي انتهاء العمل بدقة؟",
    "Compare the recorded exit reason and date with the contract, notice and actual last working day. Identify the consequences attributed to the entry and any rejected correction. Correcting the record and challenging the termination are related but separate requests.",
    "قارن سبب المغادرة وتاريخها المسجلين بالعقد والإخطار وآخر يوم عمل فعلي. حدّد الآثار المنسوبة للقيد وأي تصحيح رُفض. تصحيح السجل والطعن في الإنهاء طلبان مرتبطان لكنهما مستقلان.",
    "labour-record extract, termination or resignation papers, attendance evidence and correction correspondence",
    "مستخرج السجل العمالي وأوراق الإنهاء أو الاستقالة وإثبات الحضور ومراسلات التصحيح"),
  brief(["Correction of a work permit or labour record"],
    "Which field in the work permit or labour record needs correction?", "ما البيان الذي يحتاج إلى تصحيح في تصريح العمل أو السجل العمالي؟",
    "Identify the incorrect name, employer, occupation, date or status and the document supporting the replacement. Check whether the discrepancy appears in linked identity or employer records. A request to correct data is different from an application for new permission to work.",
    "حدّد الاسم أو صاحب العمل أو المهنة أو التاريخ أو الوضع غير الصحيح والمستند المؤيد للبديل. افحص تكرار الاختلاف في سجلات الهوية أو صاحب العمل المرتبطة. تصحيح البيانات يختلف عن طلب إذن جديد بالعمل.",
    "current permit or labour extract, supporting identity and employment records, correction request and authority response",
    "التصريح أو المستخرج العمالي الحالي ومستندات الهوية والعمل المؤيدة وطلب التصحيح ورد الجهة"),
];
