import { brief } from "./types.js";

export const FAMILY_BRIEFS = [
  brief(["Divorce and separation", "Divorce filing and personal-status procedure"],
    "What should I settle before starting a divorce application?", "ما الذي أحدده قبل البدء بطلب الطلاق؟",
    "Identify the marriage record, where each spouse lives, any existing proceedings and whether the separation is agreed or disputed. List custody, support, housing and property requests separately; ending the marriage does not itself answer every related question.",
    "حدّد وثيقة الزواج ومكان إقامة كل زوج والإجراءات القائمة وما إذا كان الانفصال اتفاقياً أم متنازعاً عليه. افصل طلبات الحضانة والنفقة والسكن والأموال؛ فإنهاء الزواج لا يحسم وحده كل مسألة مرتبطة به.",
    "marriage and identity records, existing court papers, separation correspondence and a list of the orders requested",
    "وثيقة الزواج والهوية وأوراق المحكمة القائمة ومراسلات الانفصال وقائمة الطلبات المراد تقديمها"),
  brief(["Child custody and visitation", "Child custody and visitation dispute"],
    "What information helps assess a proposed custody arrangement?", "ما المعلومات المفيدة لتقييم ترتيب حضانة مقترح؟",
    "Describe the child's present care, school, health needs and contact with each parent. Explain the arrangement requested and any immediate safety concern. Distinguish a new custody request from changing an existing order or enforcing missed visits.",
    "صف رعاية الطفل الحالية ومدرسته واحتياجاته الصحية وتواصله مع كل والد. وضّح الترتيب المطلوب وأي قلق عاجل على السلامة. ميّز طلب الحضانة الجديد عن تعديل حكم قائم أو تنفيذ زيارات لم تتم.",
    "birth and family records, existing custody orders, school and care schedules, relevant communications and documented safety concerns",
    "سجلات الميلاد والأسرة وأحكام الحضانة القائمة وجداول الدراسة والرعاية والمراسلات ذات الصلة ومخاوف السلامة الموثقة"),
  brief(["Alimony and child maintenance", "Alimony and child-maintenance claim"],
    "How should I organise a maintenance request or objection?", "كيف أنظم طلب النفقة أو الاعتراض عليه؟",
    "Separate the person claiming support, the period claimed, current expenses and payments already made. Keep child expenses distinct from spousal support. A budget explains the request, but entitlement, the recoverable period and the amount require the applicable family-law assessment.",
    "افصل صاحب طلب النفقة والفترة المطالب بها والمصروفات الحالية والمبالغ المدفوعة. ميّز مصروفات الطفل عن النفقة الزوجية. يوضح جدول المصروفات الطلب، لكن الاستحقاق والفترة القابلة للمطالبة والمبلغ تتطلب تقييماً وفق قانون الأسرة المنطبق.",
    "existing support orders, income records, housing and child-expense receipts, transfer records and a period-by-period calculation",
    "أحكام النفقة القائمة ومستندات الدخل وإيصالات السكن ومصروفات الأطفال والتحويلات وحساب مفصل لكل فترة"),
  brief(["Marriage and personal-status disputes"],
    "Which personal-status question needs a decision?", "ما مسألة الأحوال الشخصية التي تحتاج إلى حسم؟",
    "Identify whether the dispute concerns the existence or validity of the marriage, a recorded family status or an obligation arising from marriage. Compare the original documents with the entry or allegation disputed; nationality and foreign documents may change the assessment.",
    "حدّد هل الخلاف على وجود الزواج أو صحته أو الحالة الأسرية المسجلة أو التزام ناشئ عن الزواج. قارن الأصول بالقيد أو الادعاء المتنازع عليه؛ فقد تؤثر الجنسية والمستندات الأجنبية في التقييم.",
    "marriage documents, civil-status extracts, translations, prior decisions and the precise disputed entry or request",
    "وثائق الزواج ومستخرجات الحالة المدنية والترجمات والقرارات السابقة والقيد أو الطلب المحدد محل الخلاف"),
  brief(["Inheritance and family settlements"],
    "What should a family inheritance settlement identify?", "ما الذي ينبغي أن تحدده التسوية الأسرية بشأن الإرث؟",
    "List the estate assets and debts, everyone whose position is affected, and what each person proposes to receive or give up. Separate an agreement to discuss distribution from a binding transfer. Check authority, disputed entitlements and asset-transfer requirements before signing.",
    "احصر أموال التركة وديونها وكل من يتأثر مركزه وما يقترح أن يأخذه أو يتنازل عنه كل طرف. ميّز الاتفاق على مناقشة التوزيع عن نقل ملزم. تحقّق من الصفة والاستحقاقات المتنازع عليها ومتطلبات نقل الأموال قبل التوقيع.",
    "estate inventory, succession records, debt statements, draft settlement, valuations and any authority to sign for another person",
    "جرد التركة ومستندات الإرث وبيانات الديون ومسودة التسوية والتقييمات وأي تفويض بالتوقيع عن الغير"),
  brief(["Visitation order enforcement"],
    "What should I record when ordered visits do not take place?", "ماذا أوثق عندما لا تتم الزيارات المقررة؟",
    "Match each missed visit to the exact order: date, place, handover conditions and any explanation given. Preserve messages and neutral records. Enforcement of the current order differs from seeking a new schedule; urgent safety concerns also need a separate response.",
    "طابق كل زيارة لم تتم مع نص الحكم: التاريخ والمكان وشروط التسليم والتفسير المذكور. احفظ الرسائل والسجلات المحايدة. يختلف تنفيذ الحكم القائم عن طلب جدول جديد، كما تحتاج مخاوف السلامة العاجلة إلى استجابة مستقلة.",
    "the visitation order, service record, dated visit log, handover correspondence and previous enforcement papers",
    "حكم الزيارة وإثبات تبليغه وسجل الزيارات المؤرخ ومراسلات التسليم وأوراق التنفيذ السابقة"),
  brief(["Child relocation and travel disputes", "Child relocation and travel dispute"],
    "How does permanent relocation differ from a short trip?", "كيف يختلف الانتقال الدائم بالطفل عن رحلة قصيرة؟",
    "Specify the destination, duration, return plan and effect on schooling and contact with the other parent. Provide existing custody and travel orders and any consent. Do not treat passport possession as resolving authority to travel or relocate.",
    "حدّد الوجهة والمدة وخطة العودة وأثر السفر في الدراسة والتواصل مع الوالد الآخر. قدّم أحكام الحضانة والسفر القائمة وأي موافقة. لا تعتبر حيازة جواز السفر حاسمة لصلاحية السفر أو الانتقال الدائم.",
    "custody and travel orders, consent correspondence, proposed itinerary, school arrangements and the child's relevant travel records",
    "أحكام الحضانة والسفر ومراسلات الموافقة وخطة الرحلة وترتيبات الدراسة وسجلات سفر الطفل ذات الصلة"),
  brief(["Recognition of foreign family judgments", "Recognition of foreign family judgment"],
    "What is needed to assess a foreign family judgment?", "ما المطلوب لتقييم حكم أسري أجنبي؟",
    "Identify the issuing court, what the judgment actually decides and where its effect is sought. Record finality, service and any appeal. Recognition of marital status and enforcement of money or custody provisions may raise different questions.",
    "حدّد المحكمة المصدرة وما قضى به الحكم فعلاً والدولة التي يطلب ترتيب أثره فيها. وثّق نهائيته والتبليغ وأي طعن. قد تختلف مسائل الاعتراف بالحالة الزوجية عن تنفيذ مبالغ أو أحكام حضانة.",
    "the complete judgment, finality and service records, translations, appeal information and the specific local effect requested",
    "الحكم كاملاً ومستندات النهائية والتبليغ والترجمات ومعلومات الطعن والأثر المحلي المحدد المطلوب"),
  brief(["Recognition and enforcement of a Syrian family judgment"],
    "What should I clarify before using a Syrian family judgment abroad?", "ما الذي أوضحه قبل استعمال حكم أسري سوري في الخارج؟",
    "State the destination country and whether the aim is updating a civil record, obtaining support or implementing custody provisions. Obtain the complete Syrian judgment and available service and finality records. The receiving jurisdiction determines its recognition and enforcement requirements.",
    "حدّد دولة الاستعمال وهل الغرض تحديث قيد مدني أو تحصيل نفقة أو تنفيذ أحكام حضانة. احصل على الحكم السوري كاملاً ومستندات التبليغ والنهائية المتاحة. يحدد اختصاص الدولة المستقبلة متطلبات الاعتراف والتنفيذ.",
    "Syrian judgment and case reference, finality evidence, service records, destination-country correspondence and required translations",
    "الحكم السوري ورقم الدعوى وإثبات النهائية وسجلات التبليغ ومراسلات دولة الاستعمال والترجمات المطلوبة"),
  brief(["Paternity dispute"],
    "What is the precise issue in a paternity dispute?", "ما المسألة المحددة في منازعة النسب؟",
    "Distinguish establishing parentage, challenging a recorded relationship and correcting a clerical entry. Identify existing family records and proceedings. Medical testing, if relevant, must be considered within the applicable legal process; a private result alone does not resolve the civil record.",
    "ميّز إثبات النسب عن منازعة صلة مسجلة وتصحيح خطأ كتابي. حدّد قيود الأسرة والإجراءات القائمة. يُبحث الفحص الطبي عند صلته بالمسألة ضمن المسار القانوني المنطبق؛ ولا تحسم نتيجة خاصة وحدها القيد المدني.",
    "birth and marriage records, existing parentage entries, prior orders and correspondence identifying the disputed relationship",
    "قيود الميلاد والزواج وبيانات النسب المسجلة والقرارات السابقة والمراسلات المحددة للصلة المتنازع عليها"),
  brief(["Khulʿ and marriage-annulment dispute"],
    "Why does the requested form of marriage dissolution matter?", "لماذا يهم تحديد نوع إنهاء الزواج المطلوب؟",
    "Explain the facts relied on, whether the other spouse agrees, any proposed financial terms and existing proceedings. Khulʿ and annulment should not be used as interchangeable labels: the grounds, proof and consequences must be checked for the actual request.",
    "بيّن الوقائع المستند إليها وموافقة الزوج الآخر أو معارضته والشروط المالية المقترحة والإجراءات القائمة. لا تُستخدم تسميتا الخلع والفسخ بالتبادل؛ إذ يلزم فحص الأسباب والإثبات والآثار بحسب الطلب الفعلي.",
    "marriage contract, relevant correspondence, proposed financial terms, evidence supporting the stated grounds and existing case papers",
    "عقد الزواج والمراسلات ذات الصلة والشروط المالية المقترحة وأدلة الأسباب المذكورة وأوراق الدعوى القائمة"),
  brief(["Domestic-violence protection and family-safety application"],
    "What comes first when family safety is at risk?", "ما الأولوية عندما تكون سلامة الأسرة معرضة للخطر؟",
    "If there is immediate danger, contact local emergency or protection services and prioritise a safe location. When safe, record the incident and any existing protection order. A legal consultation is not an emergency-response service and should not delay urgent assistance.",
    "عند الخطر الفوري تواصل مع خدمات الطوارئ أو الحماية المحلية وأعط الأولوية لمكان آمن. وحين يصبح ذلك آمناً وثّق الواقعة وأي أمر حماية قائم. الاستشارة القانونية ليست خدمة استجابة طارئة، ولا ينبغي أن تؤخر المساعدة العاجلة.",
    "available incident and medical records, existing protection orders and relevant messages, gathered only when safe",
    "محاضر الوقائع والتقارير الطبية المتاحة وأوامر الحماية القائمة والرسائل ذات الصلة، عند إمكان جمعها بأمان"),
  brief(["Marital-status document and record correction"],
    "Is the marital-status problem a recording error or a disputed legal status?", "هل مشكلة الحالة الزوجية خطأ في القيد أم نزاع في الحالة القانونية؟",
    "Compare the disputed entry with the document that should support it. Identify the date, name or status to be corrected and the authority's written response. A clerical correction differs from obtaining recognition of a marriage, divorce or foreign judgment.",
    "قارن القيد المختلف عليه بالمستند المفترض أن يؤيده. حدّد التاريخ أو الاسم أو الحالة المراد تصحيحها ورد الجهة المكتوب. يختلف التصحيح الكتابي عن استصدار الاعتراف بزواج أو طلاق أو حكم أجنبي.",
    "current civil extract, underlying marriage or divorce record, identity documents and the rejected correction request",
    "المستخرج المدني الحالي ووثيقة الزواج أو الطلاق الأصلية ومستندات الهوية وطلب التصحيح المرفوض"),
  brief(["Marriage registration and family-status certificate problem", "Marriage registration and certificate problem"],
    "What should I do when a marriage certificate is refused or incomplete?", "ماذا أفعل عند رفض شهادة الزواج أو نقصها؟",
    "Obtain the reason for refusal and identify whether the marriage has already been registered. Separate missing documents, inconsistent names and recognition of a foreign marriage. The required application depends on the authority and the record that already exists.",
    "احصل على سبب الرفض وحدّد هل سُجّل الزواج أصلاً. افصل نقص المستندات عن اختلاف الأسماء والاعتراف بزواج أجنبي. يتوقف الطلب المناسب على الجهة والقيد الموجود بالفعل.",
    "marriage instrument, registration or application reference, identity and civil records, translations and the refusal or deficiency notice",
    "وثيقة الزواج ومرجع التسجيل أو الطلب والهوية والقيود المدنية والترجمات وإخطار الرفض أو النقص"),
  brief(["Family-status document or civil-record correction"],
    "How do I identify the correct civil-record correction?", "كيف أحدد التصحيح المطلوب في السجل المدني؟",
    "Quote the exact entry to be corrected, its source and the proposed replacement supported by documents. Identify which other records repeat the discrepancy. A correction to one record may leave linked identity, family or property records requiring separate attention.",
    "بيّن القيد المراد تصحيحه حرفياً ومصدره والبديل المقترح المؤيد بالمستندات. حدّد القيود الأخرى التي تكرر الاختلاف. قد يستلزم تصحيح سجل واحد معالجة مستقلة لسجلات هوية أو أسرة أو ملكية مرتبطة به.",
    "current and historical civil extracts, supporting originals, linked records and the registration authority's correspondence",
    "المستخرجات المدنية الحالية والسابقة والأصول المؤيدة والقيود المرتبطة ومراسلات جهة التسجيل"),
  brief(["Inheritance distribution dispute"],
    "What must be resolved before disputed estate assets can be distributed?", "ما الذي يلزم بحثه قبل توزيع أموال تركة متنازع عليها؟",
    "Identify the beneficiaries claimed, estate assets, debts, any will and transfers already made. Specify whether the disagreement concerns entitlement, valuation or the proposed allocation. A proposed share should not be calculated without the relevant family and asset facts.",
    "حدّد المستفيدين المدعى باستحقاقهم وأموال التركة وديونها وأي وصية والتحويلات المنفذة. بيّن هل الخلاف على الاستحقاق أو التقييم أو طريقة التوزيع. لا تُحسب حصة مقترحة دون الوقائع الأسرية والمالية ذات الصلة.",
    "succession and death records, estate inventory, debt evidence, wills, valuations and records of prior distributions",
    "مستندات الإرث والوفاة وجرد التركة وإثبات الديون والوصايا والتقييمات وسجلات التوزيعات السابقة"),
];
