import { brief } from "./types.js";
export const PROPERTY_BRIEFS = [
  brief(["Property ownership disputes"],
    "What distinguishes ownership from occupation or a promise to sell?", "ما الذي يميز الملكية عن الإشغال أو الوعد بالبيع؟",
    "Identify the property precisely and compare the competing basis of ownership: registration, inheritance, a sale or another asserted right. Occupation and payments are relevant facts but should not be treated as substitutes for reviewing the title and transaction history.",
    "حدّد العقار بدقة وقارن أساس الملكية لدى الأطراف: التسجيل أو الإرث أو البيع أو حق آخر مدعى به. الإشغال والمدفوعات وقائع مهمة، لكنهما لا يغنيان عن مراجعة السند وتسلسل التصرفات.",
    "title records, property identifiers, transaction chain, inheritance documents where relevant and evidence of possession",
    "قيود الملكية ومعرّفات العقار وتسلسل التصرفات ومستندات الإرث عند صلتها وإثبات الحيازة"),
  brief(["Sale and purchase contract disputes"],
    "Which obligation in the property sale has not been performed?", "ما الالتزام غير المنفذ في بيع العقار؟",
    "Separate payment, title transfer, discharge of existing charges and physical handover. Compare the agreed sequence with what occurred and identify any conditions still outstanding. A claim for completion differs from cancellation or compensation for a failed sale.",
    "افصل السداد ونقل الملكية وفك القيود القائمة والتسليم الفعلي. قارن التسلسل المتفق عليه بما حدث وحدّد الشروط التي لم تُستكمل. تختلف مطالبة إتمام البيع عن الفسخ أو التعويض عن تعثره.",
    "sale contract and amendments, title information, payment records, completion conditions and handover correspondence",
    "عقد البيع وتعديلاته وبيانات الملكية وسجلات السداد وشروط الإتمام ومراسلات التسليم"),
  brief(["Lease and eviction matters"],
    "Is the tenancy dispute about renewal, rent or ending occupation?", "هل النزاع الإيجاري على التجديد أم الأجرة أم إنهاء الإشغال؟",
    "Identify the lease term, current occupation and exact demand made by the landlord or tenant. Separate renewal, unpaid rent, termination and physical eviction. The notice, reason given and procedural stage determine which question needs to be addressed first.",
    "حدّد مدة العقد والإشغال الحالي والمطلب الدقيق للمؤجر أو المستأجر. افصل التجديد عن الأجرة المتأخرة والإنهاء والإخلاء الفعلي. يحدد الإخطار وسببه والمرحلة الإجرائية المسألة التي تحتاج إلى معالجة أولاً.",
    "lease and renewal history, rent ledger, notices and service evidence, occupancy records and any case papers",
    "العقد وسجل التجديد وبيان الأجرة والإخطارات وإثبات تبليغها وسجلات الإشغال وأوراق الدعوى إن وجدت"),
  brief(["Registration and title problems"],
    "Why has registration or transfer of title not been completed?", "لماذا لم يكتمل التسجيل أو نقل الملكية؟",
    "Obtain the registry's stated reason and identify the missing consent, document, payment or correction. Distinguish an incomplete application from a competing ownership claim. The next step depends on whether the obstacle is administrative, contractual or a recorded restriction.",
    "احصل على سبب جهة التسجيل وحدّد الموافقة أو المستند أو السداد أو التصحيح الناقص. ميّز الطلب غير المكتمل عن ادعاء ملكية منافس. تتوقف الخطوة التالية على كون العائق إدارياً أو عقدياً أو قيداً مسجلاً.",
    "current title extract, transfer application, transaction documents, restriction entries and registry correspondence",
    "مستخرج الملكية الحالي وطلب النقل ومستندات المعاملة والقيود المسجلة ومراسلات التسجيل"),
  brief(["Construction and contractor claims"],
    "Which construction obligation or payment is disputed?", "ما الالتزام أو الدفعة المتنازع عليها في المقاولة؟",
    "Identify the contract scope, approved variations, completed work and certification history. Separate payment claims from delay, defects and termination. Match each disputed amount or task to the relevant instruction and record rather than relying on a single overall project figure.",
    "حدّد نطاق العقد والتغييرات المعتمدة والأعمال المنجزة وسجل اعتمادها. افصل مطالبات الدفع عن التأخير والعيوب والإنهاء. اربط كل مبلغ أو مهمة بالتكليف والسجل المعنيين بدلاً من الاعتماد على إجمالي واحد للمشروع.",
    "construction contract, drawings, variation orders, progress records, payment certificates and notices",
    "عقد المقاولة والمخططات وأوامر التغيير وسجلات التقدم ومستخلصات الدفع والإخطارات"),
  brief(["Eviction notice and eviction dispute"],
    "What should I check when I receive an eviction notice?", "ما الذي أراجعه عند استلام إخطار إخلاء؟",
    "Keep the complete notice and record how and when it arrived. Compare its stated ground and requested departure date with the tenancy history. A notice is not the same as an enforceable eviction order; establish the current stage before choosing a response.",
    "احفظ الإخطار كاملاً وسجّل كيفية وصوله وتاريخه. قارن سببه وموعد المغادرة المطلوب بسجل الإيجار. الإخطار ليس هو نفسه حكم الإخلاء القابل للتنفيذ؛ حدّد المرحلة الحالية قبل اختيار الرد.",
    "eviction notice and envelope or delivery record, lease, renewal correspondence, rent payments and existing orders",
    "إخطار الإخلاء وظرفه أو إثبات وصوله والعقد ومراسلات التجديد وسداد الأجرة والأحكام القائمة"),
  brief(["Unpaid rent and rental payment claim"],
    "How can I reconcile a disputed rent balance?", "كيف أطابق رصيد أجرة متنازعاً عليه؟",
    "List each rental period, agreed amount, payment, credit and deduction separately. Identify whether the disagreement concerns non-payment, allocation of a payment or the rent demanded. Keep rent distinct from deposits, service charges and repair claims.",
    "افصل كل فترة إيجارية وأجرتها ومدفوعاتها وإشعاراتها الدائنة وحسمياتها. حدّد هل الخلاف على عدم الدفع أو تخصيص دفعة أو مقدار الأجرة المطلوبة. افصل الأجرة عن التأمين ورسوم الخدمات ومطالبات الإصلاح.",
    "lease, period-by-period rent ledger, receipts and bank transfers, returned-payment records and payment demands",
    "العقد وجدول الأجرة لكل فترة والإيصالات والتحويلات وسجلات الدفعات المرتجعة ومطالبات السداد"),
  brief(["Construction delay and defective construction"],
    "How should delay and defect allegations be separated?", "كيف أفصل ادعاء التأخير عن ادعاء العيوب الإنشائية؟",
    "Build a delay chronology against the agreed programme and a separate defect schedule showing location, specification and evidence. Record access, variations and remedial offers. Delay, defective work and the cost of correction should not be combined without explaining their causal links.",
    "أعد تسلسلاً للتأخير مقارنة بالبرنامج المتفق عليه وجدول عيوب مستقلاً يوضح الموقع والمواصفة والدليل. سجّل إتاحة الموقع والتغييرات وعروض الإصلاح. لا تدمج التأخير والعيوب وتكلفة التصحيح دون بيان الروابط السببية.",
    "programme and extensions, site records, approved variations, defect photographs, inspection reports and remedial quotations",
    "البرنامج والتمديدات وسجلات الموقع والتغييرات المعتمدة وصور العيوب وتقارير الفحص وعروض الإصلاح"),
  brief(["Title deed and registration dispute"],
    "Which part of the registered title is being challenged?", "أي جزء من سند الملكية المسجل محل المنازعة؟",
    "Identify the disputed owner, share, property description or restriction and the transaction said to justify changing it. Compare current and historical extracts. A challenge to the underlying right differs from correcting a typing or measurement error in the registry.",
    "حدّد المالك أو الحصة أو وصف العقار أو القيد المتنازع عليه والتصرف المستند إليه لطلب تغييره. قارن المستخرجات الحالية والسابقة. يختلف الطعن في أصل الحق عن تصحيح خطأ كتابي أو مساحي في السجل.",
    "current and historical title extracts, disputed transaction, plans, registry decision and competing ownership evidence",
    "مستخرجات الملكية الحالية والسابقة والتصرف المتنازع عليه والمخططات وقرار التسجيل وأدلة الملكية المتعارضة"),
  brief(["Property encroachment and boundary dispute"],
    "How can I distinguish a boundary error from physical encroachment?", "كيف أميز خطأ الحدود عن التعدي الفعلي على العقار؟",
    "Compare the registered plan, survey markers and actual occupation. Identify the fence, structure or use said to cross the boundary and when it appeared. A survey discrepancy and a claim to remove an encroachment may need different evidence and remedies.",
    "قارن المخطط المسجل والعلامات المساحية والإشغال الفعلي. حدّد السور أو البناء أو الاستخدام المدعى بتجاوزه الحدود وتاريخ ظهوره. قد يحتاج اختلاف المساحة وطلب إزالة التعدي إلى أدلة ومعالجات مختلفة.",
    "title and cadastral plans, survey reports, dated site photographs, neighbour correspondence and construction records",
    "السند والمخططات العقارية وتقارير المساحة وصور الموقع المؤرخة ومراسلات الجار وسجلات البناء"),
  brief(["Expropriation and compensation claim"],
    "Is the dispute about the taking, valuation or payment of compensation?", "هل النزاع على نزع الملكية أم التقييم أم صرف التعويض؟",
    "Identify the formal decision, affected parcel, valuation date and compensation offered or paid. Separate a challenge to the decision from a valuation objection or payment delay. Preserve notification evidence because the available response depends on the applicable process and stage.",
    "حدّد القرار الرسمي والعقار المتأثر وتاريخ التقييم والتعويض المعروض أو المدفوع. افصل الطعن في القرار عن اعتراض التقييم أو تأخر الصرف. احفظ إثبات التبليغ لأن الرد المتاح يتوقف على الإجراء المنطبق ومرحلته.",
    "expropriation notice, title, parcel plan, valuation report, comparable evidence and compensation payment records",
    "إخطار نزع الملكية والسند ومخطط العقار وتقرير التقييم وأدلة المقارنة وسجلات صرف التعويض"),
  brief(["Ejar rental contract and registration dispute"],
    "Does the Ejar record match the tenancy actually agreed?", "هل يطابق سجل إيجار العلاقة الإيجارية المتفق عليها؟",
    "Compare the registered parties, property, term and payment schedule with the signed agreement and actual payments. Identify the disputed platform entry or rejected transaction. A registration problem and a substantive rent or eviction dispute should be assessed separately.",
    "قارن الأطراف والعقار والمدة وجدول الدفع المسجلين بالاتفاق الموقع والسداد الفعلي. حدّد بيان المنصة المختلف عليه أو العملية المرفوضة. يلزم تقييم مشكلة التسجيل بصورة مستقلة عن نزاع الأجرة أو الإخلاء الموضوعي.",
    "Ejar contract and transaction reference, signed agreement, payment records, screenshots of the disputed entry and support response",
    "عقد إيجار ومرجع العملية والاتفاق الموقع وسجلات الدفع وصور البيان المختلف عليه ورد الدعم"),
  brief(["Off-plan property purchase and developer delay claim"],
    "What should I compare when an off-plan handover is delayed?", "ما الذي أقارنه عند تأخر تسليم عقار على الخارطة؟",
    "Compare the contractual completion date, permitted extensions, construction updates and your payment position. Record the developer's revised dates and explanation. Continuing the purchase, seeking cancellation and claiming loss are different objectives that need the contract and project status reviewed.",
    "قارن موعد الإنجاز العقدي والتمديدات المسموح بها وتحديثات البناء ووضع سدادك. وثّق مواعيد المطور المعدلة وتفسيره. الاستمرار في الشراء وطلب الفسخ والمطالبة بالخسارة أهداف مختلفة تحتاج إلى مراجعة العقد وحالة المشروع.",
    "off-plan purchase agreement, project registration information, payment schedule, progress notices and handover promises",
    "عقد الشراء على الخارطة وبيانات تسجيل المشروع وجدول السداد وإخطارات التقدم ووعود التسليم"),
  brief(["Mortgage, financing and property-lien dispute"],
    "Is the disagreement about the financing debt or the property security?", "هل الخلاف على دين التمويل أم الضمان العقاري؟",
    "Separate the outstanding financing amount from the scope and registration of the mortgage or lien. Identify the secured party, default notice and proposed enforcement. A payment dispute does not itself explain whether a registered security can be released or enforced.",
    "افصل مبلغ التمويل المتبقي عن نطاق الرهن أو الحق المسجل. حدّد صاحب الضمان وإخطار التعثر والتنفيذ المقترح. لا يفسر نزاع الدفع وحده إمكان فك ضمان مسجل أو تنفيذه.",
    "finance agreement, security instrument, title restrictions, account statement, default notices and release correspondence",
    "اتفاق التمويل وسند الضمان وقيود الملكية وكشف الحساب وإخطارات التعثر ومراسلات فك الضمان"),
  brief(["Foreign property ownership eligibility problem"],
    "Which buyer and property details determine the ownership review?", "ما بيانات المشتري والعقار اللازمة لمراجعة أهلية التملك؟",
    "Identify the buyer's nationality and legal form, the property's exact location and use, and the right proposed to be acquired. Check the applicable framework before committing funds. Eligibility may depend on the particular area, buyer and transaction rather than a country-wide assumption.",
    "حدّد جنسية المشتري وشكله القانوني وموقع العقار واستعماله والحق المراد اكتسابه. تحقّق من الإطار المنطبق قبل الالتزام بمبالغ. قد تتوقف الأهلية على المنطقة والمشتري والمعاملة بدلاً من افتراض عام لكل الدولة.",
    "buyer identity or incorporation records, property location and title, proposed transaction and authority correspondence",
    "هوية المشتري أو مستندات تأسيسه وموقع العقار وسنده والمعاملة المقترحة ومراسلات الجهة"),
  brief(["Property handover and defects after purchase"],
    "How should I record defects discovered at or after handover?", "كيف أوثق العيوب المكتشفة عند تسليم العقار أو بعده؟",
    "Create a dated list showing each defect, its location, photographs and when the seller was notified. Keep acceptance documents and any reservations made at handover. Distinguish unfinished work, visible defects and later-discovered problems before assessing the requested correction or claim.",
    "أعد قائمة مؤرخة لكل عيب وموقعه وصوره وتاريخ إبلاغ البائع. احفظ مستندات القبول والتحفظات عند التسليم. ميّز الأعمال الناقصة والعيوب الظاهرة والمشكلات المكتشفة لاحقاً قبل تقييم الإصلاح أو المطالبة المطلوبة.",
    "sale specification, handover and snagging reports, dated photographs, seller notices and repair assessments",
    "مواصفات البيع ومحاضر التسليم والملاحظات والصور المؤرخة وإخطارات البائع وتقييمات الإصلاح"),
  brief(["Landlord or tenant notice and settlement problem", "Landlord notice and tenant settlement problem"],
    "What should a tenancy settlement say about departure and payment?", "ماذا ينبغي أن توضح التسوية الإيجارية بشأن المغادرة والسداد؟",
    "Specify the departure date, rent balance, deposit treatment, keys, property condition and claims being released. Compare the proposal with existing notices or proceedings. A promise to leave and an acknowledgement of money owed should not be left ambiguous.",
    "حدّد موعد المغادرة ورصيد الأجرة ومصير التأمين والمفاتيح وحالة العقار والمطالبات المشمولة بالمخالصة. قارن المقترح بالإخطارات أو الإجراءات القائمة. ينبغي ألا يبقى التعهد بالمغادرة أو الإقرار بالدين غامضاً.",
    "lease, notices, settlement draft, rent and deposit reconciliation and proposed handover terms",
    "العقد والإخطارات ومسودة التسوية ومطابقة الأجرة والتأمين وشروط التسليم المقترحة"),
  brief(["Shared-building expenses and maintenance dispute"],
    "What makes a shared-building expense payable in this Syrian property?", "ما أساس استحقاق نفقة البناء المشتركة في هذا العقار السوري؟",
    "Identify the repair or shared expense, the responsible parties and its basis in the lease, ownership records or an agreement. Compare invoices with work performed and any agreed allocation. Do not assume a Gulf owners-association charging system applies to the building.",
    "حدّد الإصلاح أو النفقة المشتركة والأطراف المسؤولة وأساسها في عقد الإيجار أو سجلات الملكية أو الاتفاق. قارن الفواتير بالأعمال المنفذة وتوزيع التكلفة المتفق عليه. ولا تفترض خضوع البناء لنظام رسوم جمعية ملاك مطبق في دولة خليجية.",
    "lease or ownership records, expense agreement, invoices, maintenance requests and responses",
    "عقد الإيجار أو سجلات الملكية واتفاق النفقات والفواتير وطلبات الصيانة والردود"),
  brief(["Property service-charge and maintenance dispute"],
    "Who is responsible for the disputed charge or maintenance item?", "من المسؤول عن الرسم أو بند الصيانة المتنازع عليه؟",
    "Identify the charge period, service provided and contractual or recorded basis for allocation. Separate routine maintenance, major repair and owner-association charges. Compare invoices, budgets and notices with the party's actual responsibility before accepting the balance claimed.",
    "حدّد فترة الرسم والخدمة وأساس توزيع التكلفة في العقد أو السجل. افصل الصيانة المعتادة والإصلاح الكبير ورسوم جمعية الملاك. قارن الفواتير والموازنات والإخطارات بمسؤولية الطرف الفعلية قبل قبول الرصيد المطلوب.",
    "lease or ownership documents, charge statements, maintenance requests, invoices, budgets and management replies",
    "مستندات الإيجار أو الملكية وكشوف الرسوم وطلبات الصيانة والفواتير والموازنات وردود الإدارة"),
  brief(["Land-registry and title-record correction"],
    "What evidence supports the proposed land-register correction?", "ما الدليل المؤيد لتصحيح القيد العقاري المقترح؟",
    "Identify the exact entry, the source of the error and the documents supporting the replacement. Check whether owners, shares, parcel details or restrictions are affected. A correction that changes substantive rights needs different assessment from a clerical inconsistency.",
    "حدّد القيد بدقة ومصدر الخطأ والمستندات المؤيدة للبديل. افحص تأثر أسماء الملاك أو الحصص أو بيانات العقار أو القيود. يحتاج التصحيح المغير للحقوق الموضوعية إلى تقييم يختلف عن اختلاف كتابي.",
    "current and earlier registry extracts, original supporting instruments, survey material and the rejected correction request",
    "المستخرجات الحالية والسابقة والأصول المؤيدة والمواد المساحية وطلب التصحيح المرفوض"),
  brief(["Property possession and handover dispute"],
    "What gives each party the claimed right to possess the property?", "ما أساس حق كل طرف المدعى به في حيازة العقار؟",
    "Record who currently occupies the property, under which agreement or order, and the promised handover conditions. Distinguish a demand for possession from a title dispute or repair claim. Avoid changing locks or removing property without assessing the lawful route.",
    "سجّل من يشغل العقار حالياً وبموجب أي اتفاق أو حكم وشروط التسليم الموعودة. ميّز طلب الحيازة عن نزاع الملكية أو الإصلاح. تجنب تغيير الأقفال أو إخراج الممتلكات دون تقييم المسار القانوني.",
    "occupancy agreement or order, title information, handover promises, key records and correspondence about access",
    "اتفاق الإشغال أو الحكم وبيانات الملكية ووعود التسليم وسجلات المفاتيح ومراسلات الدخول"),
  brief(["Bounced rental cheque"],
    "How does a returned rental cheque affect the tenancy dispute?", "كيف يرتبط الشيك الإيجاري المرتجع بالنزاع الإيجاري؟",
    "Record the bank's return reason, the rental period covered and any replacement payment. Separate the instrument, underlying rent balance and any existing complaint or enforcement step. A returned cheque should not be treated as proving every alleged consequence automatically.",
    "سجّل سبب الإرجاع المصرفي والفترة الإيجارية وأي دفعة بديلة. افصل الشيك عن رصيد الأجرة وأي شكوى أو تنفيذ قائم. لا يُعامل ارتجاع الشيك بوصفه مثبتاً تلقائياً لكل أثر مدعى به.",
    "cheque copy and return memo, tenancy contract, rent ledger, replacement payments and any notice or case reference",
    "صورة الشيك وإشعار الإرجاع وعقد الإيجار وبيان الأجرة والدفعات البديلة وأي إخطار أو مرجع قضية"),
  brief(["Dubai tenancy and Rental Disputes Center claim"],
    "Is the Dubai rental issue registration, a rent proposal or a filed dispute?", "هل المسألة الإيجارية في دبي تسجيل أم اقتراح أجرة أم نزاع مقيد؟",
    "Identify the property and Ejari record, the rent or notice being disputed and any Rental Disputes Center case. An index result, registration transaction and judicial decision have different roles. Match the question to the relevant Dubai service and current tenancy facts.",
    "حدّد العقار وسجل إيجاري والأجرة أو الإخطار المتنازع عليه وأي ملف بمركز فض المنازعات الإيجارية. لنتيجة المؤشر ومعاملة التسجيل والقرار القضائي أدوار مختلفة. اربط السؤال بالخدمة المناسبة في دبي ووقائع الإيجار الحالية.",
    "Ejari and lease, rent proposal or notice, relevant index result, payment history and Rental Disputes Center correspondence",
    "إيجاري والعقد واقتراح الأجرة أو الإخطار ونتيجة المؤشر ذات الصلة وسجل الدفع ومراسلات مركز فض المنازعات الإيجارية"),
];
